/// Bank soal Simulasi Tes Akademik CAT AKPOL dari TB XI.
class AkpolCatQuestion {
  final int number;
  final String category;
  final String question;
  final List<String> options;
  final int answer;
  final String explanation;

  const AkpolCatQuestion({
    required this.number,
    required this.category,
    required this.question,
    required this.options,
    required this.answer,
    required this.explanation,
  });
}

const akpolCatQuestions = <AkpolCatQuestion>[
  AkpolCatQuestion(
    number: 1,
    category: 'TPA Verbal',
    question: 'Sinonim kata kredibel adalah ...',
    options: [
      'meragukan',
      'dapat dipercaya',
      'sementara',
      'terkenal',
      'berlebihan',
    ],
    answer: 1,
    explanation: 'Kredibel berarti dapat dipercaya.',
  ),
  AkpolCatQuestion(
    number: 2,
    category: 'TPA Verbal',
    question: 'Antonim kata transparan adalah ...',
    options: ['terbuka', 'jelas', 'tertutup', 'terang', 'jujur'],
    answer: 2,
    explanation: 'Lawan transparan adalah tertutup/tidak terbuka.',
  ),
  AkpolCatQuestion(
    number: 3,
    category: 'TPA Verbal',
    question: 'Dokter : pasien = guru : ...',
    options: ['buku', 'sekolah', 'murid', 'kelas', 'ujian'],
    answer: 2,
    explanation: 'Dokter menangani pasien; guru mengajar murid.',
  ),
  AkpolCatQuestion(
    number: 4,
    category: 'TPA Verbal',
    question: 'Kata yang tidak sekelompok adalah ...',
    options: ['mawar', 'melati', 'anggrek', 'mangga', 'tulip'],
    answer: 3,
    explanation: 'Mangga adalah buah, lainnya bunga.',
  ),
  AkpolCatQuestion(
    number: 5,
    category: 'TPA Verbal',
    question: 'Makna kata objektif adalah ...',
    options: [
      'berdasarkan perasaan',
      'berdasarkan fakta',
      'memihak teman',
      'sulit dipahami',
      'bersifat rahasia',
    ],
    answer: 1,
    explanation: 'Objektif berarti berdasarkan fakta dan tidak memihak.',
  ),
  AkpolCatQuestion(
    number: 6,
    category: 'TPA Numerik',
    question: '25% dari 360 adalah ...',
    options: ['60', '75', '90', '100', '120'],
    answer: 2,
    explanation: '0,25 x 360 = 90.',
  ),
  AkpolCatQuestion(
    number: 7,
    category: 'TPA Numerik',
    question: 'Barisan 5, 10, 20, 40, ...',
    options: ['50', '60', '70', '80', '100'],
    answer: 3,
    explanation: 'Setiap suku dikali 2.',
  ),
  AkpolCatQuestion(
    number: 8,
    category: 'TPA Numerik',
    question: 'Jika 2x + 9 = 25, x = ...',
    options: ['6', '7', '8', '9', '10'],
    answer: 2,
    explanation: '2x=16, jadi x=8.',
  ),
  AkpolCatQuestion(
    number: 9,
    category: 'TPA Numerik',
    question: 'Rata-rata 60, 70, 80, 90 adalah ...',
    options: ['65', '70', '75', '80', '85'],
    answer: 2,
    explanation: 'Jumlah 300 dibagi 4 = 75.',
  ),
  AkpolCatQuestion(
    number: 10,
    category: 'TPA Numerik',
    question: 'Perbandingan A:B=2:3. Jika jumlahnya 50, nilai B ...',
    options: ['20', '25', '30', '35', '40'],
    answer: 2,
    explanation: 'B=3/5 x 50 = 30.',
  ),
  AkpolCatQuestion(
    number: 11,
    category: 'TPA Numerik',
    question: 'Sebuah kendaraan melaju 72 km/jam selama 2,5 jam. Jaraknya ...',
    options: ['144 km', '160 km', '180 km', '200 km', '216 km'],
    answer: 2,
    explanation: 'Jarak=72 x 2,5 = 180 km.',
  ),
  AkpolCatQuestion(
    number: 12,
    category: 'TPA Numerik',
    question: 'Luas lingkaran berjari-jari 7 cm (π=22/7) ...',
    options: ['44 cm2', '88 cm2', '154 cm2', '308 cm2', '616 cm2'],
    answer: 2,
    explanation: 'Luas=22/7 x 7 x 7 = 154 cm2.',
  ),
  AkpolCatQuestion(
    number: 13,
    category: 'TPA Numerik',
    question: 'Harga Rp200.000 naik 10%, menjadi ...',
    options: ['Rp210.000', 'Rp215.000', 'Rp220.000', 'Rp225.000', 'Rp230.000'],
    answer: 2,
    explanation: 'Kenaikan Rp20.000.',
  ),
  AkpolCatQuestion(
    number: 14,
    category: 'TPA Logika',
    question: 'Semua polisi wajib disiplin. Raka adalah polisi. Kesimpulan ...',
    options: [
      'Raka mungkin disiplin',
      'Raka wajib disiplin',
      'Raka bukan polisi',
      'Semua disiplin polisi',
      'Raka bebas aturan',
    ],
    answer: 1,
    explanation: 'Kesimpulan mengikuti kedua premis.',
  ),
  AkpolCatQuestion(
    number: 15,
    category: 'TPA Logika',
    question: 'Jika hari ini Selasa, 17 hari lagi adalah ...',
    options: ['Kamis', 'Jumat', 'Sabtu', 'Minggu', 'Senin'],
    answer: 1,
    explanation: '17 mod 7 = 3; Selasa + 3 = Jumat.',
  ),
  AkpolCatQuestion(
    number: 16,
    category: 'TPA Logika',
    question: 'Deret 1, 4, 9, 16, 25, ...',
    options: ['30', '32', '36', '40', '49'],
    answer: 2,
    explanation: 'Deret kuadrat: 1²,2²,3²,...; berikutnya 6²=36.',
  ),
  AkpolCatQuestion(
    number: 17,
    category: 'TPA Logika',
    question: 'Jika semua A adalah B dan sebagian B adalah C, maka ...',
    options: [
      'semua A pasti C',
      'sebagian A pasti C',
      'A tidak mungkin B',
      'belum dapat dipastikan hubungan A dan C',
      'semua C adalah A',
    ],
    answer: 3,
    explanation: 'Premis belum cukup untuk memastikan hubungan A dan C.',
  ),
  AkpolCatQuestion(
    number: 18,
    category: 'TPA Logika',
    question:
        'Bila hujan maka jalan basah. Jalan tidak basah. Kesimpulan logis ...',
    options: [
      'pasti hujan',
      'tidak hujan',
      'hujan deras',
      'jalan rusak',
      'tidak dapat menyimpulkan apa pun',
    ],
    answer: 1,
    explanation: 'Dengan pola implikasi, tidak basah berarti kondisi hujan tidak terjadi.',
  ),
  AkpolCatQuestion(
    number: 19,
    category: 'TPA Logika',
    question: 'Urutan: 2, 3, 5, 8, 12, ...',
    options: ['15', '16', '17', '18', '20'],
    answer: 2,
    explanation: 'Selisih 1,2,3,4; berikutnya +5 = 17.',
  ),
  AkpolCatQuestion(
    number: 20,
    category: 'TPA Logika',
    question: 'Andi lebih tinggi dari Budi. Cici lebih pendek dari Budi. Yang paling tinggi adalah ...',
    options: ['Andi', 'Budi', 'Cici', 'Andi dan Cici', 'tidak dapat diketahui'],
    answer: 0,
    explanation: 'Andi lebih tinggi dari Budi dan Cici.',
  ),
  AkpolCatQuestion(
    number: 21,
    category: 'TPA Analitis',
    question: 'Dalam kelas, 30 siswa suka matematika, 20 suka bahasa, dan 10 suka keduanya. Jumlah yang suka minimal salah satu ...',
    options: ['30', '40', '50', '60', '70'],
    answer: 1,
    explanation: '30+20-10 = 40.',
  ),
  AkpolCatQuestion(
    number: 22,
    category: 'TPA Analitis',
    question: 'Jika 4 pekerja menyelesaikan tugas dalam 6 hari, dengan kecepatan sama 8 pekerja memerlukan ...',
    options: ['2 hari', '3 hari', '4 hari', '6 hari', '12 hari'],
    answer: 1,
    explanation: 'Beban kerja 24 pekerja-hari; 24/8=3 hari.',
  ),
  AkpolCatQuestion(
    number: 23,
    category: 'TPA Analitis',
    question: 'Pukul 08.15 ditambah 2 jam 45 menit menjadi ...',
    options: ['10.30', '10.45', '11.00', '11.15', '11.30'],
    answer: 2,
    explanation: '08.15 + 2.45 = 11.00.',
  ),
  AkpolCatQuestion(
    number: 24,
    category: 'TPA Analitis',
    question: 'Sebuah kotak berisi 3 bola merah dan 2 biru. Peluang mengambil bola merah ...',
    options: ['1/5', '2/5', '3/5', '4/5', '1'],
    answer: 2,
    explanation: 'Ada 3 merah dari total 5 bola.',
  ),
  AkpolCatQuestion(
    number: 25,
    category: 'TPA Analitis',
    question: 'Jika x:y=4:5 dan y:z=10:3, maka x:z ...',
    options: ['4:3', '5:3', '8:3', '8:5', '10:3'],
    answer: 2,
    explanation: 'Samakan y: x:y=8:10; y:z=10:3, jadi x:z=8:3.',
  ),
  AkpolCatQuestion(
    number: 26,
    category: 'Bahasa Inggris',
    question: 'Choose the correct sentence.',
    options: [
      'She go to work.',
      'She goes to work.',
      'She going to work.',
      'She gone to work.',
      'She go works.',
    ],
    answer: 1,
    explanation: 'She memakai goes pada simple present.',
  ),
  AkpolCatQuestion(
    number: 27,
    category: 'Bahasa Inggris',
    question: 'The synonym of “rapid” is ...',
    options: ['slow', 'quick', 'weak', 'late', 'quiet'],
    answer: 1,
    explanation: 'Rapid berarti cepat.',
  ),
  AkpolCatQuestion(
    number: 28,
    category: 'Bahasa Inggris',
    question: 'The opposite of “increase” is ...',
    options: ['improve', 'reduce', 'expand', 'develop', 'raise'],
    answer: 1,
    explanation: 'Increase berarti meningkat; lawannya reduce.',
  ),
  AkpolCatQuestion(
    number: 29,
    category: 'Bahasa Inggris',
    question: 'The officers ... ready for duty.',
    options: ['is', 'am', 'are', 'be', 'was'],
    answer: 2,
    explanation: 'Officers jamak, memakai are.',
  ),
  AkpolCatQuestion(
    number: 30,
    category: 'Bahasa Inggris',
    question: 'I ... my assignment yesterday.',
    options: ['finish', 'finishes', 'finished', 'finishing', 'have finish'],
    answer: 2,
    explanation: 'Yesterday menandakan simple past: finished.',
  ),
  AkpolCatQuestion(
    number: 31,
    category: 'Bahasa Inggris',
    question: 'The report ... by the team last week.',
    options: ['writes', 'wrote', 'was written', 'is writing', 'write'],
    answer: 2,
    explanation: 'Passive past: was written.',
  ),
  AkpolCatQuestion(
    number: 32,
    category: 'Bahasa Inggris',
    question: 'If you study hard, you ... pass the test.',
    options: ['will', 'would', 'were', 'has', 'had'],
    answer: 0,
    explanation: 'First conditional memakai will.',
  ),
  AkpolCatQuestion(
    number: 33,
    category: 'Bahasa Inggris',
    question: 'The word “integrity” means ...',
    options: [
      'honesty and strong moral principles',
      'physical strength',
      'quick movement',
      'official rank',
      'public speech',
    ],
    answer: 0,
    explanation: 'Integrity berarti kejujuran dan prinsip moral yang kuat.',
  ),
  AkpolCatQuestion(
    number: 34,
    category: 'Bahasa Inggris',
    question: 'He is interested ... joining the program.',
    options: ['at', 'on', 'in', 'for', 'to'],
    answer: 2,
    explanation: 'Ungkapan yang benar: interested in.',
  ),
  AkpolCatQuestion(
    number: 35,
    category: 'Bahasa Inggris',
    question: 'The meeting starts ... Monday morning.',
    options: ['at', 'in', 'on', 'by', 'from'],
    answer: 2,
    explanation: 'Hari menggunakan on.',
  ),
  AkpolCatQuestion(
    number: 36,
    category: 'Bahasa Inggris',
    question: '“Although” expresses ...',
    options: ['contrast', 'cause', 'place', 'purpose', 'sequence'],
    answer: 0,
    explanation: 'Although menunjukkan pertentangan.',
  ),
  AkpolCatQuestion(
    number: 37,
    category: 'Bahasa Inggris',
    question: 'Choose the correct question.',
    options: [
      'Where you live?',
      'Where do you live?',
      'Where does you live?',
      'Where are you live?',
      'Where live you?',
    ],
    answer: 1,
    explanation: 'Pertanyaan simple present dengan you memakai do.',
  ),
  AkpolCatQuestion(
    number: 38,
    category: 'Bahasa Inggris',
    question: 'The plural form of “analysis” is ...',
    options: ['analysises', 'analysis', 'analyses', 'analysies', 'analytic'],
    answer: 2,
    explanation: 'Bentuk jamak analysis adalah analyses.',
  ),
  AkpolCatQuestion(
    number: 39,
    category: 'Bahasa Inggris',
    question: 'The commander gave ... order.',
    options: ['a', 'an', 'thee', 'some', 'many'],
    answer: 0,
    explanation: 'Order tunggal yang belum spesifik memakai a.',
  ),
  AkpolCatQuestion(
    number: 40,
    category: 'Bahasa Inggris',
    question: '“Must” expresses ...',
    options: [
      'ability',
      'obligation',
      'permission',
      'possibility only',
      'past habit',
    ],
    answer: 1,
    explanation: 'Must menyatakan kewajiban.',
  ),
  AkpolCatQuestion(
    number: 41,
    category: 'Bahasa Inggris',
    question: 'The trainees have ... the exercise.',
    options: ['complete', 'completed', 'completing', 'completes', 'completion'],
    answer: 1,
    explanation: 'Present perfect: have + past participle.',
  ),
  AkpolCatQuestion(
    number: 42,
    category: 'Bahasa Inggris',
    question: '“Reliable” means ...',
    options: [
      'difficult to find',
      'able to be trusted',
      'very expensive',
      'easy to break',
      'always late',
    ],
    answer: 1,
    explanation: 'Reliable berarti dapat dipercaya.',
  ),
  AkpolCatQuestion(
    number: 43,
    category: 'Bahasa Inggris',
    question: 'Neither the captain nor the soldiers ... absent.',
    options: ['is', 'am', 'are', 'was', 'be'],
    answer: 2,
    explanation: 'Kata kerja mengikuti subjek terdekat, soldiers: are.',
  ),
  AkpolCatQuestion(
    number: 44,
    category: 'Bahasa Inggris',
    question: 'The word “confidential” means ...',
    options: [
      'open to everyone',
      'private and restricted',
      'very old',
      'uncertain',
      'temporary',
    ],
    answer: 1,
    explanation: 'Confidential berarti rahasia/terbatas.',
  ),
  AkpolCatQuestion(
    number: 45,
    category: 'Bahasa Inggris',
    question: 'We should verify information ... sharing it.',
    options: ['before', 'unless', 'although', 'because of', 'during'],
    answer: 0,
    explanation: 'Verify before sharing.',
  ),
  AkpolCatQuestion(
    number: 46,
    category: 'Bahasa Inggris',
    question:
        'Choose the best translation: “Ia bertanggung jawab atas laporan itu.”',
    options: [
      'He is responsible for the report.',
      'He is responsibility the report.',
      'He responsible at report.',
      'He was respond the report.',
      'He has responsible of report.',
    ],
    answer: 0,
    explanation: 'Responsible for berarti bertanggung jawab atas.',
  ),
  AkpolCatQuestion(
    number: 47,
    category: 'Bahasa Inggris',
    question: 'The passive form of “People use this system” is ...',
    options: [
      'This system uses people.',
      'This system is used by people.',
      'People are used by system.',
      'This system used people.',
      'This system using people.',
    ],
    answer: 1,
    explanation: 'Passive present: is used by.',
  ),
  AkpolCatQuestion(
    number: 48,
    category: 'Bahasa Inggris',
    question: '“Despite the rain, they continued training.” Despite means ...',
    options: ['because of', 'in spite of', 'before', 'after', 'instead of'],
    answer: 1,
    explanation: 'Despite berarti meskipun/walaupun.',
  ),
  AkpolCatQuestion(
    number: 49,
    category: 'Bahasa Inggris',
    question: 'The correct comparative form is ...',
    options: ['more fast', 'faster', 'fastest than', 'fastly', 'most faster'],
    answer: 1,
    explanation: 'Comparative fast adalah faster.',
  ),
  AkpolCatQuestion(
    number: 50,
    category: 'Bahasa Inggris',
    question: 'The officer asked me ... I was ready.',
    options: ['what', 'whether', 'where', 'who', 'which'],
    answer: 1,
    explanation: 'Whether berarti apakah dalam kalimat tidak langsung.',
  ),
];
