// ignore_for_file: constant_identifier_names

/// Bank soal TIU prediksi sekolah kedinasan dari dokumen TB XI.
class KedinasanTiuQuestion {
  final int number;
  final String question;
  final List<String> options;
  final int answer;
  final String explanation;

  const KedinasanTiuQuestion({
    required this.number,
    required this.question,
    required this.options,
    required this.answer,
    required this.explanation,
  });
}

const PoltekipTiuQuestions = <KedinasanTiuQuestion>[
  KedinasanTiuQuestion(
    number: 1,
    question: 'KREDIBEL memiliki makna yang paling dekat dengan ...',
    options: [
      'dapat dipercaya',
      'mudah berubah',
      'bersifat rahasia',
      'sangat terkenal',
      'sulit dipahami',
    ],
    answer: 0,
    explanation: '1. (A) Kredibel berarti dapat dipercaya atau meyakinkan.',
  ),
  KedinasanTiuQuestion(
    number: 2,
    question: 'Dokter : Rumah sakit = Hakim : ...',
    options: [
      'kantor pos',
      'pengadilan',
      'perpustakaan',
      'laboratorium',
      'sekolah',
    ],
    answer: 1,
    explanation:
        '2. (B) Dokter bekerja di rumah sakit; hakim bekerja di pengadilan.',
  ),
  KedinasanTiuQuestion(
    number: 3,
    question: 'Lawan kata ABSAH adalah ...',
    options: ['resmi', 'sahih', 'batal', 'legal', 'valid'],
    answer: 2,
    explanation: '3. (C) Abash berarti sah; lawannya adalah batal/tidak sah.',
  ),
  KedinasanTiuQuestion(
    number: 4,
    question: 'Manakah yang berbeda kelompok?',
    options: ['jujur', 'amanah', 'integritas', 'transparan', 'impulsif'],
    answer: 4,
    explanation: '4. (E) Empat pilihan pertama berkaitan dengan nilai integritas; impulsif adalah kecenderungan bertindak tanpa pertimbangan.',
  ),
  KedinasanTiuQuestion(
    number: 5,
    question: 'Arsip : Dokumen = Herbarium : ...',
    options: ['batuan', 'tumbuhan', 'hewan', 'peta', 'lukisan'],
    answer: 1,
    explanation: '5. (B) Arsip menyimpan dokumen; herbarium menyimpan koleksi tumbuhan yang diawetkan.',
  ),
  KedinasanTiuQuestion(
    number: 6,
    question: 'Jika 3x - 7 = 2x + 5, nilai x adalah ...',
    options: ['2', '5', '7', '12', '14'],
    answer: 3,
    explanation:
        '6. (D) Kurangi 2x dari kedua ruas: x - 7 = 5, sehingga x = 12.',
  ),
  KedinasanTiuQuestion(
    number: 7,
    question: 'Nilai dari 3/4 + 5/8 - 1/2 adalah ...',
    options: ['1/8', '3/8', '5/8', '7/8', '9/8'],
    answer: 3,
    explanation: '7. Sumber dan catatan penyusunan',
  ),
  KedinasanTiuQuestion(
    number: 8,
    question: 'Harga sebuah buku Rp80.000 didiskon 15%. Harga setelah diskon adalah ...',
    options: ['Rp64.000', 'Rp66.000', 'Rp68.000', 'Rp70.000', 'Rp72.000'],
    answer: 2,
    explanation: '8. (C) Diskon = 15% x 80.000 = 12.000; harga akhir = 68.000.',
  ),
  KedinasanTiuQuestion(
    number: 9,
    question: 'Perbandingan jumlah petugas A dan B adalah 3:5. Jika totalnya 64 orang, jumlah petugas B adalah ...',
    options: ['24', '32', '36', '40', '48'],
    answer: 3,
    explanation:
        '9. (D) Total bagian 8; satu bagian 8. Petugas B = 5 x 8 = 40.',
  ),
  KedinasanTiuQuestion(
    number: 10,
    question: 'Rata-rata 5 nilai adalah 72. Setelah ditambah satu nilai, rata-ratanya menjadi 75. Nilai tambahan itu adalah ...',
    options: ['80', '85', '88', '90', '95'],
    answer: 3,
    explanation: '10. (D) Jumlah awal 360, jumlah baru 450. Selisihnya 90.',
  ),
  KedinasanTiuQuestion(
    number: 11,
    question: 'Sebuah kendaraan menempuh 180 km dalam 3 jam. Dengan kecepatan sama, jarak dalam 45 menit adalah ...',
    options: ['30 km', '40 km', '45 km', '50 km', '60 km'],
    answer: 2,
    explanation:
        '11. (C) Kecepatan 60 km/jam; 45 menit = 0,75 jam; jarak = 45 km.',
  ),
  KedinasanTiuQuestion(
    number: 12,
    question: 'Larutan 20% sebanyak 2 liter dicampur dengan larutan 50% sebanyak 3 liter. Konsentrasi campuran adalah ...',
    options: ['32%', '35%', '36%', '38%', '40%'],
    answer: 3,
    explanation: '12. (D) Zat terlarut = 0,4 + 1,5 = 1,9 liter; total 5 liter; konsentrasi 38%.',
  ),
  KedinasanTiuQuestion(
    number: 13,
    question: 'Sebuah barang dibeli Rp250.000 dan dijual dengan untung 12%. Harga jualnya adalah ...',
    options: ['Rp270.000', 'Rp275.000', 'Rp280.000', 'Rp285.000', 'Rp290.000'],
    answer: 2,
    explanation: '13. (C) Untung 12% x 250.000 = 30.000; harga jual 280.000.',
  ),
  KedinasanTiuQuestion(
    number: 14,
    question: 'A menyelesaikan pekerjaan dalam 12 hari, B dalam 18 hari. Jika bekerja bersama, pekerjaan selesai dalam ...',
    options: ['6 hari', '7 1/5 hari', '8 hari', '9 hari', '10 hari'],
    answer: 1,
    explanation:
        '14. (B) Laju bersama 1/12 + 1/18 = 5/36; waktu = 36/5 = 7 1/5 hari.',
  ),
  KedinasanTiuQuestion(
    number: 15,
    question: 'Persegi panjang memiliki panjang 14 cm dan lebar 9 cm. Kelilingnya adalah ...',
    options: ['36 cm', '42 cm', '46 cm', '48 cm', '52 cm'],
    answer: 2,
    explanation: '15. (C) Keliling = 2(14+9) = 46 cm.',
  ),
  KedinasanTiuQuestion(
    number: 16,
    question: 'Jika a:b = 4:7 dan a+b = 55, maka b-a adalah ...',
    options: ['10', '12', '15', '18', '20'],
    answer: 2,
    explanation:
        '16. (C) Total bagian 11, satu bagian 5; a=20, b=35; selisih 15.',
  ),
  KedinasanTiuQuestion(
    number: 17,
    question: 'Dari 5 calon dipilih ketua dan sekretaris yang berbeda. Banyak susunan yang mungkin adalah ...',
    options: ['10', '15', '20', '25', '30'],
    answer: 2,
    explanation: '17. (C) Pilihan ketua 5 dan sekretaris 4, jadi 5 x 4 = 20.',
  ),
  KedinasanTiuQuestion(
    number: 18,
    question: '2, 5, 11, 23, 47, ...',
    options: ['71', '83', '91', '95', '97'],
    answer: 3,
    explanation:
        '18. (D) Setiap suku dikali 2 lalu ditambah 1: 47 x 2 + 1 = 95.',
  ),
  KedinasanTiuQuestion(
    number: 19,
    question: '4, 9, 19, 39, 79, ...',
    options: ['119', '139', '149', '159', '169'],
    answer: 3,
    explanation:
        '19. (D) Setiap suku dikali 2 lalu ditambah 1: 79 x 2 + 1 = 159.',
  ),
  KedinasanTiuQuestion(
    number: 20,
    question: '81, 27, 9, 3, ...',
    options: ['0', '1/3', '1', '2', '6'],
    answer: 2,
    explanation: '20. (C) Setiap suku dibagi 3; suku berikutnya 3/3 = 1.',
  ),
  KedinasanTiuQuestion(
    number: 21,
    question: 'B, E, I, N, ... huruf berikutnya adalah ...',
    options: ['R', 'S', 'T', 'U', 'V'],
    answer: 2,
    explanation: '21. (C) Posisi huruf bertambah 3, 4, 5; berikutnya tambah 6: N(14)+6=T(20).',
  ),
  KedinasanTiuQuestion(
    number: 22,
    question: 'Semua petugas disiplin mematuhi jadwal. Sebagian peserta adalah petugas disiplin. Kesimpulan yang pasti adalah ...',
    options: [
      'Semua peserta mematuhi jadwal',
      'Sebagian peserta mematuhi jadwal',
      'Tidak ada peserta mematuhi jadwal',
      'Semua yang mematuhi jadwal adalah peserta',
      'Sebagian peserta tidak disiplin',
    ],
    answer: 1,
    explanation: '22. (B) Sebagian peserta termasuk petugas disiplin, dan semua petugas disiplin mematuhi jadwal.',
  ),
  KedinasanTiuQuestion(
    number: 23,
    question: 'Semua X adalah Y. Tidak ada Y yang Z. Kesimpulan yang benar ...',
    options: [
      'Semua Z adalah X',
      'Sebagian X adalah Z',
      'Tidak ada X yang Z',
      'Semua Y adalah X',
      'X dan Z selalu sama',
    ],
    answer: 2,
    explanation: '23. (C) Jika X berada di dalam Y dan Y tidak beririsan dengan Z, X juga tidak beririsan dengan Z.',
  ),
  KedinasanTiuQuestion(
    number: 24,
    question: 'Jika berkas lengkap, maka permohonan diproses. Permohonan R tidak diproses. Kesimpulan yang sah adalah ...',
    options: [
      'Berkas R lengkap',
      'Berkas R tidak lengkap',
      'R pasti ditolak',
      'Semua permohonan ditolak',
      'Berkas R hilang',
    ],
    answer: 1,
    explanation: '24. (B) Modus tollens: jika lengkap maka diproses; tidak diproses berarti tidak lengkap, dalam model logika soal.',
  ),
  KedinasanTiuQuestion(
    number: 25,
    question: 'Lima orang P, Q, R, S, T berdiri berurutan. P di kiri Q, R di kanan Q, dan S paling kanan. Siapa yang pasti bukan posisi pertama?',
    options: ['P', 'Q', 'R', 'S', 'T'],
    answer: 1,
    explanation: '25. (B) Q memiliki P di sebelah kirinya, sehingga Q tidak mungkin berada di posisi pertama.',
  ),
  KedinasanTiuQuestion(
    number: 26,
    question: 'Dina lebih tinggi daripada Eko. Fajar lebih pendek daripada Eko. Gita lebih tinggi daripada Dina. Urutan dari tertinggi ke terpendek adalah ...',
    options: [
      'Gita-Dina-Eko-Fajar',
      'Dina-Gita-Eko-Fajar',
      'Gita-Eko-Dina-Fajar',
      'Fajar-Eko-Dina-Gita',
      'Eko-Dina-Gita-Fajar',
    ],
    answer: 0,
    explanation: '26. (A) Relasi tinggi: Gita > Dina > Eko > Fajar.',
  ),
  KedinasanTiuQuestion(
    number: 27,
    question: 'Jika rapat dimulai tepat waktu, maka notulen selesai siang. Notulen belum selesai siang. Kesimpulannya ...',
    options: [
      'Rapat pasti dibatalkan',
      'Rapat dimulai tepat waktu',
      'Rapat tidak dimulai tepat waktu',
      'Notulen pasti hilang',
      'Tidak ada hubungan',
    ],
    answer: 2,
    explanation: '27. (C) Dengan pola implikasi, tidak selesainya akibat meniadakan syarat awal.',
  ),
  KedinasanTiuQuestion(
    number: 28,
    question: 'Dalam kelompok 40 orang, 25 menyukai A, 18 menyukai B, dan 10 menyukai keduanya. Jumlah yang menyukai minimal salah satu adalah ...',
    options: ['23', '30', '33', '35', '43'],
    answer: 2,
    explanation: '28. (C) Gabungan = 25 + 18 - 10 = 33.',
  ),
  KedinasanTiuQuestion(
    number: 29,
    question: 'Dalam antrean, Raka berada di urutan ke-8 dari depan dan ke-13 dari belakang. Jumlah orang dalam antrean adalah ...',
    options: ['19', '20', '21', '22', '23'],
    answer: 1,
    explanation: '29. (B) Jumlah = 8 + 13 - 1 = 20.',
  ),
  KedinasanTiuQuestion(
    number: 30,
    question: 'Tiga kegiatan A, B, C dijadwalkan Senin, Selasa, Rabu, satu per hari. A bukan Senin, B setelah C. Jadwal yang mungkin adalah ...',
    options: [
      'A-Senin, B-Selasa, C-Rabu',
      'C-Senin, A-Selasa, B-Rabu',
      'B-Senin, C-Selasa, A-Rabu',
      'C-Rabu, B-Selasa, A-Senin',
      'A-Rabu, C-Selasa, B-Senin',
    ],
    answer: 1,
    explanation:
        '30. (B) Hanya pilihan B memenuhi A bukan Senin dan B setelah C.',
  ),
  KedinasanTiuQuestion(
    number: 31,
    question: 'Jika semua narapidana binaan mengikuti program, dan sebagian peserta program mengikuti pelatihan kerja, maka ...',
    options: [
      'Semua narapidana mengikuti pelatihan kerja',
      'Sebagian peserta program mengikuti pelatihan kerja',
      'Tidak ada narapidana mengikuti program',
      'Semua peserta pelatihan adalah narapidana',
      'Program tidak wajib',
    ],
    answer: 1,
    explanation: '31. (B) Pernyataan kedua langsung menyatakan sebagian peserta program mengikuti pelatihan kerja.',
  ),
  KedinasanTiuQuestion(
    number: 32,
    question:
        'Negasi dari pernyataan “Semua laporan telah diperiksa” adalah ...',
    options: [
      'Tidak semua laporan telah diperiksa',
      'Semua laporan belum diperiksa',
      'Tidak ada laporan',
      'Sebagian laporan pasti rusak',
      'Laporan diperiksa ulang',
    ],
    answer: 0,
    explanation: '32. (A) Negasi “semua” adalah “tidak semua”, artinya ada setidaknya satu yang belum diperiksa.',
  ),
  KedinasanTiuQuestion(
    number: 33,
    question: 'Jika KODE ditulis 11-15-4-5 berdasarkan posisi huruf, maka DATA ditulis ...',
    options: ['4-1-20-1', '4-2-20-1', '5-1-20-1', '4-1-19-1', '3-1-20-1'],
    answer: 0,
    explanation: '33. (A) D=4, A=1, T=20, A=1.',
  ),
  KedinasanTiuQuestion(
    number: 34,
    question: 'Sebuah bilangan jika dikali 4 lalu dikurangi 6 menghasilkan 30. Bilangan itu adalah ...',
    options: ['6', '7', '8', '9', '10'],
    answer: 3,
    explanation: '34. (D) 4x - 6 = 30; 4x=36; x=9.',
  ),
  KedinasanTiuQuestion(
    number: 35,
    question: 'Dari 50 berkas, 32 berkas memiliki tanda tangan dan 28 memiliki cap. Jika 18 memiliki keduanya, jumlah berkas yang tidak memiliki tanda tangan maupun cap adalah ...',
    options: ['4', '6', '8', '10', '12'],
    answer: 2,
    explanation: '35. (C) Gabungan = 32 + 28 - 18 = 42; yang tidak termasuk = 50 - 42 = 8.',
  ),
];

const PoltekimTiuQuestions = <KedinasanTiuQuestion>[
  KedinasanTiuQuestion(
    number: 1,
    question: 'Sinonim: INHEREN berarti ....',
    options: ['sementara', 'melekat', 'berlawanan', 'tambahan', 'terbuka'],
    answer: 1,
    explanation: '1. Jawaban B — Inheren berarti melekat atau menjadi bagian yang tidak terpisahkan dari sesuatu.',
  ),
  KedinasanTiuQuestion(
    number: 2,
    question: 'Antonim: KONVERGEN berlawanan makna dengan ....',
    options: ['memusat', 'menyatu', 'divergen', 'berurutan', 'searah'],
    answer: 2,
    explanation: '2. Jawaban C — Konvergen berarti menuju satu titik; lawannya adalah divergen, yaitu menyebar atau menjauh.',
  ),
  KedinasanTiuQuestion(
    number: 3,
    question: 'Analogi: KOMPAS : ARAH = TERMOMETER : ....',
    options: ['tekanan', 'suhu', 'kecepatan', 'jarak', 'waktu'],
    answer: 1,
    explanation: '3. Jawaban B — Kompas digunakan untuk mengukur/menunjukkan arah, sedangkan termometer menunjukkan suhu.',
  ),
  KedinasanTiuQuestion(
    number: 4,
    question: 'Kata yang paling tepat melengkapi kalimat berikut: Petugas harus bersikap .... ketika memeriksa dokumen agar tidak memihak.',
    options: ['parsial', 'objektif', 'sporadis', 'impulsif', 'temporer'],
    answer: 1,
    explanation:
        '4. Jawaban B — Objektif berarti berdasarkan fakta dan tidak memihak.',
  ),
  KedinasanTiuQuestion(
    number: 5,
    question: 'Semua taruna disiplin. Sebagian peserta seleksi adalah taruna. Simpulan yang tepat adalah ....',
    options: [
      'Semua peserta seleksi disiplin',
      'Sebagian peserta seleksi disiplin',
      'Tidak ada peserta seleksi disiplin',
      'Semua yang disiplin adalah taruna',
      'Sebagian taruna tidak disiplin',
    ],
    answer: 1,
    explanation: '5. Jawaban B — Sebagian peserta merupakan taruna, sedangkan semua taruna disiplin; maka sebagian peserta disiplin.',
  ),
  KedinasanTiuQuestion(
    number: 6,
    question: 'Bacalah kalimat: “Sistem antrean digital mengurangi penumpukan pemohon karena waktu layanan dapat dipantau.” Gagasan utamanya adalah ....',
    options: [
      'Pemohon selalu terlambat',
      'Antrean digital mempercepat dan menata layanan',
      'Waktu layanan tidak dapat dipantau',
      'Sistem digital menambah penumpukan',
      'Semua layanan harus manual',
    ],
    answer: 1,
    explanation: '6. Jawaban B — Kalimat menjelaskan manfaat antrean digital dalam mengurangi penumpukan dan memantau layanan.',
  ),
  KedinasanTiuQuestion(
    number: 7,
    question: 'Jika semua A adalah B dan tidak ada B yang C, hubungan yang benar adalah ....',
    options: [
      'Semua A adalah C',
      'Sebagian A adalah C',
      'Tidak ada A yang C',
      'Semua C adalah A',
      'A dan C pasti sama',
    ],
    answer: 2,
    explanation: '7. Sumber acuan publik',
  ),
  KedinasanTiuQuestion(
    number: 8,
    question: 'Kata “akuntabel” paling dekat maknanya dengan ....',
    options: [
      'dapat dipertanggungjawabkan',
      'mudah berubah',
      'bersifat rahasia',
      'tidak terukur',
      'dilakukan spontan',
    ],
    answer: 0,
    explanation: '8. Jawaban A — Akuntabel berarti dapat dipertanggungjawabkan, terutama atas keputusan dan penggunaan sumber daya.',
  ),
  KedinasanTiuQuestion(
    number: 9,
    question: 'Jika 3x + 7 = 28, nilai x adalah ....',
    options: ['5', '6', '7', '8', '9'],
    answer: 2,
    explanation: '9. Jawaban C — 3x = 21 sehingga x = 7.',
  ),
  KedinasanTiuQuestion(
    number: 10,
    question: 'Perbandingan jumlah buku A dan B adalah 3 : 5. Jika totalnya 64 buku, jumlah buku B adalah ....',
    options: ['24', '32', '36', '40', '48'],
    answer: 3,
    explanation: '10. Jawaban D — Total bagian 8; satu bagian 64/8 = 8. Buku B = 5 x 8 = 40.',
  ),
  KedinasanTiuQuestion(
    number: 11,
    question: 'Sebuah nilai naik 20% dari 250, lalu turun 10%. Nilai akhirnya adalah ....',
    options: ['250', '260', '265', '270', '275'],
    answer: 3,
    explanation: '11. Jawaban D — Naik menjadi 300, kemudian turun 10% dari 300 yaitu 30; hasilnya 270.',
  ),
  KedinasanTiuQuestion(
    number: 12,
    question: 'Rata-rata 5 bilangan adalah 18. Jika empat bilangan pertama berjumlah 64, bilangan kelima adalah ....',
    options: ['18', '20', '24', '26', '28'],
    answer: 3,
    explanation: '12. Jawaban D — Jumlah seluruh bilangan = 5 x 18 = 90. Bilangan kelima = 90 - 64 = 26.',
  ),
  KedinasanTiuQuestion(
    number: 13,
    question: 'Sebuah pekerjaan selesai 12 hari oleh 4 orang dengan produktivitas sama. Jika dikerjakan 6 orang, pekerjaan selesai dalam ....',
    options: ['6 hari', '8 hari', '9 hari', '10 hari', '18 hari'],
    answer: 1,
    explanation: '13. Jawaban B — Beban kerja = 4 x 12 = 48 orang-hari. Dengan 6 orang, waktu = 48/6 = 8 hari.',
  ),
  KedinasanTiuQuestion(
    number: 14,
    question: 'Pola bilangan 4, 9, 19, 39, 79, .... adalah ....',
    options: ['119', '139', '149', '159', '169'],
    answer: 3,
    explanation: '14. Jawaban D — Setiap suku dikali 2 lalu ditambah 1: 79 x 2 + 1 = 159.',
  ),
  KedinasanTiuQuestion(
    number: 15,
    question: 'Pola bilangan 2, 6, 12, 20, 30, .... adalah ....',
    options: ['36', '40', '42', '44', '46'],
    answer: 2,
    explanation: '15. Jawaban C — Selisihnya 4, 6, 8, 10, sehingga selisih berikutnya 12; 30 + 12 = 42.',
  ),
  KedinasanTiuQuestion(
    number: 16,
    question: 'Jika a:b = 4:7 dan b:c = 14:15, maka a:c = ....',
    options: ['4:15', '8:15', '14:15', '8:21', '15:8'],
    answer: 1,
    explanation: '16. Jawaban B — Samakan b: a:b = 8:14 dan b:c = 14:15, sehingga a:c = 8:15.',
  ),
  KedinasanTiuQuestion(
    number: 17,
    question: 'Sebuah kendaraan menempuh 180 km dalam 3 jam. Dengan kecepatan sama, jarak dalam 4,5 jam adalah ....',
    options: ['240 km', '250 km', '260 km', '270 km', '280 km'],
    answer: 3,
    explanation: '17. Jawaban D — Kecepatan = 180/3 = 60 km/jam. Jarak = 60 x 4,5 = 270 km.',
  ),
  KedinasanTiuQuestion(
    number: 18,
    question: 'Luas persegi panjang 216 cm2. Jika panjangnya 18 cm, lebarnya adalah ....',
    options: ['10 cm', '11 cm', '12 cm', '13 cm', '14 cm'],
    answer: 2,
    explanation: '18. Jawaban C — Lebar = luas/panjang = 216/18 = 12 cm.',
  ),
  KedinasanTiuQuestion(
    number: 19,
    question: 'Dalam sebuah kotak terdapat 3 bola merah, 2 biru, dan 5 hijau. Peluang mengambil bola biru adalah ....',
    options: ['1/10', '1/5', '1/4', '1/3', '2/5'],
    answer: 1,
    explanation:
        '19. Jawaban B — Total bola 10; bola biru 2. Peluang = 2/10 = 1/5.',
  ),
  KedinasanTiuQuestion(
    number: 20,
    question:
        'Jika 2/3 dari suatu bilangan adalah 48, bilangan tersebut adalah ....',
    options: ['60', '64', '72', '80', '96'],
    answer: 2,
    explanation: '20. Jawaban C — Bilangan = 48 x 3/2 = 72.',
  ),
  KedinasanTiuQuestion(
    number: 21,
    question: 'Usia ayah 4 kali usia anak. Enam tahun lagi usia ayah menjadi 2,5 kali usia anak. Usia anak sekarang adalah ....',
    options: ['3 tahun', '4 tahun', '5 tahun', '6 tahun', '8 tahun'],
    answer: 3,
    explanation: '21. Jawaban D — Misal anak x dan ayah 4x. 4x+6 = 2,5(x+6), sehingga 1,5x = 9 dan x = 6.',
  ),
  KedinasanTiuQuestion(
    number: 22,
    question: 'Lima orang A, B, C, D, E duduk berderet. A di kiri B, C di kanan D, dan E di antara A dan D. Susunan yang mungkin adalah ....',
    options: ['A-E-D-C-B', 'B-A-E-D-C', 'D-E-A-B-C', 'A-D-E-C-B', 'C-D-E-B-A'],
    answer: 0,
    explanation: '22. Jawaban A — A-E-D-C-B memenuhi A di kiri B, C di kanan D, dan E berada di antara A dan D.',
  ),
  KedinasanTiuQuestion(
    number: 23,
    question: 'Jika hari ini Rabu, 100 hari lagi adalah ....',
    options: ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat'],
    answer: 4,
    explanation:
        '23. Jawaban E — 100 dibagi 7 bersisa 2. Rabu + 2 hari = Jumat.',
  ),
  KedinasanTiuQuestion(
    number: 24,
    question: 'Semua petugas X memakai kartu identitas. Rina tidak memakai kartu identitas. Simpulan yang pasti adalah ....',
    options: [
      'Rina petugas X',
      'Rina bukan petugas X',
      'Semua yang tidak memakai kartu adalah Rina',
      'Rina memakai kartu cadangan',
      'Tidak ada petugas X',
    ],
    answer: 1,
    explanation: '24. Jawaban B — Kontrapositif: jika semua X memakai kartu, orang yang tidak memakai kartu bukan X.',
  ),
  KedinasanTiuQuestion(
    number: 25,
    question: 'Jika pernyataan “Semua dokumen lengkap diproses” benar, negasinya adalah ....',
    options: [
      'Semua dokumen tidak lengkap diproses',
      'Ada dokumen lengkap yang tidak diproses',
      'Tidak ada dokumen yang diproses',
      'Ada dokumen tidak lengkap yang diproses',
      'Semua dokumen diproses',
    ],
    answer: 1,
    explanation: '25. Jawaban B — Negasi “semua A adalah B” adalah “ada A yang bukan B”.',
  ),
  KedinasanTiuQuestion(
    number: 26,
    question: 'P, Q, R, S mengikuti jadwal berurutan. P sebelum Q, R setelah Q, dan S sebelum P. Urutan yang mungkin adalah ....',
    options: ['P-S-Q-R', 'S-P-Q-R', 'Q-P-S-R', 'R-Q-S-P', 'S-R-P-Q'],
    answer: 1,
    explanation: '26. Jawaban B — Urutan S-P-Q-R memenuhi S sebelum P sebelum Q sebelum R.',
  ),
  KedinasanTiuQuestion(
    number: 27,
    question: 'Tiga lampu menyala berkedip dengan pola: lampu 1 tiap 2 detik, lampu 2 tiap 3 detik, lampu 3 tiap 4 detik. Ketiganya menyala bersamaan lagi setelah ....',
    options: ['6 detik', '8 detik', '9 detik', '12 detik', '24 detik'],
    answer: 3,
    explanation:
        '27. Jawaban D — Waktu bersamaan adalah KPK(2,3,4) = 12 detik.',
  ),
  KedinasanTiuQuestion(
    number: 28,
    question: 'Sebuah kode terdiri dari dua huruf berbeda diikuti dua angka berbeda. Jika huruf dipilih dari A, B, C dan angka dari 1, 2, 3, banyak kode yang mungkin adalah ....',
    options: ['18', '24', '36', '54', '81'],
    answer: 2,
    explanation: '28. Jawaban C — Urutan huruf: 3P2 = 6. Urutan angka: 3P2 = 6. Total 6 x 6 = 36.',
  ),
  KedinasanTiuQuestion(
    number: 29,
    question: 'Analogi simbol: △ berubah menjadi ▲ dengan aturan “diisi penuh”. Jika ○ dikenai aturan yang sama, hasilnya adalah ....',
    options: ['□', '●', '◇', '☆', '○'],
    answer: 1,
    explanation: '29. Jawaban B — Aturannya mengubah bentuk garis luar menjadi bentuk terisi; lingkaran menjadi lingkaran penuh.',
  ),
  KedinasanTiuQuestion(
    number: 30,
    question: 'Deret simbol: ○, △, □, ○, △, .... Simbol berikutnya adalah ....',
    options: ['○', '△', '□', '◇', '☆'],
    answer: 2,
    explanation: '30. Jawaban C — Pola berulang tiga simbol: lingkaran, segitiga, persegi.',
  ),
  KedinasanTiuQuestion(
    number: 31,
    question: 'Sebuah panah mengarah ke atas. Diputar 90 derajat searah jarum jam, lalu 90 derajat lagi searah jarum jam. Arah akhirnya adalah ....',
    options: ['atas', 'kanan', 'bawah', 'kiri', 'diagonal'],
    answer: 2,
    explanation: '31. Jawaban C — Dua kali rotasi 90 derajat = 180 derajat; atas menjadi bawah.',
  ),
  KedinasanTiuQuestion(
    number: 32,
    question: 'Urutan bentuk bertambah sisi: segitiga, persegi, segilima, .... Bentuk berikutnya adalah ....',
    options: ['lingkaran', 'segienam', 'segitujuh', 'persegi panjang', 'oval'],
    answer: 1,
    explanation: '32. Jawaban B — Jumlah sisi bertambah satu: 3, 4, 5, lalu 6 sisi yaitu segienam.',
  ),
  KedinasanTiuQuestion(
    number: 33,
    question: 'Sebuah pola terdiri atas 2 titik pada gambar pertama, 5 titik pada kedua, 8 titik pada ketiga. Jumlah titik pada gambar keenam adalah ....',
    options: ['14', '15', '17', '18', '20'],
    answer: 2,
    explanation:
        '33. Jawaban C — Pertambahan tetap 3; suku keenam = 2 + 5 x 3 = 17.',
  ),
  KedinasanTiuQuestion(
    number: 34,
    question: 'Pada matriks, baris pertama berisi 2, 4, 6; baris kedua 3, 6, 9; baris ketiga 4, 8, .... Angka yang tepat adalah ....',
    options: ['10', '11', '12', '14', '16'],
    answer: 2,
    explanation:
        '34. Jawaban C — Setiap baris adalah kelipatan: baris ketiga 4, 8, 12.',
  ),
  KedinasanTiuQuestion(
    number: 35,
    question: 'Sebuah kubus memiliki semua sisi dicat, lalu dipotong menjadi 27 kubus kecil sama besar. Banyak kubus kecil yang memiliki tepat dua sisi bercat adalah ....',
    options: ['4', '8', '12', '16', '24'],
    answer: 2,
    explanation: '35. Jawaban C — Kubus kecil dengan tepat dua sisi bercat berada di tengah setiap rusuk: 12 rusuk x 1 = 12.',
  ),
];

const STMKGTiuQuestions = <KedinasanTiuQuestion>[
  KedinasanTiuQuestion(
    number: 1,
    question: 'Makna kata AKURAT paling dekat dengan ...',
    options: ['cepat', 'rumit', 'cermat', 'umum', 'sementara'],
    answer: 2,
    explanation: '1. C — Akurat berarti tepat atau cermat.',
  ),
  KedinasanTiuQuestion(
    number: 2,
    question: 'Lawan kata AMBIGU adalah ...',
    options: ['samar', 'tegas', 'ganda', 'rancu', 'kabur'],
    answer: 1,
    explanation: '2. B — Ambigu berarti bermakna ganda atau tidak jelas; lawannya tegas/jelas.',
  ),
  KedinasanTiuQuestion(
    number: 3,
    question: 'DOKTER : PASIEN = GURU : ...',
    options: ['sekolah', 'buku', 'murid', 'kelas', 'pelajaran'],
    answer: 2,
    explanation: '3. C — Dokter melayani pasien; guru mengajar murid.',
  ),
  KedinasanTiuQuestion(
    number: 4,
    question: 'Kata yang tidak sekelompok adalah ...',
    options: [
      'barometer',
      'termometer',
      'higrometer',
      'anemometer',
      'mikroskop',
    ],
    answer: 4,
    explanation: '4. E — Empat alat pertama mengukur unsur cuaca; mikroskop digunakan untuk mengamati objek sangat kecil.',
  ),
  KedinasanTiuQuestion(
    number: 5,
    question: 'Semua peserta yang disiplin datang tepat waktu. Raka datang tepat waktu. Simpulan yang tepat adalah ...',
    options: [
      'Raka pasti disiplin',
      'Raka mungkin disiplin, tetapi tidak pasti',
      'Raka pasti tidak disiplin',
      'Tidak ada peserta yang disiplin',
      'Raka tidak datang',
    ],
    answer: 1,
    explanation: '5. B — Pernyataan hanya memberi implikasi disiplin ke tepat waktu, bukan sebaliknya.',
  ),
  KedinasanTiuQuestion(
    number: 6,
    question: 'Kata yang paling tepat untuk melengkapi: Data yang ... membantu peneliti menarik kesimpulan yang dapat dipertanggungjawabkan.',
    options: ['acak', 'valid', 'lambat', 'bias', 'kabur'],
    answer: 1,
    explanation:
        '6. B — Data valid adalah data yang sahih dan dapat dipercaya.',
  ),
  KedinasanTiuQuestion(
    number: 7,
    question: 'Jika semua X adalah Y dan sebagian Y adalah Z, maka ...',
    options: [
      'semua X pasti Z',
      'sebagian X pasti Z',
      'tidak dapat dipastikan hubungan X dan Z',
      'semua Z adalah X',
      'X dan Z pasti sama',
    ],
    answer: 2,
    explanation: '7. C — Informasi tersebut belum cukup untuk memastikan irisan X dan Z.',
  ),
  KedinasanTiuQuestion(
    number: 8,
    question: 'Rapat ditunda karena peringatan cuaca ekstrem. Hubungan kedua klausa tersebut adalah ...',
    options: [
      'perbandingan',
      'sebab-akibat',
      'penambahan',
      'penegasan',
      'syarat',
    ],
    answer: 1,
    explanation: '8. B — Peringatan cuaca ekstrem menjadi sebab rapat ditunda.',
  ),
  KedinasanTiuQuestion(
    number: 9,
    question:
        'Pilih pasangan kata yang hubungannya paling serupa: TERMOMETER : SUHU',
    options: [
      'kompas : arah',
      'jam : jarak',
      'kamera : berat',
      'buku : warna',
      'peta : bunyi',
    ],
    answer: 0,
    explanation:
        '9. A — Termometer mengukur suhu; kompas menunjukkan/mengukur arah.',
  ),
  KedinasanTiuQuestion(
    number: 10,
    question: 'Pernyataan yang paling efektif adalah ...',
    options: [
      'Para peserta-peserta diwajibkan untuk hadir.',
      'Peserta diwajibkan hadir.',
      'Peserta adalah diwajibkan untuk hadir.',
      'Para peserta diwajibkan untuk agar hadir.',
      'Peserta-peserta wajib untuk hadir semuanya.',
    ],
    answer: 1,
    explanation: '10. B — Kalimat B ringkas dan menghindari bentuk jamak serta kata depan yang tidak perlu.',
  ),
  KedinasanTiuQuestion(
    number: 11,
    question: 'Jika “presisi” berarti tingkat ketelitian hasil pengukuran, kata yang berlawanan makna adalah ...',
    options: ['cermat', 'teliti', 'tepat', 'ceroboh', 'rinci'],
    answer: 3,
    explanation: '11. D — Ceroboh berlawanan dengan teliti atau presisi.',
  ),
  KedinasanTiuQuestion(
    number: 12,
    question: 'Pernyataan: “Tidak ada data rahasia yang boleh dibagikan tanpa wewenang.” Jika berkas A dibagikan tanpa wewenang, simpulan logisnya ...',
    options: [
      'A pasti data rahasia',
      'A bukan data rahasia',
      'A melanggar ketentuan bila termasuk data rahasia',
      'semua berkas boleh dibagikan',
      'wewenang tidak diperlukan',
    ],
    answer: 2,
    explanation: '12. C — Larangan berlaku bila objeknya termasuk data rahasia; status A tidak disebutkan secara langsung.',
  ),
  KedinasanTiuQuestion(
    number: 13,
    question: '3, 6, 12, 24, ..., suku berikutnya adalah ...',
    options: ['30', '36', '42', '48', '54'],
    answer: 3,
    explanation: '13. D — Setiap suku dikali 2; 24 × 2 = 48.',
  ),
  KedinasanTiuQuestion(
    number: 14,
    question: '5, 9, 17, 33, ..., suku berikutnya adalah ...',
    options: ['49', '57', '65', '67', '71'],
    answer: 2,
    explanation: '14. C — Pola ×2 − 1: 5→9→17→33, maka 33×2−1=65.',
  ),
  KedinasanTiuQuestion(
    number: 15,
    question: 'Jika 4x − 7 = 21, nilai x adalah ...',
    options: ['5', '6', '7', '8', '9'],
    answer: 2,
    explanation: '15. C — 4x=28 sehingga x=7.',
  ),
  KedinasanTiuQuestion(
    number: 16,
    question: '25% dari 360 adalah ...',
    options: ['72', '80', '90', '100', '120'],
    answer: 2,
    explanation: '16. C — 25% = 1/4; 360/4 = 90.',
  ),
  KedinasanTiuQuestion(
    number: 17,
    question: 'Perbandingan A:B = 3:5. Jika A+B=64, nilai B adalah ...',
    options: ['24', '32', '36', '40', '48'],
    answer: 3,
    explanation: '17. D — Total bagian 8; satu bagian 8; B=5×8=40.',
  ),
  KedinasanTiuQuestion(
    number: 18,
    question: 'Rata-rata 5 bilangan adalah 18. Jika empat bilangan pertama berjumlah 64, bilangan kelima adalah ...',
    options: ['18', '20', '24', '26', '28'],
    answer: 3,
    explanation: '18. D — Jumlah total=5×18=90; bilangan kelima=90−64=26.',
  ),
  KedinasanTiuQuestion(
    number: 19,
    question: 'Sebuah pekerjaan selesai 12 hari oleh 6 orang dengan laju sama. Jika dikerjakan 8 orang, waktunya ...',
    options: ['6 hari', '8 hari', '9 hari', '10 hari', '16 hari'],
    answer: 2,
    explanation: '19. C — Beban kerja=6×12=72 orang-hari; 72/8=9 hari.',
  ),
  KedinasanTiuQuestion(
    number: 20,
    question:
        'Luas persegi panjang dengan panjang 18 cm dan lebar 7 cm adalah ...',
    options: ['25 cm2', '50 cm2', '96 cm2', '126 cm2', '144 cm2'],
    answer: 3,
    explanation: '20. D — Luas=p×l=18×7=126 cm2.',
  ),
  KedinasanTiuQuestion(
    number: 21,
    question: 'Sebuah barang seharga Rp240.000 mendapat diskon 15%. Harga setelah diskon adalah ...',
    options: ['Rp196.000', 'Rp204.000', 'Rp210.000', 'Rp216.000', 'Rp225.000'],
    answer: 1,
    explanation: '21. B — Diskon=36.000; harga akhir=240.000−36.000=204.000.',
  ),
  KedinasanTiuQuestion(
    number: 22,
    question: 'Jika 2/3 dari suatu bilangan adalah 48, bilangan itu adalah ...',
    options: ['64', '72', '81', '96', '108'],
    answer: 1,
    explanation: '22. B — Bilangan=48×3/2=72.',
  ),
  KedinasanTiuQuestion(
    number: 23,
    question: 'Sebuah kendaraan menempuh 180 km dalam 3 jam. Dengan kecepatan sama, jarak dalam 5 jam adalah ...',
    options: ['240 km', '270 km', '300 km', '330 km', '360 km'],
    answer: 2,
    explanation: '23. C — Kecepatan=60 km/jam; 60×5=300 km.',
  ),
  KedinasanTiuQuestion(
    number: 24,
    question: 'Umur Ayah 4 kali umur Budi. Enam tahun lagi umur Ayah menjadi 2 kali umur Budi. Umur Budi sekarang ...',
    options: ['2 tahun', '3 tahun', '4 tahun', '5 tahun', '6 tahun'],
    answer: 1,
    explanation:
        '24. B — Misal Budi=x, Ayah=4x. 4x+6=2(x+6), jadi 2x=6 dan x=3.',
  ),
  KedinasanTiuQuestion(
    number: 25,
    question: 'Semua meteorolog adalah pengamat cuaca. Sebagian pengamat cuaca bekerja di lapangan. Simpulan yang pasti benar ...',
    options: [
      'semua meteorolog bekerja di lapangan',
      'sebagian meteorolog pasti bekerja di lapangan',
      'tidak dapat dipastikan meteorolog bekerja di lapangan',
      'tidak ada meteorolog di lapangan',
      'semua pekerja lapangan meteorolog',
    ],
    answer: 2,
    explanation:
        '25. C — Irisan meteorolog dengan pekerja lapangan tidak dinyatakan.',
  ),
  KedinasanTiuQuestion(
    number: 26,
    question: 'Jika hujan maka jalan basah. Jalan tidak basah. Simpulan yang sah adalah ...',
    options: [
      'pasti hujan',
      'tidak hujan',
      'pasti panas',
      'jalan rusak',
      'tidak dapat disimpulkan',
    ],
    answer: 1,
    explanation:
        '26. B — Modus tollens: jika hujan→basah; tidak basah→tidak hujan.',
  ),
  KedinasanTiuQuestion(
    number: 27,
    question: 'Urutan huruf: A, C, F, J, O, ... Huruf berikutnya adalah ...',
    options: ['R', 'S', 'T', 'U', 'V'],
    answer: 3,
    explanation: '27. D — Lompatan +2,+3,+4,+5; berikutnya +6 dari O = U.',
  ),
  KedinasanTiuQuestion(
    number: 28,
    question: 'Lima orang P, Q, R, S, T duduk berjajar. P di kiri Q, R di kanan Q, S di kiri P, dan T di kanan R. Urutan dari kiri ke kanan adalah ...',
    options: ['P-Q-R-S-T', 'S-P-Q-R-T', 'S-Q-P-R-T', 'T-R-Q-P-S', 'Q-P-S-R-T'],
    answer: 1,
    explanation: '28. B — Kendala S<P<Q<R<T memaksa urutan S-P-Q-R-T.',
  ),
  KedinasanTiuQuestion(
    number: 29,
    question: 'Jika nilai A lebih besar dari B, B lebih besar dari C, dan C lebih besar dari D, maka yang terbesar adalah ...',
    options: ['A', 'B', 'C', 'D', 'tidak dapat ditentukan'],
    answer: 0,
    explanation: '29. A — Urutannya A>B>C>D.',
  ),
  KedinasanTiuQuestion(
    number: 30,
    question: 'Pola: 2, 5, 10, 17, 26, ... angka berikutnya adalah ...',
    options: ['32', '35', '36', '37', '38'],
    answer: 3,
    explanation:
        '30. D — Selisih 3,5,7,9; selisih berikutnya 11, jadi 26+11=37.',
  ),
  KedinasanTiuQuestion(
    number: 31,
    question: 'Semua laporan yang lengkap telah diperiksa. Laporan X belum diperiksa. Simpulan yang valid adalah ...',
    options: [
      'X pasti tidak lengkap',
      'X pasti lengkap',
      'X belum tentu lengkap',
      'semua laporan tidak lengkap',
      'pemeriksaan tidak diperlukan',
    ],
    answer: 0,
    explanation: '31. A — Kontrapositif dari lengkap→diperiksa adalah belum diperiksa→tidak lengkap.',
  ),
  KedinasanTiuQuestion(
    number: 32,
    question: 'Tiga kotak berlabel Merah, Biru, Hijau. Hanya satu berisi hadiah. Petunjuk: hadiah bukan di Merah; hadiah berada di kotak yang bukan Biru. Hadiah berada di ...',
    options: [
      'Merah',
      'Biru',
      'Hijau',
      'Merah atau Biru',
      'tidak dapat ditentukan',
    ],
    answer: 2,
    explanation: '32. C — Bukan Merah dan bukan Biru, sehingga Hijau.',
  ),
  KedinasanTiuQuestion(
    number: 33,
    question: 'Jika sebagian X adalah Y dan semua Y adalah Z, maka ...',
    options: [
      'semua X adalah Z',
      'sebagian X adalah Z',
      'tidak ada X yang Z',
      'semua Z adalah X',
      'X dan Z pasti identik',
    ],
    answer: 1,
    explanation: '33. B — Bagian X yang termasuk Y otomatis termasuk Z.',
  ),
  KedinasanTiuQuestion(
    number: 34,
    question: 'Empat kegiatan K, L, M, N dijadwalkan Senin–Kamis, satu per hari. K sebelum M, L tepat setelah K, dan N bukan Kamis. Jadwal yang mungkin adalah ...',
    options: ['K-L-M-N', 'K-M-L-N', 'L-K-N-M', 'N-K-L-M', 'M-K-L-N'],
    answer: 3,
    explanation:
        '34. D — D memenuhi K sebelum M, L tepat setelah K, dan N bukan Kamis.',
  ),
  KedinasanTiuQuestion(
    number: 35,
    question: 'Jika semua A adalah B, dan tidak ada B yang C, maka hubungan A dan C adalah ...',
    options: [
      'sebagian A adalah C',
      'semua A adalah C',
      'tidak ada A yang C',
      'semua C adalah A',
      'tidak dapat ditentukan',
    ],
    answer: 2,
    explanation: '35. C — A termasuk B, sedangkan B tidak beririsan dengan C; berarti A juga tidak beririsan dengan C.',
  ),
];

const IPDNTiuQuestions = <KedinasanTiuQuestion>[
  KedinasanTiuQuestion(
    number: 1,
    question: 'Kata mitigasi memiliki makna yang paling dekat dengan ...',
    options: [
      'Perluasan',
      'Pengurangan dampak',
      'Penolakan',
      'Pemusatan',
      'Penyatuan',
    ],
    answer: 1,
    explanation: '1. Jawaban B — Mitigasi berarti tindakan untuk mengurangi risiko atau dampak buruk.',
  ),
  KedinasanTiuQuestion(
    number: 2,
    question: 'Lawan kata sporadis adalah ...',
    options: ['Sementara', 'Terpisah', 'Teratur', 'Mendadak', 'Terbatas'],
    answer: 2,
    explanation: '2. Jawaban C — Sporadis berarti terpencar atau tidak teratur; lawannya adalah teratur atau terpola.',
  ),
  KedinasanTiuQuestion(
    number: 3,
    question: 'KOMPAS : ARAH = TERMOMETER : ...',
    options: ['Tekanan', 'Suhu', 'Cuaca', 'Panas', 'Udara'],
    answer: 1,
    explanation: '3. Jawaban B — Kompas digunakan untuk menentukan arah, sedangkan termometer untuk mengukur suhu.',
  ),
  KedinasanTiuQuestion(
    number: 4,
    question: 'DOKTER : PASIEN = GURU : ...',
    options: ['Sekolah', 'Buku', 'Murid', 'Kelas', 'Pelajaran'],
    answer: 2,
    explanation: '4. Jawaban C — Dokter berhubungan langsung dengan pasien; guru berhubungan langsung dengan murid.',
  ),
  KedinasanTiuQuestion(
    number: 5,
    question: 'Semua praja disiplin. Sebagian peserta seleksi adalah praja. Kesimpulan yang tepat adalah ...',
    options: [
      'Semua peserta seleksi disiplin',
      'Sebagian peserta seleksi disiplin',
      'Tidak ada peserta seleksi yang disiplin',
      'Semua orang disiplin adalah praja',
      'Sebagian praja tidak disiplin',
    ],
    answer: 1,
    explanation: '5. Jawaban B — Sebagian peserta adalah praja, sedangkan semua praja disiplin. Jadi sebagian peserta seleksi disiplin.',
  ),
  KedinasanTiuQuestion(
    number: 6,
    question: 'Semua pegawai teliti. Sebagian orang teliti bukan pegawai. Kesimpulan yang benar adalah ...',
    options: [
      'Semua orang teliti adalah pegawai',
      'Sebagian pegawai tidak teliti',
      'Semua pegawai tidak teliti',
      'Sebagian orang teliti bukan pegawai',
      'Tidak ada pegawai yang teliti',
    ],
    answer: 3,
    explanation:
        '6. Jawaban D — Pernyataan kedua sudah langsung menjadi kesimpulan.',
  ),
  KedinasanTiuQuestion(
    number: 7,
    question: 'Urutan dari paling umum ke paling khusus: (1) kendaraan, (2) sepeda, (3) alat transportasi, (4) sepeda gunung.',
    options: ['1–3–2–4', '3–1–2–4', '3–2–1–4', '4–2–1–3', '2–4–1–3'],
    answer: 1,
    explanation: '7. Jawaban B — Alat transportasi lebih umum daripada kendaraan; sepeda termasuk kendaraan; sepeda gunung adalah jenis sepeda.',
  ),
  KedinasanTiuQuestion(
    number: 8,
    question: 'BENIH : TANAMAN = TELUR : ...',
    options: ['Daging', 'Ayam', 'Sarang', 'Bulu', 'Makanan'],
    answer: 1,
    explanation: '8. Jawaban B — Benih dapat berkembang menjadi tanaman; telur dapat berkembang menjadi ayam.',
  ),
  KedinasanTiuQuestion(
    number: 9,
    question: 'Jika hujan turun deras, jalan menjadi licin. Hari ini jalan tidak licin. Kesimpulan paling tepat adalah ...',
    options: [
      'Hari ini pasti tidak hujan',
      'Hujan pasti turun ringan',
      'Hujan deras tidak terjadi hari ini',
      'Jalan pasti kering',
      'Hari ini cuaca cerah',
    ],
    answer: 2,
    explanation: '9. Jawaban C — Kondisi hujan deras yang menyebabkan jalan licin tidak terjadi; tidak berarti pasti tidak hujan sama sekali.',
  ),
  KedinasanTiuQuestion(
    number: 10,
    question: 'Semua peserta yang datang tepat waktu mengikuti pengarahan. Raka tidak mengikuti pengarahan. Kesimpulan yang pasti benar adalah ...',
    options: [
      'Raka pasti terlambat',
      'Raka tidak datang',
      'Raka tidak datang tepat waktu',
      'Raka mengikuti kegiatan lain',
      'Raka tidak lolos seleksi',
    ],
    answer: 2,
    explanation: '10. Jawaban C — Jika datang tepat waktu, peserta mengikuti pengarahan. Raka tidak mengikuti pengarahan, berarti ia tidak datang tepat waktu.',
  ),
  KedinasanTiuQuestion(
    number: 11,
    question: '3, 7, 15, 31, ...',
    options: ['47', '55', '63', '65', '71'],
    answer: 2,
    explanation:
        '11. Jawaban C — Pola: dikali 2 lalu ditambah 1. Jadi 31 × 2 + 1 = 63.',
  ),
  KedinasanTiuQuestion(
    number: 12,
    question: '2, 6, 12, 20, 30, ...',
    options: ['36', '40', '42', '44', '46'],
    answer: 2,
    explanation:
        '12. Jawaban C — Selisihnya 4, 6, 8, 10, lalu 12. Jadi 30 + 12 = 42.',
  ),
  KedinasanTiuQuestion(
    number: 13,
    question: '5, 10, 20, 40, ...',
    options: ['50', '60', '70', '80', '100'],
    answer: 3,
    explanation: '13. Jawaban D — Setiap angka dikali 2.',
  ),
  KedinasanTiuQuestion(
    number: 14,
    question: 'Perbandingan siswa laki-laki dan perempuan adalah 3 : 5. Jika jumlah seluruh siswa 40 orang, jumlah siswa laki-laki adalah ...',
    options: ['12', '15', '18', '20', '25'],
    answer: 1,
    explanation:
        '14. Jawaban B — Jumlah bagian 8; 40 ÷ 8 = 5; laki-laki = 3 × 5 = 15.',
  ),
  KedinasanTiuQuestion(
    number: 15,
    question: 'Harga buku Rp80.000,00 mendapat diskon 15%. Harga setelah diskon adalah ...',
    options: [
      'Rp64.000,00',
      'Rp66.000,00',
      'Rp68.000,00',
      'Rp70.000,00',
      'Rp72.000,00',
    ],
    answer: 2,
    explanation: '15. Jawaban C — Diskon Rp12.000,00; harga akhir Rp80.000,00 – Rp12.000,00 = Rp68.000,00.',
  ),
  KedinasanTiuQuestion(
    number: 16,
    question: 'Barang seharga Rp200.000,00 naik 10%, kemudian turun 10%. Harga akhirnya adalah ...',
    options: [
      'Rp198.000,00',
      'Rp200.000,00',
      'Rp202.000,00',
      'Rp210.000,00',
      'Rp220.000,00',
    ],
    answer: 0,
    explanation: '16. Jawaban A — Setelah naik menjadi Rp220.000,00; turun 10% menjadi Rp198.000,00.',
  ),
  KedinasanTiuQuestion(
    number: 17,
    question: 'Rata-rata lima nilai adalah 76. Empat nilai pertama 70, 75, 80, dan 78. Nilai kelima adalah ...',
    options: ['75', '76', '77', '78', '79'],
    answer: 2,
    explanation: '17. Jawaban C — Total 380; empat nilai berjumlah 303; nilai kelima = 380 – 303 = 77.',
  ),
  KedinasanTiuQuestion(
    number: 18,
    question: 'Kendaraan menempuh 180 km dalam 3 jam. Kecepatan rata-ratanya adalah ...',
    options: ['45 km/jam', '50 km/jam', '55 km/jam', '60 km/jam', '65 km/jam'],
    answer: 3,
    explanation:
        '18. Jawaban D — Kecepatan = jarak ÷ waktu = 180 ÷ 3 = 60 km/jam.',
  ),
  KedinasanTiuQuestion(
    number: 19,
    question: 'A menyelesaikan pekerjaan dalam 12 hari, B dalam 6 hari. Jika bersama, pekerjaan selesai dalam ...',
    options: ['2 hari', '3 hari', '4 hari', '5 hari', '6 hari'],
    answer: 2,
    explanation: '19. Jawaban C — Laju bersama = 1/12 + 1/6 = 1/4 pekerjaan per hari, jadi selesai 4 hari.',
  ),
  KedinasanTiuQuestion(
    number: 20,
    question: 'Umur Ayah tiga kali umur anak. Jumlah umur mereka 48 tahun. Umur anak adalah ...',
    options: ['10 tahun', '12 tahun', '14 tahun', '16 tahun', '18 tahun'],
    answer: 1,
    explanation: '20. Jawaban B — x + 3x = 48, sehingga x = 12.',
  ),
  KedinasanTiuQuestion(
    number: 21,
    question: 'Nilai 3/4 + 2/3 adalah ...',
    options: ['5/7', '7/12', '13/12', '17/12', '19/12'],
    answer: 3,
    explanation: '21. Jawaban D — 3/4 = 9/12 dan 2/3 = 8/12; jumlahnya 17/12.',
  ),
  KedinasanTiuQuestion(
    number: 22,
    question: 'Jika 3x + 7 = 25, nilai x adalah ...',
    options: ['4', '5', '6', '7', '8'],
    answer: 2,
    explanation: '22. Jawaban C — 3x = 18, sehingga x = 6.',
  ),
  KedinasanTiuQuestion(
    number: 23,
    question: 'Dalam kotak ada 3 bola merah dan 2 bola biru. Peluang mengambil bola merah adalah ...',
    options: ['1/5', '2/5', '3/5', '1/2', '2/3'],
    answer: 2,
    explanation: '23. Jawaban C — Jumlah bola 5; bola merah 3; peluang = 3/5.',
  ),
  KedinasanTiuQuestion(
    number: 24,
    question: 'Suatu bilangan jika dibagi 5 bersisa 3. Bilangan yang mungkin adalah ...',
    options: ['21', '22', '23', '24', '25'],
    answer: 2,
    explanation: '24. Jawaban C — 23 ÷ 5 = 4 sisa 3.',
  ),
  KedinasanTiuQuestion(
    number: 25,
    question: 'Dari 40 peserta, 25 menyukai matematika, 20 menyukai bahasa, dan 10 menyukai keduanya. Jumlah yang menyukai minimal salah satu adalah ...',
    options: ['30', '32', '35', '38', '40'],
    answer: 2,
    explanation: '25. Jawaban C — 25 + 20 – 10 = 35.',
  ),
  KedinasanTiuQuestion(
    number: 26,
    question:
        'Deret simbol: ○, △, □, ○, △, □, ○, ... Simbol berikutnya adalah ...',
    options: ['○', '△', '□', '☆', '◇'],
    answer: 1,
    explanation: '26. Jawaban B — Pola berulang: lingkaran, segitiga, persegi.',
  ),
  KedinasanTiuQuestion(
    number: 27,
    question: 'Deret arah: ↑, →, ↓, ←, ↑, ... Simbol berikutnya adalah ...',
    options: ['↑', '→', '↓', '←', '↗'],
    answer: 1,
    explanation: '27. Jawaban B — Arah berputar 90 derajat searah jarum jam.',
  ),
  KedinasanTiuQuestion(
    number: 28,
    question: 'Deret jumlah titik: •, ••, •••, ••••, ... Tahap berikutnya memiliki ...',
    options: ['3 titik', '4 titik', '5 titik', '6 titik', '7 titik'],
    answer: 2,
    explanation: '28. Jawaban C — Jumlah titik bertambah satu setiap tahap.',
  ),
  KedinasanTiuQuestion(
    number: 29,
    question: 'Manakah yang berbeda?',
    options: ['△△○', '□□◇', '○○△', '☆☆□', '○△○'],
    answer: 4,
    explanation: '29. Jawaban E — Pilihan A–D memiliki dua simbol pertama yang sama; E tidak.',
  ),
  KedinasanTiuQuestion(
    number: 30,
    question: '○ : ● = □ : ...',
    options: ['△', '■', '◇', '☆', '▱'],
    answer: 1,
    explanation: '30. Jawaban B — Bentuk kosong berubah menjadi bentuk penuh: ○ menjadi ●, maka □ menjadi ■.',
  ),
  KedinasanTiuQuestion(
    number: 31,
    question:
        'Panah ↑ diputar 90 derajat searah jarum jam. Hasilnya adalah ...',
    options: ['↑', '→', '↓', '←', '↖'],
    answer: 1,
    explanation: '31. Jawaban B — Rotasi 90 derajat searah jarum jam mengubah ↑ menjadi →.',
  ),
  KedinasanTiuQuestion(
    number: 32,
    question: 'Jika bentuk “b” dicerminkan secara horizontal, bentuk yang paling mendekati adalah ...',
    options: ['b', 'd', 'p', 'q', 'h'],
    answer: 1,
    explanation: '32. Jawaban B — Pencerminan horizontal mengubah arah lengkungan seperti b menjadi d.',
  ),
  KedinasanTiuQuestion(
    number: 33,
    question: 'AB, BC, CD, DE, ... Pasangan berikutnya adalah ...',
    options: ['DF', 'EF', 'FG', 'CE', 'EG'],
    answer: 1,
    explanation: '33. Jawaban B — Huruf pertama dan kedua bergeser satu langkah secara berurutan.',
  ),
  KedinasanTiuQuestion(
    number: 34,
    question: 'Deret bentuk: △, △△, △△△, △△△△, ... Tahap berikutnya adalah ...',
    options: ['△△', '△△△', '△△△△', '△△△△△', '□□□□□'],
    answer: 3,
    explanation: '34. Jawaban D — Jumlah segitiga bertambah satu.',
  ),
  KedinasanTiuQuestion(
    number: 35,
    question: 'Manakah yang tidak mengikuti pola lainnya?',
    options: ['2–4–6', '3–6–9', '4–8–12', '5–10–15', '6–11–18'],
    answer: 4,
    explanation: '35. Jawaban E — A–D memiliki angka kedua dua kali angka pertama dan angka ketiga tiga kali angka pertama. E tidak.',
  ),
];

const PoltekSSNTiuQuestions = <KedinasanTiuQuestion>[
  KedinasanTiuQuestion(
    number: 1,
    question: 'KUNCI : PINTU = ...',
    options: [
      'Buku : Halaman',
      'Password : Akun',
      'Jalan : Kendaraan',
      'Air : Gelas',
      'Lampu : Ruangan',
    ],
    answer: 1,
    explanation: '1. Kunci B — Kunci digunakan untuk membuka pintu; password digunakan untuk membuka akses akun.',
  ),
  KedinasanTiuQuestion(
    number: 2,
    question: 'KOMPAS : ARAH = TERMOMETER : ...',
    options: ['Suhu', 'Cuaca', 'Panas', 'Ruang', 'Tekanan'],
    answer: 0,
    explanation: '2. Kunci A — Kompas mengukur/menunjukkan arah, sedangkan termometer mengukur suhu.',
  ),
  KedinasanTiuQuestion(
    number: 3,
    question: 'ENKRIPSI : KERAHASIAAN = CHECKSUM : ...',
    options: [
      'Kecepatan',
      'Integritas',
      'Ketersediaan',
      'Kerusakan',
      'Kompresi',
    ],
    answer: 1,
    explanation: '3. Kunci B — Enkripsi membantu menjaga kerahasiaan; checksum membantu memeriksa integritas data.',
  ),
  KedinasanTiuQuestion(
    number: 4,
    question: 'DOKTER : DIAGNOSIS = PENYIDIK : ...',
    options: ['Persidangan', 'Bukti', 'Investigasi', 'Hukuman', 'Saksi'],
    answer: 2,
    explanation: '4. Kunci C — Diagnosis adalah kegiatan utama dokter dalam menganalisis kondisi; investigasi adalah kegiatan utama penyidik.',
  ),
  KedinasanTiuQuestion(
    number: 5,
    question: 'Sinonim kata “VALID” adalah ...',
    options: ['Sah', 'Cepat', 'Rumit', 'Rahasia', 'Sementara'],
    answer: 0,
    explanation:
        '5. Kunci A — Valid berarti sah, benar, atau sesuai ketentuan.',
  ),
  KedinasanTiuQuestion(
    number: 6,
    question: 'Antonim kata “OBJEKTIF” adalah ...',
    options: ['Netral', 'Faktual', 'Subjektif', 'Terukur', 'Terbuka'],
    answer: 2,
    explanation: '6. Sumber rujukan fakta pola seleksi',
  ),
  KedinasanTiuQuestion(
    number: 7,
    question: 'Manakah yang tidak sekelompok?',
    options: ['Firewall', 'Antivirus', 'Antispam', 'Enkripsi', 'Phishing'],
    answer: 4,
    explanation: '7. Kunci E — Empat pilihan pertama merupakan mekanisme/alat perlindungan; phishing adalah bentuk penipuan atau serangan sosial.',
  ),
  KedinasanTiuQuestion(
    number: 8,
    question: 'Semua taruna Poltek SSN mengikuti pembinaan disiplin. Sebagian peserta kelas A adalah taruna Poltek SSN. Kesimpulan yang benar adalah ...',
    options: [
      'Semua peserta kelas A mengikuti pembinaan disiplin',
      'Sebagian peserta kelas A mengikuti pembinaan disiplin',
      'Tidak ada peserta kelas A yang disiplin',
      'Semua yang disiplin adalah taruna',
      'Sebagian taruna bukan peserta kelas A',
    ],
    answer: 1,
    explanation: '8. Kunci B — Sebagian peserta kelas A termasuk taruna, dan semua taruna mengikuti pembinaan disiplin; maka sebagian peserta kelas A mengikuti pembinaan disiplin.',
  ),
  KedinasanTiuQuestion(
    number: 9,
    question: 'Semua audit menghasilkan laporan. Sebagian pemeriksaan bukan audit. Kesimpulan yang pasti adalah ...',
    options: [
      'Semua pemeriksaan menghasilkan laporan',
      'Sebagian pemeriksaan menghasilkan laporan',
      'Semua yang menghasilkan laporan adalah audit',
      'Audit menghasilkan laporan',
      'Tidak ada pemeriksaan yang menghasilkan laporan',
    ],
    answer: 3,
    explanation: '9. Kunci D — Pernyataan yang pasti dan langsung mengikuti premis adalah semua audit menghasilkan laporan.',
  ),
  KedinasanTiuQuestion(
    number: 10,
    question: 'Lima peserta P, Q, R, S, dan T berbaris. P harus di depan Q, R harus di belakang S, dan T berada di posisi pertama. Urutan yang mungkin adalah ...',
    options: ['T-P-Q-S-R', 'T-Q-P-S-R', 'P-T-S-R-Q', 'T-S-R-Q-P', 'T-P-R-S-Q'],
    answer: 0,
    explanation: '10. Kunci A — Urutan T-P-Q-S-R memenuhi P di depan Q, R di belakang S, dan T posisi pertama.',
  ),
  KedinasanTiuQuestion(
    number: 11,
    question: 'Jika semua berkas terenkripsi wajib memiliki kunci pemulihan, dan berkas X tidak memiliki kunci pemulihan, maka ...',
    options: [
      'X pasti terenkripsi',
      'X pasti tidak terenkripsi',
      'X pasti rusak',
      'X pasti publik',
      'Tidak dapat disimpan',
    ],
    answer: 1,
    explanation: '11. Kunci B — Bentuk kontrapositif: jika tidak memiliki kunci pemulihan, berkas tersebut tidak termasuk berkas terenkripsi yang dimaksud.',
  ),
  KedinasanTiuQuestion(
    number: 12,
    question: 'Dalam suatu kode, DATA ditulis EBUB. Dengan pola yang sama, KODE ditulis ...',
    options: ['LPEF', 'JNCD', 'LPDF', 'KPDF', 'LQEF'],
    answer: 0,
    explanation: '12. Kunci A — Setiap huruf digeser satu posisi maju: K→L, O→P, D→E, E→F.',
  ),
  KedinasanTiuQuestion(
    number: 13,
    question: 'Jika 3x + 7 = 34, nilai x adalah ...',
    options: ['7', '8', '9', '10', '11'],
    answer: 2,
    explanation: '13. Kunci C — 3x = 34 - 7 = 27, sehingga x = 9.',
  ),
  KedinasanTiuQuestion(
    number: 14,
    question: '25% dari 360 ditambah 15% dari 200 adalah ...',
    options: ['90', '100', '110', '120', '130'],
    answer: 3,
    explanation: '14. Kunci D — 25%×360 = 90 dan 15%×200 = 30; totalnya 120.',
  ),
  KedinasanTiuQuestion(
    number: 15,
    question: 'Sebuah nilai naik dari 80 menjadi 100. Persentase kenaikannya adalah ...',
    options: ['20%', '25%', '30%', '40%', '50%'],
    answer: 1,
    explanation:
        '15. Kunci B — Kenaikan 20 dibagi nilai awal 80 = 0,25 atau 25%.',
  ),
  KedinasanTiuQuestion(
    number: 16,
    question: 'Rasio peserta putra dan putri adalah 3:2. Jika total peserta 45 orang, jumlah peserta putri adalah ...',
    options: ['15', '18', '20', '27', '30'],
    answer: 1,
    explanation: '16. Kunci B — Total bagian 5; satu bagian = 45/5 = 9. Putri = 2×9 = 18.',
  ),
  KedinasanTiuQuestion(
    number: 17,
    question: 'Rata-rata lima nilai adalah 76. Empat nilai pertama berjumlah 294. Nilai kelima adalah ...',
    options: ['76', '82', '84', '86', '88'],
    answer: 3,
    explanation: '17. Kunci D — Jumlah seluruh nilai = 5×76 = 380. Nilai kelima = 380−294 = 86.',
  ),
  KedinasanTiuQuestion(
    number: 18,
    question: '2, 5, 10, 17, 26, ...',
    options: ['35', '36', '37', '38', '39'],
    answer: 2,
    explanation: '18. Kunci C — Selisihnya 3, 5, 7, 9; selisih berikutnya 11, jadi 26+11 = 37.',
  ),
  KedinasanTiuQuestion(
    number: 19,
    question: '81, 27, 9, 3, ...',
    options: ['0', '1/3', '1', '2', '6'],
    answer: 2,
    explanation: '19. Kunci C — Setiap suku dibagi 3: 81, 27, 9, 3, 1.',
  ),
  KedinasanTiuQuestion(
    number: 20,
    question: '4, 7, 13, 25, 49, ...',
    options: ['73', '81', '89', '97', '101'],
    answer: 3,
    explanation:
        '20. Kunci D — Setiap suku dikali 2 lalu dikurangi 1: 49×2−1 = 97.',
  ),
  KedinasanTiuQuestion(
    number: 21,
    question: '1, 4, 9, 16, 25, ...',
    options: ['30', '32', '36', '40', '49'],
    answer: 2,
    explanation:
        '21. Kunci C — Deret kuadrat: 1², 2², 3², 4², 5²; berikutnya 6² = 36.',
  ),
  KedinasanTiuQuestion(
    number: 22,
    question: 'Jika a = 3/4 dan b = 5/8, hubungan yang benar adalah ...',
    options: ['a < b', 'a = b', 'a > b', 'a + b = 1', 'Tidak dapat ditentukan'],
    answer: 2,
    explanation: '22. Kunci C — 3/4 = 6/8, sehingga 6/8 > 5/8.',
  ),
  KedinasanTiuQuestion(
    number: 23,
    question: 'Sebuah pekerjaan selesai dalam 12 hari oleh 8 orang dengan produktivitas sama. Jika dikerjakan 6 orang, waktu yang diperlukan adalah ...',
    options: ['14 hari', '15 hari', '16 hari', '18 hari', '20 hari'],
    answer: 2,
    explanation: '23. Kunci C — Beban kerja = 8×12 = 96 orang-hari. Dengan 6 orang, waktunya 96/6 = 16 hari.',
  ),
  KedinasanTiuQuestion(
    number: 24,
    question: 'Kecepatan kendaraan 72 km/jam. Jarak yang ditempuh dalam 25 menit adalah ...',
    options: ['24 km', '27 km', '30 km', '32 km', '36 km'],
    answer: 2,
    explanation: '24. Kunci C — 72 km/jam × 25/60 jam = 30 km.',
  ),
  KedinasanTiuQuestion(
    number: 25,
    question: 'Harga barang Rp240.000 mendapat diskon 15%. Harga setelah diskon adalah ...',
    options: ['Rp196.000', 'Rp204.000', 'Rp210.000', 'Rp216.000', 'Rp225.000'],
    answer: 1,
    explanation:
        '25. Kunci B — Diskon = 15%×240.000 = 36.000; harga akhir = 204.000.',
  ),
  KedinasanTiuQuestion(
    number: 26,
    question: 'Dari 5 calon dipilih ketua dan wakil tanpa rangkap jabatan. Banyak susunan yang mungkin adalah ...',
    options: ['10', '15', '20', '25', '30'],
    answer: 2,
    explanation:
        '26. Kunci C — Ketua memiliki 5 pilihan, wakil 4 pilihan; 5×4 = 20.',
  ),
  KedinasanTiuQuestion(
    number: 27,
    question: 'Sebuah dadu bersisi enam dilempar sekali. Peluang muncul bilangan genap adalah ...',
    options: ['1/6', '1/3', '1/2', '2/3', '5/6'],
    answer: 2,
    explanation: '27. Kunci C — Bilangan genap 2, 4, 6 ada 3 dari 6 kemungkinan, jadi 3/6 = 1/2.',
  ),
  KedinasanTiuQuestion(
    number: 28,
    question:
        'Luas persegi panjang dengan panjang 18 cm dan lebar 7 cm adalah ...',
    options: ['25 cm²', '50 cm²', '96 cm²', '126 cm²', '144 cm²'],
    answer: 3,
    explanation: '28. Kunci D — Luas = panjang×lebar = 18×7 = 126 cm².',
  ),
  KedinasanTiuQuestion(
    number: 29,
    question: 'Sebuah pola jumlah sisi bangun bertambah: segitiga, persegi, segilima, segienam, ... Bangun berikutnya adalah ...',
    options: ['Lingkaran', 'Segitujuh', 'Segidelapan', 'Segisembilan', 'Garis'],
    answer: 1,
    explanation: '29. Kunci B — Jumlah sisi bertambah satu setiap langkah; setelah segienam adalah segitujuh.',
  ),
  KedinasanTiuQuestion(
    number: 30,
    question: 'Urutan arah panah berputar 90° searah jarum jam setiap langkah: ↑, →, ↓, ←, ... Arah berikutnya adalah ...',
    options: ['↑', '→', '↓', '←', '↗'],
    answer: 0,
    explanation:
        '30. Kunci A — Setelah ←, rotasi 90° searah jarum jam kembali ke ↑.',
  ),
  KedinasanTiuQuestion(
    number: 31,
    question: 'Sebuah persegi dicerminkan terhadap garis vertikal. Posisi yang berubah adalah ...',
    options: [
      'Ukuran',
      'Jumlah sisi',
      'Orientasi kiri-kanan',
      'Warna selalu menjadi hitam',
      'Luas menjadi dua kali',
    ],
    answer: 2,
    explanation: '31. Kunci C — Pencerminan vertikal membalik orientasi kiri-kanan, tetapi ukuran, luas, dan jumlah sisi tetap.',
  ),
  KedinasanTiuQuestion(
    number: 32,
    question: 'Manakah yang berbeda dari lainnya?',
    options: ['■▲■▲', '●◆●◆', '★○★○', '▲▲■■', '◆●◆●'],
    answer: 3,
    explanation: '32. Kunci D — A, B, C, dan E berpola berselang-seling; D terdiri dari dua simbol sejenis berurutan.',
  ),
  KedinasanTiuQuestion(
    number: 33,
    question: 'Jika pola pertama adalah lingkaran putih menjadi lingkaran hitam, maka persegi putih menjadi ...',
    options: [
      'Segitiga hitam',
      'Persegi hitam',
      'Persegi putih lebih besar',
      'Lingkaran hitam',
      'Garis hitam',
    ],
    answer: 1,
    explanation: '33. Kunci B — Transformasinya adalah perubahan warna putih menjadi hitam dengan bentuk tetap.',
  ),
  KedinasanTiuQuestion(
    number: 34,
    question: 'Dalam deret simbol, setiap langkah menambah satu titik: ○, ○·, ○··, ... Simbol berikutnya adalah ...',
    options: ['○', '·○', '○···', '○····', '●'],
    answer: 2,
    explanation: '34. Kunci C — Jumlah titik bertambah satu; setelah dua titik menjadi tiga titik.',
  ),
  KedinasanTiuQuestion(
    number: 35,
    question: 'Huruf “L” diputar 180°. Hasilnya memiliki ciri ...',
    options: [
      'Tetap sama persis',
      'Kaki mengarah ke kanan atas relatif terhadap posisi awal',
      'Menjadi lingkaran',
      'Hilang satu garis',
      'Menjadi huruf T',
    ],
    answer: 1,
    explanation: '35. Kunci B — Rotasi 180° membalik arah vertikal dan horizontal; bentuk L menjadi terbalik dengan kaki ke arah berlawanan.',
  ),
];

const PKNSTANTiuQuestions = <KedinasanTiuQuestion>[
  KedinasanTiuQuestion(
    number: 1,
    question: 'Sinonim kata “akuntabel” adalah …',
    options: [
      'dapat dipertanggungjawabkan',
      'dapat dirahasiakan',
      'mudah dipengaruhi',
      'selalu berubah',
      'tidak terbatas',
    ],
    answer: 0,
    explanation: '1. A — Akuntabel berarti dapat dipertanggungjawabkan, terutama atas keputusan dan penggunaan sumber daya.',
  ),
  KedinasanTiuQuestion(
    number: 2,
    question: 'Antonim kata “sporadis” adalah …',
    options: ['sesekali', 'terpencar', 'teratur', 'mendadak', 'acak'],
    answer: 2,
    explanation: '2. C — Sporadis berarti tidak teratur atau muncul sesekali; antonimnya teratur.',
  ),
  KedinasanTiuQuestion(
    number: 3,
    question: 'Hubungan kata yang setara dengan “anggaran : belanja” adalah …',
    options: [
      'peta : arah',
      'jadwal : waktu',
      'resep : bahan',
      'aturan : pelanggaran',
      'laporan : data',
    ],
    answer: 2,
    explanation: '3. C — Anggaran menjadi pedoman/perencanaan belanja, sebagaimana resep menjadi pedoman penggunaan bahan.',
  ),
  KedinasanTiuQuestion(
    number: 4,
    question: 'Semua pegawai teliti memeriksa dokumen. Sebagian pemeriksa dokumen bekerja dari rumah. Simpulan yang pasti benar adalah …',
    options: [
      'semua pegawai bekerja dari rumah',
      'sebagian pegawai teliti bekerja dari rumah',
      'semua yang bekerja dari rumah teliti',
      'belum tentu ada pegawai teliti yang bekerja dari rumah',
      'tidak ada pemeriksa dokumen yang teliti',
    ],
    answer: 3,
    explanation: '4. D — Kedua premis tidak menyatakan irisan antara pegawai teliti dan pekerja dari rumah, sehingga irisan belum pasti ada.',
  ),
  KedinasanTiuQuestion(
    number: 5,
    question: 'Bacalah: “Program A menurunkan waktu layanan dari 20 menit menjadi 15 menit. Namun, jumlah keluhan tidak berubah.” Pernyataan yang paling tepat adalah …',
    options: [
      'program pasti gagal',
      'program mempercepat layanan, tetapi belum terbukti menurunkan keluhan',
      'keluhan pasti tidak terkait waktu layanan',
      'waktu layanan sebenarnya meningkat',
      'program harus dihentikan',
    ],
    answer: 1,
    explanation: '5. B — Data mendukung percepatan layanan, tetapi tidak cukup untuk menyimpulkan pengaruh terhadap keluhan.',
  ),
  KedinasanTiuQuestion(
    number: 6,
    question: 'Kata yang maknanya paling dekat dengan “mitigasi” adalah …',
    options: [
      'penghapusan total',
      'pengurangan risiko',
      'penambahan beban',
      'pembuktian',
      'pengabaian',
    ],
    answer: 1,
    explanation:
        '6. B — Mitigasi adalah tindakan mengurangi dampak atau risiko.',
  ),
  KedinasanTiuQuestion(
    number: 7,
    question: 'Jika laporan lengkap maka pemeriksaan dapat dimulai. Pemeriksaan belum dapat dimulai. Kesimpulan logisnya adalah …',
    options: [
      'laporan pasti lengkap',
      'laporan pasti hilang',
      'laporan belum tentu lengkap',
      'laporan tidak lengkap',
      'pemeriksaan sudah selesai',
    ],
    answer: 2,
    explanation: '7. Sumber publik',
  ),
  KedinasanTiuQuestion(
    number: 8,
    question: 'Semua analis memahami data. Tidak semua orang yang memahami data adalah analis. Pernyataan yang benar adalah …',
    options: [
      'pemahaman data cukup untuk menjadi analis',
      'analis tidak memahami data',
      'analis merupakan bagian dari orang yang memahami data',
      'tidak ada analis yang memahami data',
      'semua orang adalah analis',
    ],
    answer: 2,
    explanation: '8. C — Premis pertama menyatakan himpunan analis berada di dalam himpunan orang yang memahami data.',
  ),
  KedinasanTiuQuestion(
    number: 9,
    question: 'Urutan kata yang paling efektif adalah …',
    options: [
      'Dalam rangka untuk meningkatkan maka layanan dilakukan evaluasi',
      'Evaluasi layanan dilakukan untuk meningkatkan kualitas pelayanan',
      'Untuk dalam rangka meningkatkan kualitas, evaluasi layanan adalah dilakukan',
      'Layanan kualitas meningkatkan evaluasi dilakukan',
      'Dilakukan meningkatkan evaluasi dalam pelayanan kualitas',
    ],
    answer: 1,
    explanation: '9. B — Pilihan B memiliki susunan subjek-predikat-keterangan yang jelas dan tidak mubazir.',
  ),
  KedinasanTiuQuestion(
    number: 10,
    question: '“Integritas” paling tepat diartikan sebagai …',
    options: [
      'kemampuan memengaruhi orang lain',
      'kesesuaian antara nilai, ucapan, dan tindakan',
      'keberanian mengambil risiko tanpa pertimbangan',
      'kecepatan menyelesaikan tugas',
      'kepatuhan pada semua pendapat',
    ],
    answer: 1,
    explanation: '10. B — Integritas menekankan kejujuran dan konsistensi nilai, ucapan, serta tindakan.',
  ),
  KedinasanTiuQuestion(
    number: 11,
    question: 'Semua peserta yang lolos tahap I mengikuti tahap II. Rina tidak mengikuti tahap II. Simpulan yang paling kuat adalah …',
    options: [
      'Rina pasti lolos tahap I',
      'Rina pasti tidak lolos tahap I',
      'Rina mungkin tidak lolos tahap I',
      'semua peserta gagal tahap II',
      'tahap I tidak ada',
    ],
    answer: 2,
    explanation: '11. C — Jika lolos I maka ikut II; tidak ikut II membuat Rina tidak dapat dipastikan lolos I, tetapi secara logika implikasi ia tidak lolos I bila premis berlaku tanpa pengecualian. Dalam bahasa “paling kuat” dari informasi praktis: mungkin tidak lolos; tidak ada data langsung tentang hasil tahap I.',
  ),
  KedinasanTiuQuestion(
    number: 12,
    question: 'Kata “kredibel” berlawanan makna dengan …',
    options: ['terpercaya', 'sahih', 'meyakinkan', 'meragukan', 'teruji'],
    answer: 3,
    explanation:
        '12. D — Kredibel berarti dapat dipercaya; lawannya meragukan.',
  ),
  KedinasanTiuQuestion(
    number: 13,
    question: 'Jika 3x − 7 = 20, nilai x adalah …',
    options: ['7', '8', '9', '10', '11'],
    answer: 2,
    explanation: '13. C — 3x=27 sehingga x=9.',
  ),
  KedinasanTiuQuestion(
    number: 14,
    question: 'Perbandingan pegawai A:B = 3:5. Jika jumlahnya 64 orang, banyak pegawai B adalah …',
    options: ['24', '32', '36', '40', '48'],
    answer: 3,
    explanation: '14. D — Total bagian 8; satu bagian 8. B=5×8=40.',
  ),
  KedinasanTiuQuestion(
    number: 15,
    question: 'Sebuah barang seharga Rp240.000 didiskon 15%. Harga setelah diskon adalah …',
    options: ['Rp196.000', 'Rp204.000', 'Rp210.000', 'Rp216.000', 'Rp225.000'],
    answer: 1,
    explanation: '15. B — Diskon=36.000; harga akhir=204.000.',
  ),
  KedinasanTiuQuestion(
    number: 16,
    question: 'Rata-rata lima nilai adalah 72. Empat nilai pertama 68, 75, 70, dan 80. Nilai kelima adalah …',
    options: ['65', '67', '68', '70', '72'],
    answer: 1,
    explanation: '16. B — Total lima nilai harus 360. Empat nilai berjumlah 293, sehingga nilai kelima 67.',
  ),
  KedinasanTiuQuestion(
    number: 17,
    question: 'Pola 2, 6, 12, 20, 30, … suku berikutnya adalah …',
    options: ['36', '40', '42', '44', '48'],
    answer: 2,
    explanation: '17. C — Selisihnya 4,6,8,10; selisih berikutnya 12, sehingga 30+12=42.',
  ),
  KedinasanTiuQuestion(
    number: 18,
    question: 'Sebuah pekerjaan selesai 12 hari oleh 8 orang dengan produktivitas sama. Jika dikerjakan 6 orang, waktunya …',
    options: ['8 hari', '14 hari', '16 hari', '18 hari', '20 hari'],
    answer: 2,
    explanation: '18. C — Beban kerja 8×12=96 orang-hari; 96/6=16 hari.',
  ),
  KedinasanTiuQuestion(
    number: 19,
    question: 'Sebuah pekerjaan selesai 12 hari oleh 8 orang dengan produktivitas sama. Jika dikerjakan 6 orang, waktunya …',
    options: ['8 hari', '14 hari', '16 hari', '18 hari', '20 hari'],
    answer: 3,
    explanation: '19. D — Beban kerja 8×12=96 orang-hari; 96/6=16 hari. (Koreksi: jawaban yang benar C.)',
  ),
  KedinasanTiuQuestion(
    number: 20,
    question: 'Nilai 40% dari 250 ditambah 25% dari 160 adalah …',
    options: ['120', '130', '140', '150', '160'],
    answer: 2,
    explanation: '20. C — 40%×250=100 dan 25%×160=40; total 140.',
  ),
  KedinasanTiuQuestion(
    number: 21,
    question:
        'Sebuah persegi panjang berukuran 12 cm×8 cm. Kelilingnya adalah …',
    options: ['20 cm', '32 cm', '40 cm', '48 cm', '96 cm'],
    answer: 2,
    explanation: '21. C — Keliling=2(12+8)=40 cm.',
  ),
  KedinasanTiuQuestion(
    number: 22,
    question: 'Jika a:b=4:7 dan b:c=14:15, maka a:c adalah …',
    options: ['4:15', '8:15', '14:15', '15:8', '28:15'],
    answer: 1,
    explanation: '22. B — Samakan b: 4:7 menjadi 8:14; maka a:c=8:15.',
  ),
  KedinasanTiuQuestion(
    number: 23,
    question: 'Dalam sebuah kelas, 60% peserta lulus matematika, 50% lulus verbal, dan 30% lulus keduanya. Persentase yang lulus minimal salah satu adalah …',
    options: ['70%', '80%', '90%', '110%', '140%'],
    answer: 1,
    explanation: '23. B — Gabungan=60+50−30=80%.',
  ),
  KedinasanTiuQuestion(
    number: 24,
    question:
        'Kecepatan rata-rata untuk menempuh 120 km dalam 2,5 jam adalah …',
    options: [
      'forty km/jam',
      '48 km/jam',
      '50 km/jam',
      '60 km/jam',
      '72 km/jam',
    ],
    answer: 1,
    explanation:
        '24. B — 120/2,5=48 km/jam. Opsi A ditulis “forty” dan bukan jawaban.',
  ),
  KedinasanTiuQuestion(
    number: 25,
    question:
        'Kecepatan rata-rata untuk menempuh 120 km dalam 2,5 jam adalah …',
    options: ['40 km/jam', '48 km/jam', '50 km/jam', '60 km/jam', '72 km/jam'],
    answer: 1,
    explanation: '25. B — Kecepatan=jarak/waktu=120/2,5=48 km/jam.',
  ),
  KedinasanTiuQuestion(
    number: 26,
    question: 'Lima orang P, Q, R, S, T duduk berderet. P di kiri Q, R di kanan Q, S di kiri P, dan T di kanan R. Urutan dari kiri ke kanan adalah …',
    options: ['S-P-Q-R-T', 'P-S-Q-R-T', 'S-Q-P-R-T', 'T-R-Q-P-S', 'P-Q-S-R-T'],
    answer: 0,
    explanation: '26. A — Semua relasi terpenuhi oleh S-P-Q-R-T.',
  ),
  KedinasanTiuQuestion(
    number: 27,
    question:
        'Jika pola simbol berulang △, ○, □, △, ○, □, … simbol ke-17 adalah …',
    options: ['△', '○', '□', '△○', 'tidak dapat ditentukan'],
    answer: 1,
    explanation: '27. B — Pola berulang tiap 3 posisi. Posisi 17 bersisa 2 saat dibagi 3, jadi simbol kedua: ○.',
  ),
  KedinasanTiuQuestion(
    number: 28,
    question: 'Semua kotak A berwarna merah. Sebagian benda merah berbentuk lingkaran. Pernyataan pasti benar adalah …',
    options: [
      'semua benda merah adalah kotak A',
      'sebagian kotak A berbentuk lingkaran',
      'tidak ada kotak A berbentuk lingkaran',
      'semua kotak A berwarna merah',
      'semua lingkaran berwarna merah',
    ],
    answer: 3,
    explanation:
        '28. D — Hanya premis “semua kotak A berwarna merah” yang pasti.',
  ),
  KedinasanTiuQuestion(
    number: 29,
    question: 'Urutan huruf: B, E, I, N, T, … Huruf berikutnya adalah …',
    options: ['Y', 'Z', 'A', 'B', 'C'],
    answer: 2,
    explanation: '29. C — Lompatan +3,+4,+5,+6; berikutnya +7 dari T melingkar menjadi A.',
  ),
  KedinasanTiuQuestion(
    number: 30,
    question: 'Jika hari ini Rabu, 100 hari lagi adalah …',
    options: ['Kamis', 'Jumat', 'Sabtu', 'Minggu', 'Senin'],
    answer: 1,
    explanation: '30. B — 100 mod 7=2; Rabu maju dua hari menjadi Jumat.',
  ),
  KedinasanTiuQuestion(
    number: 31,
    question: 'Dalam kode tertentu, KOTA ditulis 11-15-20-1. Dengan pola yang sama, DATA ditulis …',
    options: ['4-1-20-1', '4-2-20-1', '5-1-20-2', '4-1-19-1', '3-1-20-1'],
    answer: 0,
    explanation:
        '31. A — Kode menggunakan posisi huruf alfabet: D=4, A=1, T=20, A=1.',
  ),
  KedinasanTiuQuestion(
    number: 32,
    question: 'Tiga lampu A, B, C menyala bergantian. A menyala setiap 2 detik, B setiap 3 detik, C setiap 4 detik. Ketiganya menyala bersamaan setiap … detik.',
    options: ['6', '8', '9', '12', '24'],
    answer: 3,
    explanation: '32. D — Kelipatan persekutuan terkecil 2,3,4 adalah 12.',
  ),
  KedinasanTiuQuestion(
    number: 33,
    question: 'Jika semua X adalah Y dan tidak ada Y yang Z, maka …',
    options: [
      'sebagian X adalah Z',
      'semua Z adalah X',
      'tidak ada X yang Z',
      'semua Y adalah X',
      'X dan Z selalu sama',
    ],
    answer: 2,
    explanation: '33. C — X berada di dalam Y, sedangkan Y tidak beririsan dengan Z; maka X juga tidak beririsan dengan Z.',
  ),
  KedinasanTiuQuestion(
    number: 34,
    question: 'Sebuah kubus memiliki semua sisi dicat lalu dipotong menjadi 27 kubus kecil sama besar. Banyak kubus kecil yang memiliki tepat dua sisi bercat adalah …',
    options: ['4', '8', '12', '16', '24'],
    answer: 2,
    explanation: '34. C — Kubus kecil dengan tepat dua sisi bercat berada di tengah setiap rusuk: 12 rusuk×1=12.',
  ),
  KedinasanTiuQuestion(
    number: 35,
    question: 'Empat tugas W, X, Y, Z dikerjakan berurutan. W sebelum X, Y setelah X, dan Z sebelum W. Urutan yang mungkin adalah …',
    options: ['W-Z-X-Y', 'Z-W-X-Y', 'X-Z-W-Y', 'Z-X-Y-W', 'Y-Z-W-X'],
    answer: 1,
    explanation: '35. B — Urutan Z-W-X-Y memenuhi Z sebelum W, W sebelum X, dan Y setelah X.',
  ),
];

const STINTiuQuestions = <KedinasanTiuQuestion>[
  KedinasanTiuQuestion(
    number: 1,
    question: 'KOMPAS : ARAH = TERMOMETER : ...',
    options: ['Berat', 'Suhu', 'Waktu', 'Jarak', 'Kecepatan'],
    answer: 1,
    explanation: '1. Kompas digunakan untuk mengetahui arah; termometer digunakan untuk mengukur suhu.',
  ),
  KedinasanTiuQuestion(
    number: 2,
    question: 'KREDIBEL : DIPERCAYA = AKURAT : ...',
    options: ['Cepat', 'Tepat', 'Rumit', 'Panjang', 'Baru'],
    answer: 1,
    explanation: '2. Akurt berarti tepat atau sesuai kenyataan.',
  ),
  KedinasanTiuQuestion(
    number: 3,
    question: 'Semua analis teliti. Sebagian pegawai adalah analis. Kesimpulan yang tepat adalah ...',
    options: [
      'Semua pegawai teliti',
      'Sebagian pegawai teliti',
      'Sebagian analis tidak teliti',
      'Semua yang teliti adalah analis',
      'Tidak ada pegawai yang teliti',
    ],
    answer: 1,
    explanation: '3. Sebagian pegawai yang termasuk analis pasti teliti.',
  ),
  KedinasanTiuQuestion(
    number: 4,
    question: 'Semua data terenkripsi sulit dibaca tanpa kunci. Berkas X sulit dibaca tanpa kunci. Kesimpulan yang pasti benar adalah ...',
    options: [
      'Berkas X pasti terenkripsi',
      'Berkas X pasti bukan data',
      'Jika X terenkripsi, X sulit dibaca tanpa kunci',
      'Semua berkas sulit dibaca',
      'Kunci X pasti hilang',
    ],
    answer: 2,
    explanation: '4. Premis hanya memberi implikasi satu arah; kesimpulan aman adalah bentuk bersyaratnya.',
  ),
  KedinasanTiuQuestion(
    number: 5,
    question: 'INTEGRITAS : JUJUR = AKUNTABILITAS : ...',
    options: ['Bertanggung jawab', 'Berani', 'Cepat', 'Kreatif', 'Hemat'],
    answer: 0,
    explanation: '5. Akuntabilitas berkaitan dengan kewajiban mempertanggungjawabkan tindakan.',
  ),
  KedinasanTiuQuestion(
    number: 6,
    question: 'Padanan kata yang paling tepat untuk "mitigasi" adalah ...',
    options: [
      'Perluasan',
      'Pengurangan risiko',
      'Penghapusan data',
      'Penundaan',
      'Penetapan',
    ],
    answer: 1,
    explanation: '6. Mitigasi adalah upaya mengurangi dampak atau risiko.',
  ),
  KedinasanTiuQuestion(
    number: 7,
    question: 'Lawan kata "konvergen" adalah ...',
    options: ['Terpusat', 'Sejajar', 'Divergen', 'Konsisten', 'Stabil'],
    answer: 2,
    explanation:
        '7. Konvergen berarti menuju satu titik; lawannya divergen, menyebar.',
  ),
  KedinasanTiuQuestion(
    number: 8,
    question: 'PETA : WILAYAH = INDEKS : ...',
    options: ['Buku', 'Sampul', 'Kertas', 'Huruf', 'Rak'],
    answer: 0,
    explanation: '8. Peta merepresentasikan wilayah; indeks membantu menemukan isi buku.',
  ),
  KedinasanTiuQuestion(
    number: 9,
    question: 'Tidak ada laporan rahasia yang boleh dibagikan kepada publik. Dokumen Y adalah laporan rahasia. Maka ...',
    options: [
      'Y boleh dibagikan terbatas kepada publik',
      'Y tidak boleh dibagikan kepada publik',
      'Y bukan laporan',
      'Semua dokumen tidak boleh dibagikan',
      'Publik harus membaca Y',
    ],
    answer: 1,
    explanation: '9. Dokumen Y termasuk kelompok yang tidak boleh dibagikan kepada publik.',
  ),
  KedinasanTiuQuestion(
    number: 10,
    question: 'Kata yang paling dekat maknanya dengan "presisi" adalah ...',
    options: [
      'Ketelitian',
      'Kecepatan',
      'Keluwesan',
      'Keberanian',
      'Kelangkaan',
    ],
    answer: 0,
    explanation: '10. Presisi berarti ketepatan atau ketelitian.',
  ),
  KedinasanTiuQuestion(
    number: 11,
    question: 'Sebuah nilai naik 20% lalu turun 20%. Jika nilai awal 250, nilai akhirnya adalah ...',
    options: ['230', '240', '245', '250', '260'],
    answer: 1,
    explanation: '11. 250 x 1,2 x 0,8 = 240.',
  ),
  KedinasanTiuQuestion(
    number: 12,
    question: 'Rasio A:B = 3:5. Jika A+B=64, nilai B adalah ...',
    options: ['24', '32', '36', '40', '48'],
    answer: 3,
    explanation: '12. Jumlah bagian 8; satu bagian 8; B=5x8=40.',
  ),
  KedinasanTiuQuestion(
    number: 13,
    question: '2, 5, 11, 23, 47, ...',
    options: ['71', '83', '95', '97', '101'],
    answer: 2,
    explanation: '13. Pola x2+1: 47x2+1=95.',
  ),
  KedinasanTiuQuestion(
    number: 14,
    question: '81, 27, 9, 3, ...',
    options: ['0', '1/3', '1', '2', '6'],
    answer: 2,
    explanation: '14. Setiap suku dibagi 3; suku berikutnya 1.',
  ),
  KedinasanTiuQuestion(
    number: 15,
    question: 'Jika 3x - 7 = 2x + 11, maka x = ...',
    options: ['4', '11', '14', '18', '21'],
    answer: 3,
    explanation: '15. Pindahkan 2x ke kiri dan -7 ke kanan: x=18.',
  ),
  KedinasanTiuQuestion(
    number: 16,
    question: 'Dari 80 peserta, 35% lulus tahap pertama. Jumlah peserta yang lulus adalah ...',
    options: ['24', '26', '28', '30', '32'],
    answer: 2,
    explanation: '16. 35% x 80 = 28.',
  ),
  KedinasanTiuQuestion(
    number: 17,
    question: 'A menyelesaikan pekerjaan dalam 6 hari, B dalam 12 hari. Jika bekerja bersama, selesai dalam ...',
    options: ['3 hari', '4 hari', '5 hari', '6 hari', '9 hari'],
    answer: 1,
    explanation:
        '17. Laju gabungan 1/6+1/12=1/4 pekerjaan per hari, jadi 4 hari.',
  ),
  KedinasanTiuQuestion(
    number: 18,
    question: 'Kendaraan menempuh 180 km dalam 3 jam 45 menit. Kecepatan rata-ratanya adalah ...',
    options: ['40 km/jam', '45 km/jam', '48 km/jam', '50 km/jam', '60 km/jam'],
    answer: 2,
    explanation: '18. 3 jam 45 menit=3,75 jam; 180/3,75=48 km/jam.',
  ),
  KedinasanTiuQuestion(
    number: 19,
    question: 'Luas persegi panjang 96 cm2. Jika panjang 12 cm, kelilingnya adalah ...',
    options: ['32 cm', '36 cm', '40 cm', '44 cm', '48 cm'],
    answer: 2,
    explanation: '19. Lebar=96/12=8; keliling=2(12+8)=40 cm.',
  ),
  KedinasanTiuQuestion(
    number: 20,
    question: 'Rata-rata 5 bilangan adalah 18. Jika satu bilangan 26 dihapus, rata-rata 4 bilangan tersisa ...',
    options: ['15', '16', '16,5', '17', '17,5'],
    answer: 1,
    explanation: '20. Jumlah awal 90; sisa 64; 64/4=16.',
  ),
  KedinasanTiuQuestion(
    number: 21,
    question: 'Dari 5 calon dipilih ketua dan sekretaris, tanpa rangkap jabatan. Banyak cara adalah ...',
    options: ['10', '15', '20', '25', '30'],
    answer: 2,
    explanation: '21. Ketua 5 pilihan, sekretaris 4 pilihan: 5x4=20.',
  ),
  KedinasanTiuQuestion(
    number: 22,
    question: 'Sebuah kotak berisi 3 bola merah dan 2 biru. Satu bola diambil acak. Peluang mendapat bola biru adalah ...',
    options: ['1/5', '2/5', '1/2', '3/5', '2/3'],
    answer: 1,
    explanation: '22. Ada 2 bola biru dari total 5 bola, jadi peluang 2/5.',
  ),
  KedinasanTiuQuestion(
    number: 23,
    question: 'Jika 2/3 dari suatu bilangan adalah 48, bilangan itu adalah ...',
    options: ['64', '72', '80', '96', '108'],
    answer: 1,
    explanation: '23. Bilangan=48 x 3/2=72.',
  ),
  KedinasanTiuQuestion(
    number: 24,
    question: '4, 7, 13, 22, 34, ...',
    options: ['46', '47', '48', '49', '50'],
    answer: 3,
    explanation: '24. Selisih 3,6,9,12; berikutnya +15, jadi 49.',
  ),
  KedinasanTiuQuestion(
    number: 25,
    question:
        'Pola simbol: ▲, ■, ▲▲, ■■, ▲▲▲, ... Simbol berikutnya adalah ...',
    options: ['▲▲▲▲', '■■■', '▲■▲', '■■▲', '▲▲■'],
    answer: 1,
    explanation:
        '25. Jenis simbol bergantian segitiga-kotak, jumlahnya bertambah satu.',
  ),
  KedinasanTiuQuestion(
    number: 26,
    question: 'Pola: ○, ○○, △△△, △△△△, □□□□□, ... Banyak simbol pada suku berikutnya adalah ...',
    options: ['4', '5', '6', '7', '8'],
    answer: 2,
    explanation: '26. Kelompok simbol berpasangan: 1,2 lalu 3,4 lalu 5,6.',
  ),
  KedinasanTiuQuestion(
    number: 27,
    question: 'Sebuah panah mengarah ke atas. Jika diputar 90° searah jarum jam dua kali, arahnya menjadi ...',
    options: ['Atas', 'Bawah', 'Kiri', 'Kanan', 'Miring 45°'],
    answer: 1,
    explanation: '27. Dua kali 90° searah jarum jam sama dengan 180°, sehingga mengarah ke bawah.',
  ),
  KedinasanTiuQuestion(
    number: 28,
    question: 'Dalam pola 2x2, tiga sel berisi: kiri atas ●, kanan atas ○, kiri bawah ○. Simbol yang melengkapi kanan bawah agar tiap baris dan kolom memiliki satu ● dan satu ○ adalah ...',
    options: ['●', '○', '▲', '■', 'Tidak dapat ditentukan'],
    answer: 0,
    explanation: '28. Setiap baris/kolom memuat satu lingkaran penuh dan satu kosong; kanan bawah harus ●.',
  ),
  KedinasanTiuQuestion(
    number: 29,
    question: 'Jika bentuk △ diberi aturan menjadi ▲, maka bentuk □ diberi aturan yang sama menjadi ...',
    options: ['■', '○', '◇', '△', '□'],
    answer: 0,
    explanation:
        '29. Aturannya mengubah bentuk garis luar menjadi bentuk terisi.',
  ),
  KedinasanTiuQuestion(
    number: 30,
    question: 'Urutan jumlah sisi: segitiga, persegi, segilima, segienam, ... Bentuk berikutnya adalah ...',
    options: ['Lingkaran', 'Segitiga', 'Segiempat', 'Segitujuh', 'Garis'],
    answer: 3,
    explanation:
        '30. Jumlah sisi bertambah satu; setelah segienam adalah segitujuh.',
  ),
  KedinasanTiuQuestion(
    number: 31,
    question: 'Manakah yang berbeda dari kelompok lainnya?',
    options: ['▲', '■', '◆', '●', '⬟'],
    answer: 3,
    explanation: '31. ● tidak memiliki sisi; yang lain adalah bentuk bersisi.',
  ),
  KedinasanTiuQuestion(
    number: 32,
    question: 'Pola arah: ↑, →, ↓, ←, ↑, ... Arah berikutnya adalah ...',
    options: ['↑', '→', '↓', '←', '↗'],
    answer: 1,
    explanation: '32. Arah berputar 90° searah jarum jam secara berulang.',
  ),
  KedinasanTiuQuestion(
    number: 33,
    question: 'Jika simbol ↗ dicerminkan terhadap sumbu vertikal, hasilnya adalah ...',
    options: ['↖', '↘', '↙', '↗', '↓'],
    answer: 0,
    explanation: '33. Pencerminan vertikal mengubah kanan menjadi kiri, sehingga ↗ menjadi ↖.',
  ),
  KedinasanTiuQuestion(
    number: 34,
    question:
        'Urutan pasangan: AB, BC, CD, DE, ... pasangan berikutnya adalah ...',
    options: ['EF', 'FG', 'CE', 'ED', 'AF'],
    answer: 0,
    explanation:
        '34. Kedua huruf bergeser satu posisi setiap langkah: DE menjadi EF.',
  ),
  KedinasanTiuQuestion(
    number: 35,
    question: 'Baris pertama memiliki 1 titik, baris kedua 2 titik, baris ketiga 3 titik. Jika setiap kolom mengikuti pola yang sama, sel berikutnya setelah 3 titik adalah ...',
    options: ['1 titik', '2 titik', '3 titik', '4 titik', '6 titik'],
    answer: 3,
    explanation: '35. Jumlah titik bertambah satu pada tiap langkah.',
  ),
];
