// ignore_for_file: constant_identifier_names

/// Bank soal TWK prediksi sekolah kedinasan dari dokumen TB XI.
class KedinasanTwkQuestion {
  final int number;
  final String question;
  final List<String> options;
  final int answer;
  final String explanation;

  const KedinasanTwkQuestion({
    required this.number,
    required this.question,
    required this.options,
    required this.answer,
    required this.explanation,
  });
}

const PoltekimTwkQuestions = <KedinasanTwkQuestion>[
  KedinasanTwkQuestion(
    number: 1,
    question:
        'Sikap yang sesuai sila kedua dalam pelayanan keimigrasian adalah ...',
    options: [
      'Memperlakukan pemohon secara adil dan beradab',
      'Mendahulukan orang yang dikenal',
      'Membedakan berdasarkan kewarganegaraan tanpa dasar',
      'Mengabaikan keluhan',
      'Meminta imbalan',
    ],
    answer: 0,
    explanation: '1. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 2,
    question:
        'Penerapan sila ketiga di wilayah perbatasan ditunjukkan dengan ...',
    options: [
      'Menolak warga daerah lain',
      'Menjaga persatuan dan menghormati keberagaman masyarakat',
      'Mengutamakan kepentingan kelompok',
      'Menyebarkan isu konflik',
      'Mengabaikan koordinasi',
    ],
    answer: 1,
    explanation: '2. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 3,
    question: 'Musyawarah dalam menyelesaikan persoalan pelayanan berarti ...',
    options: [
      'Memaksakan keputusan',
      'Mendengar pihak terkait dan mengambil keputusan berdasarkan aturan',
      'Mengikuti tekanan massa',
      'Menutup informasi',
      'Membiarkan masalah',
    ],
    answer: 1,
    explanation: '3. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 4,
    question: 'UUD NRI Tahun 1945 merupakan ...',
    options: [
      'Hukum dasar tertulis negara',
      'Peraturan teknis kantor',
      'Pedoman kelompok',
      'Kebiasaan daerah',
      'Aturan internal',
    ],
    answer: 0,
    explanation: '4. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 5,
    question: 'Prinsip negara hukum mengharuskan petugas imigrasi ...',
    options: [
      'Bertindak berdasarkan hukum dan prosedur',
      'Mengikuti perintah apa pun',
      'Mengutamakan senioritas',
      'Membuat aturan pribadi',
      'Mengabaikan hak pemohon',
    ],
    answer: 0,
    explanation: '5. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 6,
    question: 'Salah satu tujuan negara dalam Pembukaan UUD 1945 adalah ...',
    options: [
      'Melindungi segenap bangsa Indonesia',
      'Menguasai negara lain',
      'Menghapus budaya daerah',
      'Membatasi pendidikan',
      'Mengutamakan kelompok tertentu',
    ],
    answer: 0,
    explanation: '6. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 7,
    question: 'Bentuk negara Indonesia adalah ...',
    options: ['Serikat', 'Kesatuan', 'Monarki', 'Konfederasi', 'Protektorat'],
    answer: 1,
    explanation: '7. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 8,
    question: 'Kedaulatan negara di perbatasan harus dijaga dengan ...',
    options: [
      'Tindakan tanpa hukum',
      'Penegakan hukum, koordinasi, dan pelayanan yang profesional',
      'Menolak semua orang asing',
      'Menyebarkan data pemeriksaan',
      'Mengutamakan kepentingan pribadi',
    ],
    answer: 1,
    explanation: '8. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 9,
    question: 'Bhinneka Tunggal Ika mengajarkan ...',
    options: [
      'Perbedaan harus dihapus',
      'Berbeda-beda tetapi tetap satu',
      'Mayoritas selalu benar',
      'Budaya harus seragam',
      'Daerah boleh memisahkan diri',
    ],
    answer: 1,
    explanation: '9. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 10,
    question: 'Bela negara bagi calon taruna Poltekim diwujudkan dengan ...',
    options: [
      'Disiplin, taat hukum, menjaga integritas, dan siap mengabdi',
      'Membocorkan data pemeriksaan',
      'Mengikuti semua ajakan',
      'Membela pelanggaran',
      'Mengejar popularitas',
    ],
    answer: 0,
    explanation: '10. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 11,
    question: 'Jika menerima informasi provokatif tentang warga negara asing, Anda ...',
    options: [
      'Langsung menyebarkan',
      'Memeriksa fakta dan tidak menyebarkan ujaran kebencian',
      'Menambahkan komentar',
      'Menyalahkan kelompok tertentu',
      'Mengajak orang lain marah',
    ],
    answer: 1,
    explanation: '11. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 12,
    question: 'Menjaga perbatasan sekaligus menghormati hukum menunjukkan ...',
    options: [
      'Bela negara yang bertanggung jawab',
      'Kelemahan petugas',
      'Sikap tidak tegas',
      'Penolakan terhadap negara',
      'Kepentingan pribadi',
    ],
    answer: 0,
    explanation: '12. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 13,
    question: 'Integritas berarti ...',
    options: [
      'Kesesuaian nilai, ucapan, dan tindakan',
      'Kemampuan menutupi kesalahan',
      'Ketaatan ketika diawasi',
      'Keberanian melanggar aturan',
      'Kemampuan mencari keuntungan',
    ],
    answer: 0,
    explanation: '13. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 14,
    question: 'Jika menemukan data pada dokumen tidak sesuai, Anda ...',
    options: [
      'Membiarkan',
      'Memeriksa bukti dan memproses sesuai prosedur',
      'Mengubah diam-diam',
      'Meminta imbalan',
      'Menyalahkan pemohon',
    ],
    answer: 1,
    explanation: '14. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 15,
    question:
        'Jika pemohon menawarkan uang agar prosesnya dipercepat, Anda ...',
    options: [
      'Menerima sedikit',
      'Menolak dan melaporkan melalui jalur resmi',
      'Menerima jika tidak ada saksi',
      'Membagi dengan rekan',
      'Meminta hadiah lain',
    ],
    answer: 1,
    explanation: '15. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 16,
    question: 'Konflik kepentingan terjadi apabila ...',
    options: [
      'Keputusan berdasarkan aturan',
      'Hubungan pribadi memengaruhi keputusan tugas',
      'Layanan sesuai antrean',
      'Laporan diperiksa',
      'Petugas mengikuti SOP',
    ],
    answer: 1,
    explanation: '16. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 17,
    question: 'Menggunakan kewenangan untuk membantu perusahaan milik keluarga merupakan ...',
    options: [
      'Pelayanan prima',
      'Konflik kepentingan dan penyalahgunaan kewenangan',
      'Bela negara',
      'Kewajiban keluarga',
      'Tindakan netral',
    ],
    answer: 1,
    explanation: '17. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 18,
    question: 'Dalam pelayanan keimigrasian, HAM harus ...',
    options: [
      'Dihormati sesuai hukum dan prosedur',
      'Diabaikan demi kecepatan',
      'Berlaku hanya bagi pemohon tertentu',
      'Menjadi alasan menolak pemeriksaan',
      'Diberikan berdasarkan imbalan',
    ],
    answer: 0,
    explanation: '18. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 19,
    question: 'Perlakuan non-diskriminatif berarti ...',
    options: [
      'Memberi layanan berdasarkan aturan tanpa membedakan latar belakang',
      'Memberi prioritas kepada kenalan',
      'Menilai dari asal daerah',
      'Mengutamakan kelompok mayoritas',
      'Membatasi informasi bagi kelompok tertentu',
    ],
    answer: 0,
    explanation: '19. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 20,
    question: 'Pelayanan keimigrasian yang baik harus ...',
    options: [
      'Adil, transparan, jelas, dan tidak diskriminatif',
      'Bergantung pada hadiah',
      'Mendahulukan pejabat',
      'Menutup persyaratan',
      'Mengabaikan pemohon',
    ],
    answer: 0,
    explanation: '20. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 21,
    question: 'Jika pemohon tidak memahami persyaratan, petugas sebaiknya ...',
    options: [
      'Menyalahkan pemohon',
      'Menjelaskan dengan bahasa sederhana sesuai aturan',
      'Meminta biaya tambahan',
      'Menyuruh mencari sendiri',
      'Memproses tanpa dokumen',
    ],
    answer: 1,
    explanation: '21. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 22,
    question: 'Data paspor dan data pribadi pemohon harus ...',
    options: [
      'Disebar ke grup',
      'Diakses dan disampaikan hanya sesuai kewenangan',
      'Diunggah untuk transparansi',
      'Dijadikan bahan candaan',
      'Diberikan kepada teman',
    ],
    answer: 1,
    explanation: '22. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 23,
    question: 'Jika keluarga meminta data pemeriksaan seseorang, Anda ...',
    options: [
      'Memberikan karena keluarga',
      'Menolak dengan sopan dan mengarahkan ke prosedur resmi',
      'Memberikan sebagian',
      'Meminta imbalan',
      'Mengunggah tanpa nama',
    ],
    answer: 1,
    explanation: '23. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 24,
    question: 'Disiplin taruna ditunjukkan dengan ...',
    options: [
      'Menaati jadwal dan prosedur meski tidak diawasi',
      'Mengikuti aturan yang disukai',
      'Datang saat diperiksa',
      'Mengandalkan rekan',
      'Mencari alasan',
    ],
    answer: 0,
    explanation: '24. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 25,
    question:
        'Jika senior meminta Anda melanggar prosedur pemeriksaan, Anda ...',
    options: [
      'Langsung melaksanakan',
      'Memastikan instruksi dan menyampaikan keberatan melalui jalur resmi',
      'Mengunggah tuduhan',
      'Meminta imbalan',
      'Menyebarkan gosip',
    ],
    answer: 1,
    explanation: '25. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 26,
    question: 'Netralitas petugas dalam pelayanan berarti ...',
    options: [
      'Melayani berdasarkan aturan tanpa memihak kepentingan politik atau pribadi',
      'Mendukung pemohon yang dikenal',
      'Mengutamakan kelompok tertentu',
      'Menolak kritik',
      'Mengikuti tekanan pihak luar',
    ],
    answer: 0,
    explanation: '26. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 27,
    question: 'Kalimat efektif yang tepat adalah ...',
    options: [
      'Para pemohon-pemohon wajib hadir.',
      'Pemohon wajib hadir tepat waktu.',
      'Kepada pemohon diwajibkan untuk hadir.',
      'Pemohon wajib untuk dapat hadir.',
      'Para pemohon semuanya wajib hadir.',
    ],
    answer: 1,
    explanation: '27. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 28,
    question: 'Kata baku yang tepat adalah ...',
    options: ['Resiko', 'Ijin', 'Analisa', 'Aktivitas', 'Praktek'],
    answer: 3,
    explanation: '28. Jawaban D',
  ),
  KedinasanTwkQuestion(
    number: 29,
    question: 'Jika terjadi antrean panjang dan warga mulai emosi, tindakan tepat adalah ...',
    options: [
      'Membalas dengan marah',
      'Menjelaskan prosedur, menjaga ketertiban, dan melayani sesuai antrean',
      'Mendahulukan kenalan',
      'Menutup layanan tanpa penjelasan',
      'Meminta imbalan untuk prioritas',
    ],
    answer: 1,
    explanation: '29. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 30,
    question: 'Jika melihat rekan membocorkan data pemohon, Anda ...',
    options: [
      'Membiarkan',
      'Mengamankan informasi dan melaporkan melalui mekanisme resmi',
      'Ikut menyebarkan',
      'Meminta bagian data',
      'Menjadikannya bahan candaan',
    ],
    answer: 1,
    explanation: '30. Jawaban B',
  ),
];

const PoltekipTwkQuestions = <KedinasanTwkQuestion>[
  KedinasanTwkQuestion(
    number: 1,
    question:
        'Sikap yang sesuai sila kedua dalam pembinaan warga binaan adalah ...',
    options: [
      'Memperlakukan manusia secara adil dan beradab',
      'Membalas kesalahan dengan kekerasan',
      'Membedakan berdasarkan status',
      'Mengabaikan hak dasar',
      'Mendahulukan kepentingan petugas',
    ],
    answer: 0,
    explanation: '1. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 2,
    question: 'Penerapan sila ketiga dalam lingkungan pemasyarakatan terlihat dari ...',
    options: [
      'Membeda-bedakan warga binaan',
      'Menjaga persatuan dan memperlakukan semua secara adil',
      'Mengutamakan kelompok tertentu',
      'Menghindari kerja sama',
      'Membalas provokasi',
    ],
    answer: 1,
    explanation: '2. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 3,
    question: 'Musyawarah yang baik saat menangani masalah sosial berarti ...',
    options: [
      'Memaksakan pendapat',
      'Mendengar pihak terkait dan mengambil keputusan bertanggung jawab',
      'Mengikuti tekanan massa',
      'Membiarkan masalah',
      'Menutup informasi',
    ],
    answer: 1,
    explanation: '3. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 4,
    question: 'UUD NRI Tahun 1945 merupakan ...',
    options: [
      'Hukum dasar tertulis negara',
      'Peraturan teknis lembaga',
      'Pedoman kelompok',
      'Kebiasaan daerah',
      'Aturan internal',
    ],
    answer: 0,
    explanation: '4. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 5,
    question: 'Prinsip negara hukum mengharuskan petugas ...',
    options: [
      'Bertindak berdasarkan hukum dan prosedur',
      'Mengikuti perintah apa pun',
      'Mengutamakan senioritas',
      'Mengabaikan hak warga',
      'Membuat aturan pribadi',
    ],
    answer: 0,
    explanation: '5. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 6,
    question: 'Salah satu tujuan negara dalam Pembukaan UUD 1945 adalah ...',
    options: [
      'Melindungi segenap bangsa Indonesia',
      'Menguasai negara lain',
      'Membatasi pendidikan',
      'Menghapus budaya',
      'Mendahulukan golongan',
    ],
    answer: 0,
    explanation: '6. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 7,
    question: 'Bentuk negara Indonesia adalah ...',
    options: ['Serikat', 'Kesatuan', 'Monarki', 'Konfederasi', 'Protektorat'],
    answer: 1,
    explanation: '7. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 8,
    question: 'Bhinneka Tunggal Ika mengajarkan ...',
    options: [
      'Perbedaan harus dihapus',
      'Berbeda-beda tetapi tetap satu',
      'Mayoritas selalu benar',
      'Daerah boleh memisahkan diri',
      'Budaya harus seragam',
    ],
    answer: 1,
    explanation: '8. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 9,
    question:
        'Sikap tepat menghadapi konflik antarkelompok di masyarakat adalah ...',
    options: [
      'Memihak kelompok terbesar',
      'Menjaga netralitas, mencegah kekerasan, dan bertindak sesuai hukum',
      'Menyebarkan identitas pihak',
      'Membiarkan konflik',
      'Membalas provokasi',
    ],
    answer: 1,
    explanation: '9. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 10,
    question: 'Bela negara bagi calon taruna Poltekip diwujudkan dengan ...',
    options: [
      'Disiplin, taat hukum, dan siap mengabdi',
      'Membocorkan informasi',
      'Mengabaikan prosedur',
      'Membela pelanggaran',
      'Mengutamakan popularitas',
    ],
    answer: 0,
    explanation: '10. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 11,
    question: 'Informasi provokatif tentang kerusuhan di lapas sebaiknya ...',
    options: [
      'Langsung disebarkan',
      'Diverifikasi melalui sumber berwenang dan tidak disebarkan sembarangan',
      'Dibumbui agar menarik',
      'Dijadikan bahan ejekan',
      'Diteruskan ke semua grup',
    ],
    answer: 1,
    explanation: '11. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 12,
    question: 'Menjaga keamanan dan tetap menghormati hukum merupakan ...',
    options: [
      'Bela negara yang bertanggung jawab',
      'Tanda kelemahan',
      'Bentuk diskriminasi',
      'Hal yang tidak berkaitan',
      'Penghambat pelayanan',
    ],
    answer: 0,
    explanation: '12. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 13,
    question: 'Integritas berarti ...',
    options: [
      'Kesesuaian nilai, ucapan, dan tindakan',
      'Kemampuan menutupi kesalahan',
      'Ketaatan saat diawasi',
      'Keberanian melanggar aturan',
      'Kemampuan mencari keuntungan',
    ],
    answer: 0,
    explanation: '13. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 14,
    question: 'Jika menemukan barang terlarang dalam pemeriksaan, Anda ...',
    options: [
      'Menyimpannya',
      'Mengikuti prosedur, mencatat, mengamankan, dan melaporkan',
      'Menjualnya',
      'Membiarkan',
      'Meminta imbalan',
    ],
    answer: 1,
    explanation: '14. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 15,
    question: 'Jika warga binaan menawarkan hadiah agar mendapat perlakuan khusus, Anda ...',
    options: [
      'Menerima diam-diam',
      'Menolak dan melaporkan sesuai aturan',
      'Menerima sedikit',
      'Meminta hadiah lain',
      'Membalas dengan ancaman',
    ],
    answer: 1,
    explanation: '15. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 16,
    question:
        'Jika rekan menyalahgunakan kewenangan, tindakan tepat adalah ...',
    options: [
      'Membiarkan',
      'Melaporkan melalui mekanisme resmi dengan informasi yang benar',
      'Menyebarkan sebagai gosip',
      'Meminta imbalan',
      'Ikut membantu',
    ],
    answer: 1,
    explanation: '16. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 17,
    question: 'Konflik kepentingan terjadi apabila ...',
    options: [
      'Keputusan sesuai prosedur',
      'Kepentingan pribadi memengaruhi tugas',
      'Laporan diperiksa',
      'Layanan berdasarkan antrean',
      'Atasan memberi evaluasi',
    ],
    answer: 1,
    explanation: '17. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 18,
    question: 'Menggunakan fasilitas negara untuk urusan pribadi tanpa izin merupakan ...',
    options: [
      'Efisiensi',
      'Penyalahgunaan fasilitas negara',
      'Hak petugas',
      'Pelayanan',
      'Kegiatan sosial',
    ],
    answer: 1,
    explanation: '18. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 19,
    question: 'Dalam menjalankan tugas pemasyarakatan, HAM harus dipahami sebagai ...',
    options: [
      'Hal yang tetap dihormati sesuai hukum dan batasan yang sah',
      'Hak tanpa kewajiban',
      'Alasan mengabaikan keamanan',
      'Hal yang hanya berlaku bagi petugas',
      'Hambatan bagi disiplin',
    ],
    answer: 0,
    explanation: '19. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 20,
    question: 'Larangan perlakuan diskriminatif berarti ...',
    options: [
      'Semua diperlakukan berdasarkan aturan tanpa membedakan latar belakang',
      'Semua harus mendapat hasil yang sama',
      'Petugas boleh memilih yang disukai',
      'Kelompok tertentu selalu diprioritaskan',
      'Aturan boleh berbeda tanpa dasar',
    ],
    answer: 0,
    explanation: '20. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 21,
    question: 'Tujuan pembinaan yang baik adalah ...',
    options: [
      'Mendukung perubahan perilaku dan reintegrasi sosial sesuai aturan',
      'Membalas kesalahan',
      'Mengucilkan selamanya',
      'Menghilangkan hak belajar',
      'Membuat warga takut',
    ],
    answer: 0,
    explanation: '21. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 22,
    question: 'Sikap profesional terhadap warga binaan adalah ...',
    options: [
      'Tegas, manusiawi, konsisten, dan sesuai prosedur',
      'Kasar agar ditakuti',
      'Bebas membuat hukuman',
      'Membedakan berdasarkan kedekatan',
      'Mengabaikan keluhan',
    ],
    answer: 0,
    explanation: '22. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 23,
    question: 'Data pribadi warga binaan harus ...',
    options: [
      'Disebarluaskan',
      'Diakses dan disampaikan hanya sesuai kewenangan',
      'Dijadikan bahan candaan',
      'Dikirim ke grup pribadi',
      'Dipublikasikan tanpa dasar',
    ],
    answer: 1,
    explanation: '23. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 24,
    question: 'Jika keluarga meminta informasi rahasia tentang warga binaan, Anda ...',
    options: [
      'Memberikan karena keluarga',
      'Menolak dengan sopan dan mengarahkan ke prosedur resmi',
      'Memberikan sebagian',
      'Meminta imbalan',
      'Mengunggah tanpa nama',
    ],
    answer: 1,
    explanation: '24. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 25,
    question: 'Disiplin ditunjukkan dengan ...',
    options: [
      'Menaati jadwal dan prosedur meskipun tidak diawasi',
      'Mengikuti aturan yang disukai',
      'Datang saat diperiksa',
      'Mencari alasan',
      'Mengandalkan rekan',
    ],
    answer: 0,
    explanation: '25. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 26,
    question: 'Jika menerima instruksi yang jelas melanggar hukum, Anda ...',
    options: [
      'Langsung melaksanakan',
      'Memastikan instruksi dan memakai jalur resmi untuk menyampaikan keberatan',
      'Mengunggah tuduhan',
      'Mengajak teman menutupi',
      'Menolak dengan kasar',
    ],
    answer: 1,
    explanation: '26. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 27,
    question:
        'Keluarga warga binaan yang mengeluh sebaiknya dilayani dengan ...',
    options: [
      'Sopan, empatik, jelas, dan sesuai prosedur',
      'Marah agar cepat selesai',
      'Janji di luar kewenangan',
      'Perlakuan khusus berbayar',
      'Mengabaikannya',
    ],
    answer: 0,
    explanation: '27. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 28,
    question: 'Kalimat efektif yang tepat adalah ...',
    options: [
      'Para taruna-taruna wajib hadir.',
      'Taruna wajib hadir tepat waktu.',
      'Kepada taruna diwajibkan untuk hadir.',
      'Taruna wajib untuk dapat hadir.',
      'Para taruna semuanya wajib hadir.',
    ],
    answer: 1,
    explanation: '28. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 29,
    question: 'Kata baku yang tepat adalah ...',
    options: ['Resiko', 'Ijin', 'Analisa', 'Aktivitas', 'Praktek'],
    answer: 3,
    explanation: '29. Jawaban D',
  ),
  KedinasanTwkQuestion(
    number: 30,
    question: 'Jika terjadi ketegangan di antara warga binaan, tindakan awal yang tepat adalah ...',
    options: [
      'Memihak salah satu',
      'Menjaga keselamatan, memisahkan secara proporsional, dan mengikuti prosedur',
      'Membiarkan',
      'Menghukum semua tanpa pemeriksaan',
      'Merekam untuk media sosial',
    ],
    answer: 1,
    explanation: '30. Jawaban B',
  ),
];

const STMKGTwkQuestions = <KedinasanTwkQuestion>[
  KedinasanTwkQuestion(
    number: 1,
    question: 'Sikap yang sesuai sila ketiga ketika bekerja dengan orang dari berbagai daerah adalah ...',
    options: [
      'Mengutamakan kelompok asal',
      'Menghargai perbedaan dan mengutamakan tujuan bersama',
      'Menolak pendapat daerah lain',
      'Memaksakan kebiasaan sendiri',
      'Menghindari kerja sama',
    ],
    answer: 1,
    explanation: '1. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 2,
    question: 'Pengambilan keputusan untuk keselamatan masyarakat sebaiknya dilakukan dengan ...',
    options: [
      'Mengejar popularitas',
      'Musyawarah berdasarkan data dan tanggung jawab',
      'Mengikuti tekanan media sosial',
      'Mendahulukan kepentingan pribadi',
      'Mengabaikan pendapat ahli',
    ],
    answer: 1,
    explanation: '2. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 3,
    question: 'Menghormati korban bencana tanpa membedakan latar belakang merupakan pengamalan sila ...',
    options: ['Pertama', 'Kedua', 'Ketiga', 'Keempat', 'Kelima'],
    answer: 1,
    explanation: '3. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 4,
    question: 'UUD NRI Tahun 1945 berkedudukan sebagai ...',
    options: [
      'Hukum dasar tertulis negara',
      'Peraturan teknis lembaga',
      'Pedoman kelompok',
      'Kebiasaan daerah',
      'Aturan internal sekolah',
    ],
    answer: 0,
    explanation: '4. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 5,
    question: 'Prinsip negara hukum mengharuskan ...',
    options: [
      'Kekuasaan bebas dari hukum',
      'Tindakan pemerintah berdasarkan hukum',
      'Pejabat selalu benar',
      'Hukum hanya untuk warga biasa',
      'Keputusan tanpa dasar',
    ],
    answer: 1,
    explanation: '5. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 6,
    question: 'Salah satu tujuan negara dalam Pembukaan UUD 1945 adalah ...',
    options: [
      'Melindungi segenap bangsa Indonesia',
      'Menguasai negara lain',
      'Menghapus budaya daerah',
      'Membatasi pendidikan',
      'Mendahulukan golongan tertentu',
    ],
    answer: 0,
    explanation: '6. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 7,
    question: 'Bentuk negara Indonesia adalah ...',
    options: ['Serikat', 'Kesatuan', 'Monarki', 'Konfederasi', 'Protektorat'],
    answer: 1,
    explanation: '7. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 8,
    question: 'Sikap yang tepat terhadap potensi bencana di berbagai daerah adalah ...',
    options: [
      'Mementingkan daerah sendiri',
      'Mendukung koordinasi nasional dan solidaritas antardaerah',
      'Menolak bantuan daerah lain',
      'Menyebarkan kepanikan',
      'Menganggap bencana sebagai urusan pribadi',
    ],
    answer: 1,
    explanation: '8. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 9,
    question: 'Bhinneka Tunggal Ika berarti ...',
    options: [
      'Berbeda-beda tetapi tetap satu',
      'Semua harus seragam',
      'Perbedaan harus dihapus',
      'Mayoritas selalu benar',
      'Daerah boleh memisahkan diri',
    ],
    answer: 0,
    explanation: '9. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 10,
    question: 'Bela negara bagi taruna STMKG dapat diwujudkan dengan ...',
    options: [
      'Belajar disiplin, menaati hukum, dan mengabdi untuk keselamatan masyarakat',
      'Membocorkan data peringatan',
      'Mengabaikan prosedur',
      'Menyebarkan kabar belum pasti',
      'Mengutamakan popularitas',
    ],
    answer: 0,
    explanation: '10. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 11,
    question: 'Ketika menerima informasi cuaca ekstrem dari akun tidak resmi, Anda ...',
    options: [
      'Langsung menyebarkan',
      'Memeriksa sumber resmi dan tidak menyebarkan informasi yang belum terverifikasi',
      'Menambahkan prediksi sendiri',
      'Menyalahkan lembaga',
      'Menghapus semua informasi',
    ],
    answer: 1,
    explanation: '11. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 12,
    question: 'Kontribusi ilmu meteorologi, klimatologi, dan geofisika bagi negara terutama berkaitan dengan ...',
    options: [
      'Meningkatkan keselamatan dan ketahanan masyarakat berdasarkan informasi ilmiah',
      'Mencari keuntungan pribadi',
      'Membatasi komunikasi warga',
      'Menggantikan semua keputusan pemerintah',
      'Menyebarkan ramalan tanpa dasar',
    ],
    answer: 0,
    explanation: '12. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 13,
    question: 'Integritas berarti ...',
    options: [
      'Kesesuaian nilai, ucapan, dan tindakan',
      'Kemampuan menyembunyikan kesalahan',
      'Ketaatan hanya saat diawasi',
      'Keberanian melanggar aturan',
      'Kemampuan mencari keuntungan',
    ],
    answer: 0,
    explanation: '13. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 14,
    question: 'Jika menemukan kesalahan pada data pengamatan, tindakan yang tepat adalah ...',
    options: [
      'Mengubah tanpa catatan',
      'Membiarkan',
      'Memeriksa, mencatat, dan melaporkan sesuai prosedur',
      'Menghapus data',
      'Menyalahkan rekan',
    ],
    answer: 2,
    explanation: '14. Jawaban C',
  ),
  KedinasanTwkQuestion(
    number: 15,
    question: 'Jika diminta mengubah hasil laporan agar terlihat lebih baik, Anda ...',
    options: [
      'Mengikuti demi atasan',
      'Menolak dan menyampaikan melalui jalur resmi',
      'Mengubah sedikit saja',
      'Menyimpan dua versi rahasia',
      'Menghapus bukti',
    ],
    answer: 1,
    explanation: '15. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 16,
    question:
        'Jika ditawari uang agar laporan layanan diprioritaskan, Anda ...',
    options: [
      'Menerima sedikit',
      'Menolak dan melaporkan melalui mekanisme yang tepat',
      'Menerima jika tidak ada saksi',
      'Membagi dengan tim',
      'Meminta hadiah lain',
    ],
    answer: 1,
    explanation: '16. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 17,
    question: 'Konflik kepentingan terjadi ketika ...',
    options: [
      'Keputusan berdasarkan data',
      'Kepentingan pribadi atau hubungan dekat memengaruhi tugas',
      'Laporan diperiksa',
      'Prosedur dipatuhi',
      'Petugas bekerja dalam tim',
    ],
    answer: 1,
    explanation: '17. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 18,
    question: 'Menggunakan fasilitas negara untuk kepentingan pribadi tanpa izin merupakan ...',
    options: [
      'Efisiensi',
      'Penyalahgunaan fasilitas negara',
      'Hak pegawai',
      'Bentuk pelayanan',
      'Kegiatan sosial',
    ],
    answer: 1,
    explanation: '18. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 19,
    question:
        'Informasi peringatan bencana kepada masyarakat harus disampaikan ...',
    options: [
      'Secara sensasional',
      'Akurat, jelas, tepat waktu, dan melalui kanal resmi',
      'Setelah viral',
      'Dengan istilah yang membingungkan',
      'Hanya kepada teman',
    ],
    answer: 1,
    explanation: '19. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 20,
    question: 'Kerahasiaan data tidak boleh dijadikan alasan untuk ...',
    options: [
      'Melindungi data pribadi',
      'Membatasi akses sesuai kewenangan',
      'Menutupi kesalahan atau pelanggaran',
      'Mengikuti aturan keamanan',
      'Mencegah penyalahgunaan',
    ],
    answer: 2,
    explanation: '20. Jawaban C',
  ),
  KedinasanTwkQuestion(
    number: 21,
    question:
        'Jika menerima tautan yang meminta kata sandi akun kedinasan, Anda ...',
    options: [
      'Mengisi segera',
      'Meneruskan ke teman',
      'Tidak mengisi, memeriksa sumber, dan melaporkan sebagai dugaan penipuan',
      'Membalas dengan data palsu',
      'Mengunggah tautan',
    ],
    answer: 2,
    explanation: '21. Jawaban C',
  ),
  KedinasanTwkQuestion(
    number: 22,
    question:
        'Pelayanan informasi kepada warga yang terdampak bencana harus ...',
    options: [
      'Membedakan warga berdasarkan status',
      'Cepat, empatik, jelas, dan tidak diskriminatif',
      'Menunggu imbalan',
      'Menggunakan rumor',
      'Menutup semua informasi',
    ],
    answer: 1,
    explanation: '22. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 23,
    question: 'Jika warga panik akibat informasi cuaca yang berbeda-beda, petugas sebaiknya ...',
    options: [
      'Menyalahkan warga',
      'Menjelaskan sumber resmi dan langkah keselamatan dengan bahasa sederhana',
      'Membiarkan kepanikan',
      'Menyebarkan informasi tambahan tanpa cek',
      'Menolak pertanyaan',
    ],
    answer: 1,
    explanation: '23. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 24,
    question: 'Sikap terhadap perbedaan agama, suku, dan budaya adalah ...',
    options: [
      'Menghormati perbedaan dan menjaga persatuan',
      'Memaksakan kebiasaan sendiri',
      'Menyebarkan stereotip',
      'Menilai kesetiaan dari asal daerah',
      'Menghindari semua yang berbeda',
    ],
    answer: 0,
    explanation: '24. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 25,
    question: 'Gotong royong dalam penanganan bencana menunjukkan ...',
    options: [
      'Individualisme',
      'Solidaritas dan tanggung jawab sosial',
      'Persaingan daerah',
      'Ketergantungan tanpa rencana',
      'Penolakan koordinasi',
    ],
    answer: 1,
    explanation: '25. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 26,
    question: 'Sikap disiplin taruna ditunjukkan dengan ...',
    options: [
      'Menaati jadwal dan prosedur meskipun tidak diawasi',
      'Mengikuti aturan yang disukai saja',
      'Datang saat diperiksa',
      'Mengandalkan teman',
      'Mencari alasan',
    ],
    answer: 0,
    explanation: '26. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 27,
    question: 'Jika mendapat kritik atas kesalahan analisis, Anda ...',
    options: [
      'Membantah',
      'Mendengarkan, memeriksa ulang, dan memperbaiki',
      'Menyalahkan alat',
      'Menghapus hasil',
      'Menyebarkan keluhan',
    ],
    answer: 1,
    explanation: '27. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 28,
    question: 'Jika senior meminta Anda menyebarkan informasi yang belum terverifikasi, Anda ...',
    options: [
      'Langsung menyebarkan',
      'Menolak dengan sopan dan meminta verifikasi atau arahan resmi',
      'Menyebarkan secara anonim',
      'Mengubah isi',
      'Mengirim ke semua grup',
    ],
    answer: 1,
    explanation: '28. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 29,
    question: 'Kalimat yang paling efektif adalah ...',
    options: [
      'Para taruna-taruna wajib hadir.',
      'Taruna wajib hadir tepat waktu.',
      'Kepada taruna diwajibkan untuk hadir.',
      'Taruna wajib untuk dapat hadir.',
      'Para taruna semuanya wajib hadir.',
    ],
    answer: 1,
    explanation: '29. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 30,
    question: 'Kata baku yang tepat adalah ...',
    options: ['Resiko', 'Ijin', 'Analisa', 'Aktivitas', 'Praktek'],
    answer: 3,
    explanation: '30. Jawaban D',
  ),
];

const IPDNTwkQuestions = <KedinasanTwkQuestion>[
  KedinasanTwkQuestion(
    number: 1,
    question: 'Dalam melayani warga dari berbagai latar belakang, calon praja harus ...',
    options: [
      'Mendahulukan warga yang dikenal',
      'Melayani adil tanpa membedakan suku, agama, atau status sosial',
      'Mengutamakan kelompok mayoritas',
      'Menolak kritik warga',
      'Memberi layanan berdasarkan imbalan',
    ],
    answer: 1,
    explanation: '1. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 2,
    question:
        'Sikap yang sesuai sila ketiga dalam kehidupan pemerintahan adalah ...',
    options: [
      'Mengutamakan kepentingan daerah sendiri',
      'Menjaga persatuan dan mendahulukan kepentingan nasional',
      'Menolak koordinasi antardaerah',
      'Menghapus keragaman',
      'Mengikuti kepentingan kelompok',
    ],
    answer: 1,
    explanation: '2. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 3,
    question:
        'Musyawarah dalam penyelenggaraan pemerintahan bertujuan untuk ...',
    options: [
      'Membenarkan keputusan pemimpin',
      'Mencapai keputusan bijaksana dan dapat dipertanggungjawabkan',
      'Menghindari semua perbedaan',
      'Membungkam kelompok kecil',
      'Mempercepat keputusan tanpa data',
    ],
    answer: 1,
    explanation: '3. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 4,
    question: 'UUD NRI Tahun 1945 berkedudukan sebagai ...',
    options: [
      'Hukum dasar tertulis negara',
      'Peraturan teknis daerah',
      'Pedoman organisasi',
      'Kebiasaan masyarakat',
      'Aturan internal kampus',
    ],
    answer: 0,
    explanation: '4. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 5,
    question: 'Prinsip negara hukum mengandung makna bahwa ...',
    options: [
      'Kekuasaan berada di atas hukum',
      'Penyelenggaraan negara harus berdasarkan hukum',
      'Hukum hanya untuk rakyat',
      'Pejabat bebas dari aturan',
      'Keputusan boleh tanpa dasar',
    ],
    answer: 1,
    explanation: '5. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 6,
    question: 'Salah satu tujuan negara dalam Pembukaan UUD 1945 ialah ...',
    options: [
      'Melindungi segenap bangsa Indonesia',
      'Menguasai negara lain',
      'Membatasi hak warga',
      'Menghapus budaya daerah',
      'Mendahulukan kelompok tertentu',
    ],
    answer: 0,
    explanation: '6. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 7,
    question: 'Bentuk negara Indonesia adalah ...',
    options: ['Federasi', 'Kesatuan', 'Monarki', 'Konfederasi', 'Protektorat'],
    answer: 1,
    explanation: '7. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 8,
    question: 'Otonomi daerah dalam NKRI seharusnya dipahami sebagai ...',
    options: [
      'Kebebasan memisahkan diri',
      'Pengaturan urusan daerah dalam kerangka negara kesatuan',
      'Hak menolak hukum nasional',
      'Kekuasaan tanpa pengawasan',
      'Penghapusan koordinasi pusat',
    ],
    answer: 1,
    explanation: '8. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 9,
    question: 'Sikap yang tepat terhadap isu putra daerah dan kepentingan nasional adalah ...',
    options: [
      'Mengutamakan asal daerah dalam semua keputusan',
      'Menghargai kearifan lokal sambil menjaga persatuan dan kepentingan nasional',
      'Menolak warga dari daerah lain',
      'Membatasi mobilitas warga',
      'Menganggap daerah lain sebagai pesaing',
    ],
    answer: 1,
    explanation: '9. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 10,
    question: 'Contoh bela negara bagi calon praja IPDN adalah ...',
    options: [
      'Belajar disiplin, menaati hukum, dan siap mengabdi di masyarakat',
      'Menyebarkan informasi provokatif',
      'Membela kesalahan atasan',
      'Menghindari tugas daerah',
      'Mengutamakan fasilitas pribadi',
    ],
    answer: 0,
    explanation: '10. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 11,
    question: 'Ketika melihat berita provokatif tentang konflik antardaerah, tindakan yang tepat adalah ...',
    options: [
      'Langsung menyebarkannya',
      'Memeriksa fakta dan tidak menyebarkan informasi yang belum terbukti',
      'Mengajak kelompok sendiri membalas',
      'Menambahkan komentar kasar',
      'Menentukan pihak yang salah tanpa data',
    ],
    answer: 1,
    explanation: '11. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 12,
    question: 'Ancaman terhadap persatuan yang perlu diwaspadai dalam pemerintahan daerah adalah ...',
    options: [
      'Gotong royong',
      'Disinformasi, intoleransi, dan politik identitas yang memecah belah',
      'Musyawarah',
      'Pelayanan terpadu',
      'Kerja sama antardaerah',
    ],
    answer: 1,
    explanation: '12. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 13,
    question: 'Integritas seorang aparatur berarti ...',
    options: [
      'Kesesuaian antara nilai, ucapan, dan tindakan',
      'Kemampuan mencari keuntungan',
      'Ketaatan hanya ketika diawasi',
      'Keberanian melanggar aturan',
      'Kemampuan menutupi kesalahan',
    ],
    answer: 0,
    explanation: '13. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 14,
    question: 'Jika menemukan kesalahan dalam laporan kegiatan, Anda ...',
    options: [
      'Mengubah angka tanpa catatan',
      'Membiarkan agar tidak repot',
      'Memeriksa bukti, melaporkan, dan memperbaiki sesuai prosedur',
      'Menyalahkan anggota lain',
      'Menghapus laporan',
    ],
    answer: 2,
    explanation: '14. Jawaban C',
  ),
  KedinasanTwkQuestion(
    number: 15,
    question: 'Jika keluarga meminta prioritas layanan karena Anda bertugas di pemerintahan, Anda ...',
    options: [
      'Memenuhi karena keluarga',
      'Meminta imbalan',
      'Menjelaskan bahwa layanan harus mengikuti prosedur yang sama',
      'Meminta rekan memproses diam-diam',
      'Menunda semua layanan',
    ],
    answer: 2,
    explanation: '15. Jawaban C',
  ),
  KedinasanTwkQuestion(
    number: 16,
    question: 'Jika ditawari uang untuk mempercepat layanan, sikap yang benar adalah ...',
    options: [
      'Menerima sedikit',
      'Menolak dan melaporkan melalui saluran yang tepat',
      'Menerima jika tidak ada saksi',
      'Membagi dengan tim',
      'Meminta hadiah dalam bentuk lain',
    ],
    answer: 1,
    explanation: '16. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 17,
    question: 'Konflik kepentingan terjadi apabila ...',
    options: [
      'Keputusan berdasarkan aturan',
      'Hubungan pribadi atau kepentingan pribadi dapat memengaruhi keputusan tugas',
      'Layanan dilakukan sesuai antrean',
      'Atasan melakukan pemeriksaan',
      'Data dicatat lengkap',
    ],
    answer: 1,
    explanation: '17. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 18,
    question: 'Penggunaan kendaraan atau fasilitas pemerintah untuk urusan pribadi tanpa izin merupakan ...',
    options: [
      'Contoh efisiensi',
      'Penyalahgunaan fasilitas negara',
      'Bentuk pelayanan',
      'Kewajiban aparatur',
      'Hak keluarga',
    ],
    answer: 1,
    explanation: '18. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 19,
    question: 'Pelayanan publik yang baik memiliki ciri ...',
    options: [
      'Cepat untuk kenalan saja',
      'Adil, transparan, mudah diakses, dan tidak diskriminatif',
      'Bergantung pada hadiah',
      'Prosedurnya dirahasiakan',
      'Mengutamakan pejabat',
    ],
    answer: 1,
    explanation: '19. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 20,
    question: 'Jika warga marah karena tidak memahami prosedur, petugas sebaiknya ...',
    options: [
      'Membalas dengan marah',
      'Mendengarkan, menjelaskan dengan bahasa sederhana, dan memberi solusi sesuai kewenangan',
      'Menyuruh pulang',
      'Mendahulukan warga lain',
      'Meminta biaya tambahan',
    ],
    answer: 1,
    explanation: '20. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 21,
    question:
        'Hubungan pemerintah pusat dan daerah yang sehat dibangun melalui ...',
    options: [
      'Koordinasi, pembagian kewenangan, dan kepatuhan pada hukum',
      'Persaingan tanpa aturan',
      'Penolakan kebijakan nasional',
      'Kekuasaan tanpa pengawasan',
      'Komunikasi hanya saat konflik',
    ],
    answer: 0,
    explanation: '21. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 22,
    question: 'Kepentingan masyarakat dalam kebijakan daerah dapat diketahui dengan baik melalui ...',
    options: [
      'Data, partisipasi masyarakat, dan kajian yang objektif',
      'Rumor media sosial',
      'Pendapat satu tokoh',
      'Kepentingan pribadi pejabat',
      'Tekanan kelompok tertentu',
    ],
    answer: 0,
    explanation: '22. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 23,
    question: 'Jika kebijakan daerah berdampak berbeda pada kelompok masyarakat, langkah yang tepat adalah ...',
    options: [
      'Mengabaikan kelompok kecil',
      'Mengkaji dampak dan memastikan perlakuan adil sesuai hukum',
      'Menyalahkan warga',
      'Membatalkan tanpa kajian',
      'Mendahulukan kelompok kuat',
    ],
    answer: 1,
    explanation: '23. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 24,
    question: 'Sikap disiplin calon praja ditunjukkan dengan ...',
    options: [
      'Menaati jadwal dan aturan meskipun tidak diawasi',
      'Mengikuti aturan yang disukai saja',
      'Datang jika ada pemeriksaan',
      'Mengandalkan teman',
      'Membuat alasan saat terlambat',
    ],
    answer: 0,
    explanation: '24. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 25,
    question:
        'Jika mendapat kritik dari senior atau atasan, Anda sebaiknya ...',
    options: [
      'Membantah langsung',
      'Mendengarkan, mengevaluasi, dan memperbaiki diri',
      'Menyebarkan keluhan',
      'Menghindari tugas',
      'Menyalahkan rekan',
    ],
    answer: 1,
    explanation: '25. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 26,
    question: 'Netralitas aparatur dalam kehidupan politik berarti ...',
    options: [
      'Menggunakan jabatan untuk mendukung calon tertentu',
      'Tidak memihak dan tetap menjalankan tugas sesuai hukum',
      'Menyuruh warga memilih tertentu',
      'Menyebarkan propaganda',
      'Menolak semua kegiatan masyarakat',
    ],
    answer: 1,
    explanation: '26. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 27,
    question: 'Kerahasiaan data masyarakat harus dijaga karena ...',
    options: [
      'Data dapat digunakan tanpa batas',
      'Pembukaan data tanpa kewenangan dapat merugikan dan melanggar hak warga',
      'Semua informasi harus dirahasiakan',
      'Petugas bebas mengumpulkan data',
      'Data tidak memiliki nilai',
    ],
    answer: 1,
    explanation: '27. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 28,
    question: 'Kalimat yang paling efektif adalah ...',
    options: [
      'Para praja-praja wajib hadir.',
      'Praja wajib hadir tepat waktu.',
      'Kepada praja diwajibkan untuk hadir.',
      'Praja wajib untuk dapat hadir.',
      'Para praja semuanya wajib hadir.',
    ],
    answer: 1,
    explanation: '28. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 29,
    question: 'Kata baku yang tepat adalah ...',
    options: ['Resiko', 'Ijin', 'Analisa', 'Aktivitas', 'Praktek'],
    answer: 3,
    explanation: '29. Jawaban D',
  ),
  KedinasanTwkQuestion(
    number: 30,
    question: 'Jika terjadi konflik antarwarga di wilayah tugas, calon aparatur sebaiknya ...',
    options: [
      'Memihak kelompok yang paling banyak',
      'Menjaga ketenangan, mendengar pihak terkait, dan bertindak sesuai hukum',
      'Menyebarkan identitas pihak',
      'Membiarkan konflik',
      'Mengambil keputusan tanpa informasi',
    ],
    answer: 1,
    explanation: '30. Jawaban B',
  ),
];

const PoltekSSNTwkQuestions = <KedinasanTwkQuestion>[
  KedinasanTwkQuestion(
    number: 1,
    question: 'Sikap yang sesuai dengan sila ketiga saat bekerja dalam tim yang berbeda daerah adalah ...',
    options: [
      'Mendahulukan kelompok asal',
      'Menghargai perbedaan dan mengutamakan tujuan bersama',
      'Menolak pendapat daerah lain',
      'Memaksakan kebiasaan sendiri',
      'Menghindari kerja sama',
    ],
    answer: 1,
    explanation: '1. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 2,
    question: 'Penggunaan teknologi untuk kepentingan negara harus tetap berpedoman pada ...',
    options: [
      'Keuntungan pribadi',
      'Pancasila dan etika kemanusiaan',
      'Popularitas',
      'Kecepatan tanpa aturan',
      'Kepentingan kelompok',
    ],
    answer: 1,
    explanation: '2. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 3,
    question: 'Musyawarah yang baik ditandai oleh ...',
    options: [
      'Mendengar alasan dan mengambil keputusan bertanggung jawab',
      'Memaksa pendapat ketua',
      'Membungkam perbedaan',
      'Mengikuti teman terdekat',
      'Menghindari keputusan',
    ],
    answer: 0,
    explanation: '3. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 4,
    question: 'UUD NRI Tahun 1945 merupakan ...',
    options: [
      'Hukum dasar tertulis negara',
      'Peraturan teknis kampus',
      'Pedoman satu instansi',
      'Kebiasaan masyarakat',
      'Peraturan daerah',
    ],
    answer: 0,
    explanation: '4. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 5,
    question: 'Persamaan kedudukan di hadapan hukum berarti ...',
    options: [
      'Hukum berlaku tanpa diskriminasi',
      'Pejabat tidak dapat diperiksa',
      'Orang kaya mendapat pengecualian',
      'Keluarga petugas diprioritaskan',
      'Hukum hanya berlaku bagi masyarakat biasa',
    ],
    answer: 0,
    explanation: '5. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 6,
    question: 'Salah satu tujuan negara dalam Pembukaan UUD 1945 adalah ...',
    options: [
      'Melindungi segenap bangsa Indonesia',
      'Menguasai negara lain',
      'Menghapus budaya daerah',
      'Membatasi pendidikan',
      'Mengutamakan satu golongan',
    ],
    answer: 0,
    explanation: '6. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 7,
    question: 'Bentuk negara Indonesia adalah ...',
    options: ['Serikat', 'Kesatuan', 'Monarki', 'Konfederasi', 'Protektorat'],
    answer: 1,
    explanation: '7. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 8,
    question: 'Ancaman nonmiliter yang dapat mengganggu persatuan adalah ...',
    options: [
      'Gotong royong',
      'Disinformasi dan ujaran kebencian',
      'Toleransi',
      'Musyawarah',
      'Kerja bakti',
    ],
    answer: 1,
    explanation: '8. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 9,
    question: 'Makna Bhinneka Tunggal Ika adalah ...',
    options: [
      'Berbeda-beda tetapi tetap satu',
      'Semua harus seragam',
      'Perbedaan harus dihapus',
      'Mayoritas selalu benar',
      'Daerah berdiri sendiri',
    ],
    answer: 0,
    explanation: '9. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 10,
    question:
        'Bela negara bagi calon taruna Poltek SSN dapat diwujudkan dengan ...',
    options: [
      'Belajar disiplin, menaati hukum, menjaga integritas, dan siap mengabdi',
      'Membocorkan data',
      'Mengikuti semua ajakan',
      'Menolak evaluasi',
      'Mengutamakan popularitas',
    ],
    answer: 0,
    explanation: '10. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 11,
    question: 'Jika menerima berita tentang serangan siber dari sumber tidak jelas, Anda ...',
    options: [
      'Langsung menyebarkan',
      'Memeriksa sumber resmi dan tidak menyebarkan informasi yang belum terverifikasi',
      'Mengubah judul agar viral',
      'Membuat kesimpulan sendiri',
      'Menyalahkan kelompok tertentu',
    ],
    answer: 1,
    explanation: '11. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 12,
    question: 'Kecintaan kepada tanah air yang sehat ditunjukkan dengan ...',
    options: [
      'Membela kesalahan bangsa sendiri',
      'Berkontribusi memperbaiki keadaan dan menaati hukum',
      'Menolak semua kritik',
      'Membenci bangsa lain',
      'Mengutamakan diri sendiri',
    ],
    answer: 1,
    explanation: '12. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 13,
    question: 'Integritas berarti ...',
    options: [
      'Kesesuaian nilai, ucapan, dan tindakan',
      'Kemampuan menyembunyikan kesalahan',
      'Keberanian melanggar aturan',
      'Kepandaian mencari keuntungan',
      'Kemampuan menyenangkan semua pihak',
    ],
    answer: 0,
    explanation: '13. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 14,
    question: 'Jika menemukan dokumen berisi data pribadi peserta, Anda ...',
    options: [
      'Memotretnya',
      'Mengirim ke grup',
      'Menyerahkan kepada petugas berwenang dan menjaga kerahasiaan',
      'Mengunggahnya',
      'Membaca lalu membuangnya',
    ],
    answer: 2,
    explanation: '14. Jawaban C',
  ),
  KedinasanTwkQuestion(
    number: 15,
    question: 'Jika ditawari uang untuk memengaruhi hasil seleksi, Anda ...',
    options: [
      'Menerima sedikit',
      'Menolak dan melaporkan melalui mekanisme resmi',
      'Menerima lalu membagi',
      'Meminta waktu',
      'Menerima jika tidak ada saksi',
    ],
    answer: 1,
    explanation: '15. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 16,
    question: 'Ketika melakukan kesalahan, tindakan terbaik adalah ...',
    options: [
      'Menyalahkan keadaan',
      'Menghapus bukti',
      'Mengakui, memperbaiki, dan mencegah pengulangan',
      'Menunggu dilupakan',
      'Membuat alasan',
    ],
    answer: 2,
    explanation: '16. Jawaban C',
  ),
  KedinasanTwkQuestion(
    number: 17,
    question: 'Konflik kepentingan terjadi apabila ...',
    options: [
      'Keputusan berdasarkan aturan',
      'Kepentingan pribadi memengaruhi keputusan tugas',
      'Laporan diperiksa',
      'Pelayanan sesuai antrean',
      'Petugas berdiskusi',
    ],
    answer: 1,
    explanation: '17. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 18,
    question: 'Perilaku antikorupsi yang tepat adalah ...',
    options: [
      'Membiarkan pelanggaran kecil',
      'Menolak suap dan melaporkan dugaan pelanggaran secara benar',
      'Memberi uang pelicin',
      'Menutup laporan',
      'Memakai fasilitas untuk kepentingan pribadi',
    ],
    answer: 1,
    explanation: '18. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 19,
    question: 'Kata sandi dan kode OTP seharusnya ...',
    options: [
      'Dibagikan kepada teman dekat',
      'Diberikan jika mengaku petugas',
      'Dirahasiakan dan tidak diberikan kepada pihak lain',
      'Ditulis di media sosial',
      'Dipakai bersama',
    ],
    answer: 2,
    explanation: '19. Jawaban C',
  ),
  KedinasanTwkQuestion(
    number: 20,
    question: 'Mengunggah foto dokumen atau ruang seleksi ke media sosial berisiko karena ...',
    options: [
      'Membuat akun terkenal',
      'Dapat membuka data pribadi atau informasi yang tidak semestinya tersebar',
      'Selalu membantu panitia',
      'Tidak berdampak',
      'Meningkatkan nilai ujian',
    ],
    answer: 1,
    explanation: '20. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 21,
    question:
        'Jika menerima tautan mencurigakan yang meminta data pribadi, Anda ...',
    options: [
      'Mengklik segera',
      'Meneruskan ke grup',
      'Tidak mengisi data, memeriksa sumber, dan melaporkan jika perlu',
      'Membalas dengan data palsu',
      'Mengunggah tautannya',
    ],
    answer: 2,
    explanation: '21. Jawaban C',
  ),
  KedinasanTwkQuestion(
    number: 22,
    question: 'Kerahasiaan informasi tidak boleh digunakan untuk ...',
    options: [
      'Melindungi data pribadi',
      'Membatasi akses sesuai kewenangan',
      'Menutupi pelanggaran atau kejahatan',
      'Mencegah kebocoran',
      'Menjaga kepentingan negara',
    ],
    answer: 2,
    explanation: '22. Jawaban C',
  ),
  KedinasanTwkQuestion(
    number: 23,
    question: 'Jika menerima instruksi yang jelas bertentangan dengan hukum, Anda ...',
    options: [
      'Langsung melaksanakan',
      'Memastikan instruksi dan menggunakan jalur resmi untuk menyampaikan keberatan',
      'Mengunggah tuduhan',
      'Mengajak teman menutupi',
      'Menolak dengan kasar',
    ],
    answer: 1,
    explanation: '23. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 24,
    question: 'Sikap profesional berarti ...',
    options: [
      'Bekerja berdasarkan kompetensi, aturan, etika, dan tanggung jawab',
      'Mengejar popularitas',
      'Mengikuti semua perintah',
      'Mendahulukan relasi',
      'Menghindari evaluasi',
    ],
    answer: 0,
    explanation: '24. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 25,
    question: 'Sikap terhadap perbedaan agama, suku, dan budaya adalah ...',
    options: [
      'Menghormati perbedaan dan menjaga persatuan',
      'Memaksakan kebiasaan sendiri',
      'Menilai kesetiaan dari asal daerah',
      'Menghindari semua yang berbeda',
      'Menyebarkan stereotip',
    ],
    answer: 0,
    explanation: '25. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 26,
    question: 'Pelayanan publik yang baik harus ...',
    options: [
      'Mendahulukan kenalan',
      'Adil, transparan, sopan, dan tidak diskriminatif',
      'Bergantung imbalan',
      'Menutup prosedur',
      'Mengabaikan warga',
    ],
    answer: 1,
    explanation: '26. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 27,
    question: 'Kalimat efektif yang tepat adalah ...',
    options: [
      'Para peserta-peserta wajib hadir.',
      'Peserta wajib hadir tepat waktu.',
      'Kepada peserta diwajibkan untuk hadir.',
      'Peserta wajib untuk dapat hadir.',
      'Para peserta semuanya wajib hadir.',
    ],
    answer: 1,
    explanation: '27. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 28,
    question: 'Kata baku yang tepat adalah ...',
    options: ['Resiko', 'Ijin', 'Analisa', 'Aktivitas', 'Praktek'],
    answer: 3,
    explanation: '28. Jawaban D',
  ),
  KedinasanTwkQuestion(
    number: 29,
    question: 'Jika teman meminta data internal yang bukan haknya, Anda ...',
    options: [
      'Memberikan karena teman',
      'Memberikan sebagian',
      'Menolak dengan sopan dan mengarahkan ke jalur resmi',
      'Meminta imbalan',
      'Mengunggah tanpa nama',
    ],
    answer: 2,
    explanation: '29. Jawaban C',
  ),
  KedinasanTwkQuestion(
    number: 30,
    question: 'Jika terjadi perbedaan pendapat dalam tim, tindakan terbaik adalah ...',
    options: [
      'Meninggalkan tim',
      'Mendengar semua pihak dan mencari titik temu',
      'Memaksakan pendapat senior',
      'Menyebarkan konflik',
      'Menuduh pihak lain tidak nasionalis',
    ],
    answer: 1,
    explanation: '30. Jawaban B',
  ),
];

const PKNSTANTwkQuestions = <KedinasanTwkQuestion>[
  KedinasanTwkQuestion(
    number: 1,
    question: 'Sikap yang sesuai dengan sila kelima dalam pengelolaan anggaran negara adalah ...',
    options: [
      'Membagi anggaran berdasarkan kedekatan',
      'Menggunakan anggaran secara adil, transparan, dan sesuai kebutuhan masyarakat',
      'Mendahulukan kelompok sendiri',
      'Menyembunyikan laporan',
      'Memberi fasilitas khusus tanpa dasar',
    ],
    answer: 1,
    explanation: '1. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 2,
    question: 'Dalam rapat organisasi, pengambilan keputusan sebaiknya dilakukan dengan ...',
    options: [
      'Tekanan senior',
      'Musyawarah dan pertimbangan kepentingan bersama',
      'Pemungutan suara tanpa diskusi',
      'Keputusan orang yang paling kaya',
      'Mengikuti pendapat teman dekat',
    ],
    answer: 1,
    explanation: '2. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 3,
    question: 'Menghormati pemeluk agama lain dalam lingkungan pendidikan merupakan pengamalan sila ...',
    options: ['Pertama', 'Kedua', 'Ketiga', 'Keempat', 'Kelima'],
    answer: 0,
    explanation: '3. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 4,
    question: 'UUD NRI Tahun 1945 berfungsi sebagai ...',
    options: [
      'Hukum dasar tertulis negara',
      'Peraturan sekolah',
      'Pedoman satu kelompok',
      'Kebiasaan daerah',
      'Peraturan teknis kantor',
    ],
    answer: 0,
    explanation: '4. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 5,
    question: 'Persamaan kedudukan warga negara di hadapan hukum berarti ...',
    options: [
      'Pejabat bebas dari hukum',
      'Hukum berlaku tanpa diskriminasi',
      'Orang kaya mendapat prioritas',
      'Hukum hanya berlaku bagi pelajar',
      'Keluarga petugas mendapat pengecualian',
    ],
    answer: 1,
    explanation: '5. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 6,
    question: 'Salah satu tujuan negara dalam Pembukaan UUD 1945 adalah ...',
    options: [
      'Melindungi segenap bangsa Indonesia',
      'Menguasai perekonomian negara lain',
      'Membatasi pendidikan',
      'Menghapus budaya daerah',
      'Mengutamakan satu golongan',
    ],
    answer: 0,
    explanation: '6. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 7,
    question: 'Bentuk negara Indonesia adalah ...',
    options: ['Serikat', 'Kesatuan', 'Monarki', 'Konfederasi', 'Protektorat'],
    answer: 1,
    explanation: '7. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 8,
    question: 'Sikap yang tepat terhadap kepentingan daerah dan kepentingan nasional adalah ...',
    options: [
      'Selalu memilih kepentingan daerah',
      'Mengutamakan kepentingan nasional tanpa mengabaikan kebutuhan daerah',
      'Menghapus otonomi daerah',
      'Membiarkan daerah berjalan sendiri',
      'Menolak koordinasi pusat dan daerah',
    ],
    answer: 1,
    explanation: '8. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 9,
    question: 'Bhinneka Tunggal Ika mengajarkan bahwa ...',
    options: [
      'Perbedaan harus dihilangkan',
      'Berbeda-beda tetapi tetap satu',
      'Satu daerah lebih tinggi',
      'Budaya harus seragam',
      'Kelompok mayoritas selalu benar',
    ],
    answer: 1,
    explanation: '9. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 10,
    question: 'Contoh bela negara bagi mahasiswa PKN STAN adalah ...',
    options: [
      'Belajar disiplin, menaati aturan, menjaga integritas, dan siap mengabdi',
      'Menyebarkan data kedinasan',
      'Menghindari kewajiban sosial',
      'Membela kesalahan teman',
      'Menolak kritik',
    ],
    answer: 0,
    explanation: '10. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 11,
    question: 'Ketika menerima berita tentang kebijakan fiskal dari sumber tidak jelas, tindakan tepat adalah ...',
    options: [
      'Langsung menyebarkan',
      'Memeriksa sumber resmi sebelum mempercayai atau menyebarkan',
      'Mengubah judul agar menarik',
      'Menyalahkan pemerintah',
      'Membagikan ke semua grup',
    ],
    answer: 1,
    explanation: '11. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 12,
    question: 'Sikap cinta tanah air yang sehat adalah ...',
    options: [
      'Menganggap bangsa sendiri selalu benar',
      'Berkontribusi memperbaiki pelayanan dan menaati hukum',
      'Menolak semua kritik',
      'Membenci bangsa lain',
      'Mendahulukan keuntungan pribadi',
    ],
    answer: 1,
    explanation: '12. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 13,
    question: 'Integritas dalam pengelolaan keuangan negara berarti ...',
    options: [
      'Mencari celah untuk keuntungan pribadi',
      'Jujur, taat aturan, dan dapat mempertanggungjawabkan penggunaan dana',
      'Menyembunyikan kesalahan',
      'Mengikuti perintah yang melanggar hukum',
      'Mendahulukan keluarga',
    ],
    answer: 1,
    explanation: '13. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 14,
    question:
        'Jika menemukan selisih pencatatan uang kegiatan, Anda sebaiknya ...',
    options: [
      'Mengubah catatan agar seimbang',
      'Membiarkannya',
      'Memeriksa bukti, melaporkan, dan memperbaiki melalui prosedur',
      'Menutupinya demi nama baik',
      'Meminta teman bertanggung jawab',
    ],
    answer: 2,
    explanation: '14. Jawaban C',
  ),
  KedinasanTwkQuestion(
    number: 15,
    question: 'Jika ditawari uang untuk meloloskan dokumen yang tidak lengkap, Anda ...',
    options: [
      'Menerima sedikit',
      'Menolak dan melaporkan sesuai mekanisme',
      'Menerima lalu membagi',
      'Meminta waktu mencari saksi',
      'Membantu jika pemohon teman',
    ],
    answer: 1,
    explanation: '15. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 16,
    question: 'Pemberian hadiah dari pihak yang sedang dilayani perlu diwaspadai karena ...',
    options: [
      'Selalu meningkatkan kinerja',
      'Dapat menimbulkan konflik kepentingan atau gratifikasi',
      'Tidak pernah berpengaruh',
      'Wajib diterima',
      'Merupakan hak petugas',
    ],
    answer: 1,
    explanation: '16. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 17,
    question: 'Perilaku yang paling mencerminkan antikorupsi adalah ...',
    options: [
      'Menggunakan fasilitas kantor untuk kepentingan pribadi',
      'Menolak suap dan melaporkan dugaan pelanggaran melalui jalur resmi',
      'Membiarkan pelanggaran kecil',
      'Memberi uang pelicin agar cepat',
      'Menutup akses informasi publik',
    ],
    answer: 1,
    explanation: '17. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 18,
    question: 'Konflik kepentingan terjadi ketika ...',
    options: [
      'Keputusan dibuat berdasarkan aturan',
      'Kepentingan pribadi dapat memengaruhi keputusan tugas',
      'Petugas berdiskusi dengan atasan',
      'Laporan diperiksa berlapis',
      'Pelayanan diberikan sesuai antrean',
    ],
    answer: 1,
    explanation: '18. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 19,
    question: 'Penggunaan uang negara yang bertanggung jawab harus ...',
    options: [
      'Efisien, efektif, transparan, dan dapat dipertanggungjawabkan',
      'Dirahasiakan seluruhnya',
      'Mengikuti keinginan pejabat',
      'Dibelanjakan secepat mungkin',
      'Dibagi kepada pegawai',
    ],
    answer: 0,
    explanation: '19. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 20,
    question: 'Pajak bagi negara pada prinsipnya berfungsi untuk ...',
    options: [
      'Membiayai penyelenggaraan negara dan pembangunan',
      'Menguntungkan satu perusahaan',
      'Menghapus semua kewajiban warga',
      'Membatasi pendidikan',
      'Memberi hadiah kepada pejabat',
    ],
    answer: 0,
    explanation: '20. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 21,
    question: 'Akuntabilitas berarti ...',
    options: [
      'Bebas dari pemeriksaan',
      'Kewajiban menjelaskan dan mempertanggungjawabkan tindakan atau penggunaan sumber daya',
      'Menyimpan semua dokumen pribadi',
      'Mengutamakan hasil tanpa proses',
      'Menolak evaluasi',
    ],
    answer: 1,
    explanation: '21. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 22,
    question: 'Pelayanan publik yang baik harus ...',
    options: [
      'Cepat, adil, transparan, dan tidak diskriminatif',
      'Mendahulukan orang yang dikenal',
      'Bergantung pada imbalan',
      'Menutup informasi prosedur',
      'Mengabaikan kelompok rentan',
    ],
    answer: 0,
    explanation: '22. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 23,
    question: 'Jika masyarakat tidak memahami prosedur layanan, petugas sebaiknya ...',
    options: [
      'Menyalahkan masyarakat',
      'Menjelaskan dengan bahasa yang mudah dan sesuai aturan',
      'Meminta biaya tambahan',
      'Menyuruh mencari sendiri',
      'Mendahulukan orang lain',
    ],
    answer: 1,
    explanation: '23. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 24,
    question:
        'Jika antrean layanan tidak tertib, tindakan yang tepat adalah ...',
    options: [
      'Mendahulukan kenalan',
      'Membiarkannya',
      'Menjelaskan aturan antrean dan menerapkannya secara konsisten',
      'Menutup layanan',
      'Meminta imbalan untuk prioritas',
    ],
    answer: 2,
    explanation: '24. Jawaban C',
  ),
  KedinasanTwkQuestion(
    number: 25,
    question: 'Data keuangan atau data pribadi masyarakat sebaiknya ...',
    options: [
      'Dibagikan ke grup teman',
      'Diakses dan disampaikan hanya sesuai kewenangan dan kebutuhan tugas',
      'Diunggah untuk transparansi',
      'Disimpan di perangkat tanpa pengamanan',
      'Dijadikan bahan candaan',
    ],
    answer: 1,
    explanation: '25. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 26,
    question: 'Jika menerima email yang meminta kata sandi dan OTP untuk verifikasi akun, Anda ...',
    options: [
      'Memberikan segera',
      'Meneruskan ke teman',
      'Tidak memberikan data dan melaporkan dugaan penipuan',
      'Membalas dengan data pribadi lain',
      'Mengunggahnya ke media sosial',
    ],
    answer: 2,
    explanation: '26. Jawaban C',
  ),
  KedinasanTwkQuestion(
    number: 27,
    question: 'Sikap netral dalam pelayanan berarti ...',
    options: [
      'Melayani berdasarkan pilihan politik',
      'Tidak membeda-bedakan masyarakat karena pilihan, suku, agama, atau kedekatan',
      'Mendukung pemohon yang dikenal',
      'Menolak kritik',
      'Mengutamakan kelompok mayoritas',
    ],
    answer: 1,
    explanation: '27. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 28,
    question:
        'Jika atasan meminta tindakan yang jelas melanggar hukum, Anda ...',
    options: [
      'Langsung melaksanakan',
      'Memastikan instruksi, menyampaikan keberatan secara resmi, dan mengikuti mekanisme pelaporan',
      'Mengunggah tuduhan ke media sosial',
      'Membalas dengan kasar',
      'Mengajak teman menutupi',
    ],
    answer: 1,
    explanation: '28. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 29,
    question: 'Kalimat yang paling efektif adalah ...',
    options: [
      'Para peserta-peserta wajib hadir.',
      'Peserta wajib hadir tepat waktu.',
      'Kepada peserta diwajibkan untuk hadir.',
      'Peserta wajib untuk dapat hadir.',
      'Para peserta semuanya wajib hadir.',
    ],
    answer: 1,
    explanation: '29. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 30,
    question: 'Kata baku yang tepat adalah ...',
    options: ['Resiko', 'Ijin', 'Analisa', 'Aktivitas', 'Praktek'],
    answer: 3,
    explanation: '30. Jawaban D',
  ),
];

const STINTwkQuestions = <KedinasanTwkQuestion>[
  KedinasanTwkQuestion(
    number: 1,
    question: 'Sikap yang paling sesuai dengan nilai Pancasila ketika menerima informasi yang menyerang kelompok tertentu adalah ...',
    options: [
      'Langsung menyebarkannya',
      'Membalas dengan hinaan',
      'Memeriksa kebenaran dan tidak menyebarkan kebencian',
      'Menghapus semua pendapat yang berbeda',
      'Mengajak kelompok sendiri melakukan perlawanan',
    ],
    answer: 2,
    explanation: '1. Jawaban C',
  ),
  KedinasanTwkQuestion(
    number: 2,
    question: 'Dalam menjalankan tugas negara, kepentingan yang harus diutamakan adalah ...',
    options: [
      'Kepentingan pribadi',
      'Kepentingan keluarga',
      'Kepentingan kelompok asal',
      'Kepentingan bangsa dan negara sesuai hukum',
      'Kepentingan pihak yang memberi imbalan',
    ],
    answer: 3,
    explanation: '2. Jawaban D',
  ),
  KedinasanTwkQuestion(
    number: 3,
    question: 'Musyawarah yang baik dalam sebuah tim ditunjukkan dengan ...',
    options: [
      'Memaksakan pendapat pemimpin',
      'Mendengar pendapat, menilai alasan, lalu mengambil keputusan bertanggung jawab',
      'Mengikuti pendapat terbanyak tanpa berpikir',
      'Menghindari perbedaan pendapat',
      'Membiarkan keputusan tanpa penanggung jawab',
    ],
    answer: 1,
    explanation: '3. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 4,
    question: 'Kedudukan UUD Negara Republik Indonesia Tahun 1945 dalam sistem hukum nasional adalah ...',
    options: [
      'Hukum dasar tertulis',
      'Peraturan daerah tertinggi',
      'Pedoman organisasi masyarakat',
      'Kebiasaan tidak tertulis',
      'Peraturan teknis kementerian',
    ],
    answer: 0,
    explanation: '4. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 5,
    question:
        'Prinsip persamaan kedudukan warga negara di dalam hukum berarti ...',
    options: [
      'Hukum dapat dibeli oleh orang tertentu',
      'Penegakan hukum harus membedakan status sosial',
      'Setiap orang diperlakukan berdasarkan hukum tanpa diskriminasi',
      'Pejabat tidak dapat diperiksa',
      'Keluarga petugas mendapat prioritas hukum',
    ],
    answer: 2,
    explanation: '5. Jawaban C',
  ),
  KedinasanTwkQuestion(
    number: 6,
    question: 'Pembukaan UUD 1945 memuat tujuan negara, salah satunya ...',
    options: [
      'Melindungi segenap bangsa Indonesia',
      'Menguasai negara lain',
      'Membatasi pendidikan warga',
      'Menghapus keragaman budaya',
      'Mengutamakan satu golongan',
    ],
    answer: 0,
    explanation: '6. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 7,
    question: 'Bentuk negara Indonesia adalah ...',
    options: ['Monarki', 'Serikat', 'Kesatuan', 'Konfederasi', 'Protektorat'],
    answer: 2,
    explanation: '7. Jawaban C',
  ),
  KedinasanTwkQuestion(
    number: 8,
    question: 'Ancaman nonmiliter yang dapat melemahkan persatuan adalah ...',
    options: [
      'Gotong royong',
      'Disinformasi yang memecah belah masyarakat',
      'Musyawarah',
      'Toleransi',
      'Kerja bakti',
    ],
    answer: 1,
    explanation: '8. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 9,
    question: 'Makna Bhinneka Tunggal Ika adalah ...',
    options: [
      'Berbeda-beda tetapi tetap satu',
      'Semua daerah harus sama',
      'Perbedaan harus dihilangkan',
      'Satu kelompok lebih tinggi',
      'Kepentingan daerah di atas negara',
    ],
    answer: 0,
    explanation: '9. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 10,
    question: 'Bela negara bagi calon taruna dapat diwujudkan melalui ...',
    options: [
      'Belajar disiplin, menaati hukum, dan menjaga persatuan',
      'Menyebarkan rahasia negara',
      'Mengikuti semua perintah tanpa menilai legalitasnya',
      'Menolak kritik',
      'Mengutamakan kepentingan pribadi',
    ],
    answer: 0,
    explanation: '10. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 11,
    question: 'Jika mendapat ajakan untuk menyebarkan propaganda yang memecah masyarakat, tindakan Anda adalah ...',
    options: [
      'Menyebarkan secara terbatas',
      'Menolak, memeriksa informasi, dan melaporkannya bila melanggar hukum',
      'Menyimpan untuk digunakan nanti',
      'Membalas dengan propaganda lain',
      'Mengajak teman ikut menyebarkan',
    ],
    answer: 1,
    explanation: '11. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 12,
    question: 'Sikap yang mencerminkan kecintaan kepada tanah air adalah ...',
    options: [
      'Mengkritik tanpa solusi',
      'Menjaga lingkungan, menaati hukum, dan berkontribusi sesuai kemampuan',
      'Menganggap bangsa sendiri selalu benar',
      'Menolak semua kerja sama luar negeri',
      'Membela kesalahan kelompok sendiri',
    ],
    answer: 1,
    explanation: '12. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 13,
    question: 'Integritas paling tepat berarti ...',
    options: [
      'Kemampuan menyembunyikan kesalahan',
      'Kesesuaian antara nilai, ucapan, dan tindakan',
      'Keberanian melanggar aturan',
      'Kepandaian mencari keuntungan',
      'Kemampuan menyenangkan semua pihak',
    ],
    answer: 1,
    explanation: '13. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 14,
    question: 'Jika menemukan dokumen berisi data pribadi peserta seleksi, Anda sebaiknya ...',
    options: [
      'Memotretnya untuk koleksi',
      'Mengirim ke grup teman',
      'Menyerahkan kepada petugas berwenang dan menjaga kerahasiaannya',
      'Mencari identitas pemilik di media sosial',
      'Membaca lalu membuangnya sembarangan',
    ],
    answer: 2,
    explanation: '14. Jawaban C',
  ),
  KedinasanTwkQuestion(
    number: 15,
    question: 'Jika seseorang menawarkan uang agar Anda membocorkan informasi seleksi, tindakan yang benar adalah ...',
    options: [
      'Menerima jika jumlahnya kecil',
      'Menolak dan melaporkan melalui mekanisme resmi',
      'Menerima lalu membaginya',
      'Meminta waktu untuk mempertimbangkan',
      'Memberi informasi sedikit saja',
    ],
    answer: 1,
    explanation: '15. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 16,
    question: 'Anda mengetahui teman melakukan kecurangan dalam ujian. Sikap yang paling tepat adalah ...',
    options: [
      'Membiarkan demi pertemanan',
      'Ikut membantu',
      'Mengingatkan dan melaporkan melalui prosedur yang benar bila berlanjut',
      'Menyebarkan sebagai bahan ejekan',
      'Meminta imbalan agar diam',
    ],
    answer: 2,
    explanation: '16. Jawaban C',
  ),
  KedinasanTwkQuestion(
    number: 17,
    question: 'Ketika melakukan kesalahan, sikap yang menunjukkan tanggung jawab adalah ...',
    options: [
      'Menyalahkan keadaan',
      'Menghapus bukti',
      'Mengakui, memperbaiki, dan mencegah pengulangan',
      'Menunggu orang lain lupa',
      'Membuat alasan baru',
    ],
    answer: 2,
    explanation: '17. Jawaban C',
  ),
  KedinasanTwkQuestion(
    number: 18,
    question:
        'Prinsip yang tepat dalam menangani informasi kedinasan adalah ...',
    options: [
      'Membagikan kepada orang dekat',
      'Mengunggah jika informasinya menarik',
      'Mengakses dan menyampaikan hanya sesuai kewenangan dan kebutuhan tugas',
      'Menyimpan semua informasi di ponsel pribadi',
      'Membicarakannya di tempat umum',
    ],
    answer: 2,
    explanation: '18. Jawaban C',
  ),
  KedinasanTwkQuestion(
    number: 19,
    question: 'Jika teman meminta informasi internal yang bukan haknya, Anda sebaiknya ...',
    options: [
      'Memberikan karena teman dekat',
      'Memberikan sebagian',
      'Menolak dengan sopan dan mengarahkan ke jalur resmi',
      'Meminta imbalan',
      'Mengunggahnya tanpa nama',
    ],
    answer: 2,
    explanation: '19. Jawaban C',
  ),
  KedinasanTwkQuestion(
    number: 20,
    question: 'Mengunggah foto kartu peserta, dokumen, atau ruang seleksi ke media sosial berisiko karena ...',
    options: [
      'Membuat akun lebih terkenal',
      'Dapat membuka data pribadi dan informasi yang tidak semestinya tersebar',
      'Selalu meningkatkan nilai ujian',
      'Tidak memiliki dampak apa pun',
      'Membantu panitia mengoreksi data',
    ],
    answer: 1,
    explanation: '20. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 21,
    question: 'Menurut informasi resmi STIN, STIN merupakan perguruan tinggi kedinasan yang membentuk ...',
    options: [
      'Pelaku usaha swasta',
      'Insan intelijen profesional, berintegritas, dan berdedikasi bagi bangsa',
      'Tenaga hiburan',
      'Petugas tanpa aturan',
      'Kelompok politik tertentu',
    ],
    answer: 1,
    explanation: '21. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 22,
    question: 'Kerahasiaan tidak boleh dijadikan alasan untuk ...',
    options: [
      'Mengikuti prosedur keamanan',
      'Membatasi akses sesuai kewenangan',
      'Menutupi pelanggaran atau kejahatan',
      'Melindungi data pribadi',
      'Menyampaikan informasi kepada pejabat berwenang',
    ],
    answer: 2,
    explanation: '22. Jawaban C',
  ),
  KedinasanTwkQuestion(
    number: 23,
    question: 'Dalam menghadapi informasi yang belum terverifikasi, calon taruna sebaiknya ...',
    options: [
      'Menyimpulkan seketika',
      'Membandingkan sumber, memeriksa fakta, dan menahan diri dari penyebaran',
      'Memilih sumber yang paling sesuai keinginan',
      'Membuat judul provokatif',
      'Menganggap semua informasi benar',
    ],
    answer: 1,
    explanation: '23. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 24,
    question: 'Pesan yang meminta kata sandi dan kode OTP dengan alasan verifikasi sebaiknya ...',
    options: [
      'Diberikan segera',
      'Diteruskan ke teman',
      'Diabaikan, tidak memberikan data, dan dilaporkan sebagai dugaan penipuan',
      'Dibalas dengan kata sandi palsu',
      'Dipublikasikan beserta data pengirim',
    ],
    answer: 2,
    explanation: '24. Jawaban C',
  ),
  KedinasanTwkQuestion(
    number: 25,
    question:
        'Cara paling bertanggung jawab menggunakan media sosial adalah ...',
    options: [
      'Menyebarkan informasi yang menarik tanpa cek',
      'Menjaga privasi, memeriksa sumber, dan menggunakan bahasa yang tidak menghasut',
      'Menggunakan akun anonim untuk menyerang',
      'Membagikan dokumen internal',
      'Mengikuti semua tren',
    ],
    answer: 1,
    explanation: '25. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 26,
    question: 'Sikap terhadap perbedaan agama, suku, dan budaya yang tepat adalah ...',
    options: [
      'Menghormati perbedaan dan tetap menjaga persatuan',
      'Memaksakan kebiasaan sendiri',
      'Menghindari semua orang berbeda',
      'Menyebarkan stereotip',
      'Menilai kesetiaan berdasarkan asal daerah',
    ],
    answer: 0,
    explanation: '26. Jawaban A',
  ),
  KedinasanTwkQuestion(
    number: 27,
    question: 'Jika atasan atau senior memberi instruksi yang menurut Anda bertentangan dengan hukum, langkah pertama yang tepat adalah ...',
    options: [
      'Langsung menyebarkan tuduhan',
      'Melaksanakan tanpa bertanya',
      'Memastikan kejelasan instruksi dan menyampaikannya melalui jalur resmi sesuai aturan',
      'Menolak dengan kasar',
      'Mengikuti jika tidak ada saksi',
    ],
    answer: 2,
    explanation: '27. Jawaban C',
  ),
  KedinasanTwkQuestion(
    number: 28,
    question: 'Jika kepentingan keluarga bertentangan dengan tugas negara, Anda seharusnya ...',
    options: [
      'Selalu memilih keluarga',
      'Menggunakan jabatan untuk membantu keluarga',
      'Menjalankan tugas sesuai hukum dan menjelaskan batasannya kepada keluarga',
      'Menyembunyikan konflik kepentingan',
      'Meminta imbalan dari keluarga',
    ],
    answer: 2,
    explanation: '28. Jawaban C',
  ),
  KedinasanTwkQuestion(
    number: 29,
    question: 'Kalimat yang paling efektif adalah ...',
    options: [
      'Para peserta-peserta wajib hadir tepat waktu.',
      'Peserta wajib hadir tepat waktu.',
      'Kepada peserta diwajibkan untuk hadir tepat waktu.',
      'Peserta wajib untuk dapat hadir dengan tepat pada waktunya.',
      'Para peserta semuanya wajib untuk hadir.',
    ],
    answer: 1,
    explanation: '29. Jawaban B',
  ),
  KedinasanTwkQuestion(
    number: 30,
    question: 'Kata baku yang tepat adalah ...',
    options: ['Resiko', 'Ijin', 'Analisa', 'Aktivitas', 'Praktek'],
    answer: 3,
    explanation: '30. Jawaban D',
  ),
];
