/// Bank soal Try Out Mental Ideologi calon prajurit TNI dari TB XI.
class MentalIdeologyQuestion {
  final int number;
  final String category;
  final String question;
  final List<String> options;
  final int? answer;
  final String explanation;
  final bool interview;

  const MentalIdeologyQuestion({
    required this.number,
    required this.category,
    required this.question,
    required this.options,
    required this.answer,
    required this.explanation,
    required this.interview,
  });
}

const mentalIdeologyQuestions = <MentalIdeologyQuestion>[
  MentalIdeologyQuestion(
    number: 1,
    category: 'Nilai Kebangsaan',
    question: 'Dasar negara Republik Indonesia adalah ...',
    options: [
      'UUD 1945',
      'Pancasila',
      'Bhinneka Tunggal Ika',
      'Proklamasi',
      'Garuda Pancasila',
    ],
    answer: 1,
    explanation: 'Pancasila merupakan dasar negara Indonesia.',
    interview: false,
  ),
  MentalIdeologyQuestion(
    number: 2,
    category: 'Nilai Kebangsaan',
    question: 'Sikap yang paling mencerminkan Bhinneka Tunggal Ika adalah ...',
    options: [
      'Memaksakan budaya sendiri',
      'Menghormati perbedaan dan tetap menjaga persatuan',
      'Menghindari orang yang berbeda',
      'Mengutamakan kelompok sendiri',
      'Menolak musyawarah',
    ],
    answer: 1,
    explanation: 'Perbedaan dihormati, persatuan tetap dijaga.',
    interview: false,
  ),
  MentalIdeologyQuestion(
    number: 3,
    category: 'Nilai Kebangsaan',
    question: 'Pancasila sila ketiga menekankan pentingnya ...',
    options: [
      'Ketuhanan',
      'Kemanusiaan',
      'Persatuan Indonesia',
      'Musyawarah',
      'Keadilan sosial',
    ],
    answer: 2,
    explanation: 'Sila ketiga adalah Persatuan Indonesia.',
    interview: false,
  ),
  MentalIdeologyQuestion(
    number: 4,
    category: 'Nilai Kebangsaan',
    question: 'Contoh pengamalan sila keempat adalah ...',
    options: [
      'Memaksakan pendapat',
      'Menyelesaikan masalah melalui musyawarah',
      'Mengutamakan kekayaan',
      'Menolak kritik',
      'Membeda-bedakan teman',
    ],
    answer: 1,
    explanation:
        'Musyawarah mengutamakan kebijaksanaan dan kepentingan bersama.',
    interview: false,
  ),
  MentalIdeologyQuestion(
    number: 5,
    category: 'Nilai Kebangsaan',
    question: 'Lambang negara Indonesia adalah ...',
    options: [
      'Merah Putih',
      'Indonesia Raya',
      'Garuda Pancasila',
      'Nusantara',
      'Bhinneka',
    ],
    answer: 2,
    explanation: 'Lambang negara Indonesia adalah Garuda Pancasila.',
    interview: false,
  ),
  MentalIdeologyQuestion(
    number: 6,
    category: 'Komitmen NKRI',
    question: 'NKRI adalah singkatan dari ...',
    options: [
      'Negara Kesatuan Republik Indonesia',
      'Negara Kedaulatan Rakyat Indonesia',
      'Negara Kebangsaan Republik Indonesia',
      'Negara Kesatuan Rakyat Indonesia',
      'Negara Keadilan Republik Indonesia',
    ],
    answer: 0,
    explanation: 'NKRI berarti Negara Kesatuan Republik Indonesia.',
    interview: false,
  ),
  MentalIdeologyQuestion(
    number: 7,
    category: 'Komitmen NKRI',
    question: 'Bela negara dapat diwujudkan calon prajurit dengan cara ...',
    options: [
      'Mengutamakan kepentingan pribadi',
      'Menjaga disiplin, belajar sungguh-sungguh, dan menaati aturan',
      'Menyebarkan berita yang belum terverifikasi',
      'Menolak tugas sulit',
      'Menghindari tanggung jawab',
    ],
    answer: 1,
    explanation: 'Bela negara dimulai dari sikap disiplin dan tanggung jawab.',
    interview: false,
  ),
  MentalIdeologyQuestion(
    number: 8,
    category: 'Komitmen NKRI',
    question: 'Jika ditempatkan di wilayah mana pun di Indonesia, sikap yang tepat adalah ...',
    options: [
      'Hanya bersedia di daerah asal',
      'Bersedia melaksanakan tugas sesuai perintah dan kebutuhan negara',
      'Menolak daerah terpencil',
      'Menunggu fasilitas sempurna',
      'Memilih tugas yang paling ringan',
    ],
    answer: 1,
    explanation: 'Prajurit harus siap mengabdi di seluruh wilayah NKRI.',
    interview: false,
  ),
  MentalIdeologyQuestion(
    number: 9,
    category: 'Komitmen NKRI',
    question: 'Ancaman terhadap persatuan bangsa di media sosial sebaiknya dihadapi dengan ...',
    options: [
      'Membalas dengan hinaan',
      'Memeriksa fakta dan tidak menyebarkan provokasi',
      'Menyebarkan ulang agar ramai',
      'Membuat akun palsu',
      'Mengajak konflik',
    ],
    answer: 1,
    explanation: 'Informasi harus disaring dan provokasi tidak disebarkan.',
    interview: false,
  ),
  MentalIdeologyQuestion(
    number: 10,
    category: 'Komitmen NKRI',
    question: 'Kepentingan yang harus diutamakan prajurit ketika menjalankan tugas adalah ...',
    options: [
      'Kepentingan pribadi',
      'Kepentingan kelompok kecil',
      'Kepentingan bangsa dan negara',
      'Kepentingan media sosial',
      'Kepentingan teman',
    ],
    answer: 2,
    explanation:
        'Pengabdian prajurit berorientasi pada kepentingan bangsa dan negara.',
    interview: false,
  ),
  MentalIdeologyQuestion(
    number: 11,
    category: 'Integritas',
    question: 'Integritas paling tepat berarti ...',
    options: [
      'Kemampuan memengaruhi orang lain',
      'Keselarasan antara ucapan, nilai, dan perbuatan',
      'Keberanian mengambil risiko tanpa perhitungan',
      'Kepandaian mencari alasan',
      'Ketaatan hanya saat diawasi',
    ],
    answer: 1,
    explanation:
        'Integritas berarti konsisten dan jujur dalam sikap maupun tindakan.',
    interview: false,
  ),
  MentalIdeologyQuestion(
    number: 12,
    category: 'Integritas',
    question:
        'Jika menemukan dompet di area seleksi, tindakan yang benar adalah ...',
    options: [
      'Mengambil uangnya',
      'Menyimpan sampai ada yang bertanya',
      'Menyerahkan kepada panitia/petugas dan menjelaskan tempat ditemukan',
      'Membiarkannya',
      'Memberikannya kepada teman',
    ],
    answer: 2,
    explanation: 'Barang temuan harus dikembalikan melalui jalur yang benar.',
    interview: false,
  ),
  MentalIdeologyQuestion(
    number: 13,
    category: 'Integritas',
    question: 'Jika pernah melakukan kesalahan, jawaban yang paling berintegritas adalah ...',
    options: [
      'Menyalahkan orang lain',
      'Menutupi kesalahan',
      'Mengakui, menjelaskan secara jujur, dan memperbaikinya',
      'Mengubah cerita',
      'Menghindari pertanyaan',
    ],
    answer: 2,
    explanation: 'Kejujuran dan perbaikan menunjukkan integritas.',
    interview: false,
  ),
  MentalIdeologyQuestion(
    number: 14,
    category: 'Integritas',
    question:
        'Saat melihat teman menyontek dalam latihan, sikap tepat adalah ...',
    options: [
      'Ikut menyontek',
      'Membiarkan karena teman',
      'Mengingatkan dan melaporkan melalui cara yang sesuai bila berlanjut',
      'Mempermalukannya di depan umum',
      'Meminta imbalan',
    ],
    answer: 2,
    explanation: 'Loyalitas tidak boleh mengalahkan kejujuran dan aturan.',
    interview: false,
  ),
  MentalIdeologyQuestion(
    number: 15,
    category: 'Integritas',
    question: 'Pemberian uang agar seseorang diluluskan termasuk ...',
    options: [
      'Penghargaan',
      'Solidaritas',
      'Suap dan pelanggaran integritas',
      'Tanda persahabatan',
      'Sedekah biasa',
    ],
    answer: 2,
    explanation: 'Pemberian untuk memengaruhi hasil seleksi adalah suap.',
    interview: false,
  ),
  MentalIdeologyQuestion(
    number: 16,
    category: 'Tanggung Jawab',
    question: 'Tanggung jawab dalam latihan berarti ...',
    options: [
      'Hadir hanya saat diawasi',
      'Menyelesaikan tugas sesuai standar dan menerima akibat dari tindakan',
      'Memilih tugas mudah',
      'Menunggu diperintah terus-menerus',
      'Menyerahkan tugas kepada teman',
    ],
    answer: 1,
    explanation: 'Tanggung jawab mencakup pelaksanaan tugas dan kesiapan menerima konsekuensinya.',
    interview: false,
  ),
  MentalIdeologyQuestion(
    number: 17,
    category: 'Tanggung Jawab',
    question: 'Jika terlambat karena kelalaian sendiri, tindakan paling tepat adalah ...',
    options: [
      'Membuat alasan palsu',
      'Menyalahkan kendaraan',
      'Mengakui keterlambatan, meminta maaf, dan memperbaiki kebiasaan',
      'Menghilang',
      'Menuduh peserta lain',
    ],
    answer: 2,
    explanation:
        'Sikap bertanggung jawab dimulai dari kejujuran dan perbaikan.',
    interview: false,
  ),
  MentalIdeologyQuestion(
    number: 18,
    category: 'Tanggung Jawab',
    question: 'Perintah atasan yang sah dan sesuai aturan sebaiknya ...',
    options: [
      'Dilaksanakan dengan disiplin',
      'Diabaikan',
      'Dikerjakan hanya jika menguntungkan',
      'Didebat di depan umum',
      'Dialihkan kepada orang lain',
    ],
    answer: 0,
    explanation: 'Perintah kedinasan yang sah dilaksanakan dengan disiplin.',
    interview: false,
  ),
  MentalIdeologyQuestion(
    number: 19,
    category: 'Tanggung Jawab',
    question: 'Ketika tidak memahami instruksi, calon prajurit sebaiknya ...',
    options: [
      'Menebak dan menyembunyikan hasil',
      'Bertanya dengan sopan untuk memastikan pemahaman',
      'Menolak tugas',
      'Menunggu sampai dimarahi',
      'Menyalahkan pemberi instruksi',
    ],
    answer: 1,
    explanation: 'Klarifikasi yang sopan mencegah kesalahan pelaksanaan.',
    interview: false,
  ),
  MentalIdeologyQuestion(
    number: 20,
    category: 'Tanggung Jawab',
    question: 'Disiplin paling tepat dipahami sebagai ...',
    options: [
      'Takut kepada hukuman',
      'Kepatuhan pada aturan karena kesadaran dan tanggung jawab',
      'Ketaatan hanya di depan atasan',
      'Kebebasan tanpa batas',
      'Sikap keras kepada orang lain',
    ],
    answer: 1,
    explanation:
        'Disiplin idealnya lahir dari kesadaran, bukan hanya rasa takut.',
    interview: false,
  ),
  MentalIdeologyQuestion(
    number: 21,
    category: 'Sikap/Wawancara',
    question: 'Apa alasan Anda ingin menjadi prajurit TNI?',
    options: [],
    answer: null,
    explanation: 'Jawaban harus jujur, menunjukkan keinginan mengabdi kepada bangsa dan negara, kesiapan hidup disiplin, serta bukan semata-mata mengejar gaji, status, atau fasilitas.',
    interview: true,
  ),
  MentalIdeologyQuestion(
    number: 22,
    category: 'Sikap/Wawancara',
    question: 'Apakah Anda bersedia ditempatkan di seluruh wilayah NKRI?',
    options: [],
    answer: null,
    explanation: 'Jawaban ideal menunjukkan kesiapan menerima penempatan sesuai kebutuhan organisasi dan negara, dengan tetap jujur terhadap kondisi pribadi.',
    interview: true,
  ),
  MentalIdeologyQuestion(
    number: 23,
    category: 'Sikap/Wawancara',
    question: 'Apa yang Anda lakukan jika mendapat tugas berat yang tidak Anda sukai?',
    options: [],
    answer: null,
    explanation: 'Terima dan kerjakan dengan sungguh-sungguh, pahami tujuan tugas, minta arahan bila perlu, dan tidak meninggalkan tanggung jawab.',
    interview: true,
  ),
  MentalIdeologyQuestion(
    number: 24,
    category: 'Sikap/Wawancara',
    question: 'Bagaimana sikap Anda jika teman dekat melanggar aturan?',
    options: [],
    answer: null,
    explanation: 'Tetap mengingatkan dan melaporkan melalui prosedur yang benar. Kedekatan pribadi tidak boleh mengalahkan aturan dan kepentingan organisasi.',
    interview: true,
  ),
  MentalIdeologyQuestion(
    number: 25,
    category: 'Sikap/Wawancara',
    question: 'Apa arti setia kepada NKRI bagi Anda?',
    options: [],
    answer: null,
    explanation: 'Setia berarti menjunjung Pancasila dan UUD 1945, menjaga persatuan, menaati hukum, serta mendahulukan kepentingan bangsa dan negara.',
    interview: true,
  ),
  MentalIdeologyQuestion(
    number: 26,
    category: 'Sikap/Wawancara',
    question: 'Apa yang Anda lakukan jika menerima informasi provokatif tentang TNI/NKRI?',
    options: [],
    answer: null,
    explanation: 'Tidak langsung percaya atau menyebarkan. Periksa sumber, bandingkan dengan informasi resmi, dan laporkan konten berbahaya melalui jalur yang tepat.',
    interview: true,
  ),
  MentalIdeologyQuestion(
    number: 27,
    category: 'Sikap/Wawancara',
    question: 'Bagaimana Anda menyikapi kritik dari atasan?',
    options: [],
    answer: null,
    explanation: 'Mendengarkan dengan hormat, tidak defensif, mengambil pelajaran, dan memperbaiki kekurangan.',
    interview: true,
  ),
  MentalIdeologyQuestion(
    number: 28,
    category: 'Sikap/Wawancara',
    question: 'Apa arti kejujuran dalam proses seleksi?',
    options: [],
    answer: null,
    explanation: 'Memberikan data dan jawaban apa adanya, tidak menggunakan joki, tidak menyuap, tidak menyontek, dan menerima hasil sesuai proses yang sah.',
    interview: true,
  ),
  MentalIdeologyQuestion(
    number: 29,
    category: 'Sikap/Wawancara',
    question: 'Bagaimana jika Anda gagal dalam satu tahap seleksi?',
    options: [],
    answer: null,
    explanation: 'Menerima hasil dengan sportif, mengevaluasi kekurangan, memperbaiki diri, dan tetap menjaga sikap hormat terhadap panitia.',
    interview: true,
  ),
  MentalIdeologyQuestion(
    number: 30,
    category: 'Sikap/Wawancara',
    question: 'Sebutkan contoh tanggung jawab Anda di rumah atau sekolah.',
    options: [],
    answer: null,
    explanation: 'Sampaikan contoh nyata, misalnya menyelesaikan tugas tepat waktu, menjaga amanah, membantu keluarga, atau memimpin kegiatan dan menuntaskannya.',
    interview: true,
  ),
];

const mentalIdeologySource = 'TB XI';
