/// Bank soal Try Out TKD Akademi TNI dari dokumen TB XI.
/// Konten ini disiapkan untuk latihan di dalam aplikasi.
class TniQuestion {
  final int number;
  final String category;
  final String question;
  final List<String> options;
  final int answer;
  final String explanation;

  const TniQuestion({
    required this.number,
    required this.category,
    required this.question,
    required this.options,
    required this.answer,
    required this.explanation,
  });
}

const tniTryoutQuestions = <TniQuestion>[
  TniQuestion(
    number: 1,
    category: 'Matematika',
    question: '3x + 7 = 25, x = ...',
    options: ['4', '5', '6', '7', '8'],
    answer: 2,
    explanation: '3x=18, jadi x=6.',
  ),
  TniQuestion(
    number: 2,
    category: 'Matematika',
    question: '2/3 + 3/4 = ...',
    options: ['5/7', '7/12', '17/12', '19/12', '23/12'],
    answer: 2,
    explanation: '8/12+9/12=17/12.',
  ),
  TniQuestion(
    number: 3,
    category: 'Matematika',
    question: '180 km ditempuh 3 jam. Kecepatan ...',
    options: ['50 km/jam', '60 km/jam', '70 km/jam', '80 km/jam', '90 km/jam'],
    answer: 1,
    explanation: '180/3=60 km/jam.',
  ),
  TniQuestion(
    number: 4,
    category: 'Matematika',
    question: 'Barisan 4,9,14,19,... suku berikutnya ...',
    options: ['22', '23', '24', '25', '26'],
    answer: 2,
    explanation: 'Bertambah 5.',
  ),
  TniQuestion(
    number: 5,
    category: 'Matematika',
    question: 'Luas persegi panjang 12 cm x 7 cm ...',
    options: ['19 cm2', '38 cm2', '72 cm2', '84 cm2', '96 cm2'],
    answer: 3,
    explanation: '12x7=84 cm2.',
  ),
  TniQuestion(
    number: 6,
    category: 'Matematika',
    question: '20% dari bilangan adalah 36. Bilangan itu ...',
    options: ['120', '150', '180', '200', '240'],
    answer: 2,
    explanation: '36/0,2=180.',
  ),
  TniQuestion(
    number: 7,
    category: 'Matematika',
    question: 'Akar kuadrat 144 ditambah 5 ...',
    options: ['12', '15', '17', '19', '23'],
    answer: 2,
    explanation: '12+5=17.',
  ),
  TniQuestion(
    number: 8,
    category: 'Matematika',
    question: 'Perbandingan putra:putri 3:2, total 40. Putra ...',
    options: ['16', '20', '24', '28', '30'],
    answer: 2,
    explanation: '3/5x40=24.',
  ),
  TniQuestion(
    number: 9,
    category: 'Matematika',
    question: '5 kuadrat dikurangi 3 kuadrat ...',
    options: ['8', '12', '16', '18', '22'],
    answer: 2,
    explanation: '25-9=16.',
  ),
  TniQuestion(
    number: 10,
    category: 'Matematika',
    question: 'Harga Rp250.000 diskon 12%. Harga akhir ...',
    options: ['Rp210.000', 'Rp215.000', 'Rp220.000', 'Rp225.000', 'Rp230.000'],
    answer: 2,
    explanation: 'Harga akhir Rp220.000.',
  ),
  TniQuestion(
    number: 11,
    category: 'Bahasa Indonesia',
    question: 'Sinonim akurat ...',
    options: ['cepat', 'tepat', 'luas', 'rumit', 'samar'],
    answer: 1,
    explanation: 'Akurat berarti tepat.',
  ),
  TniQuestion(
    number: 12,
    category: 'Bahasa Indonesia',
    question: 'Antonim konkret ...',
    options: ['nyata', 'jelas', 'abstrak', 'padat', 'pasti'],
    answer: 2,
    explanation: 'Lawan konkret adalah abstrak.',
  ),
  TniQuestion(
    number: 13,
    category: 'Bahasa Indonesia',
    question: 'Kalimat efektif ...',
    options: [
      'Para peserta-peserta segera masuk.',
      'Para peserta segera masuk.',
      'Semua para peserta segera masuk.',
      'Peserta-peserta para masuk.',
      'Para segera peserta masuk.',
    ],
    answer: 1,
    explanation: 'Kata para sudah bermakna jamak.',
  ),
  TniQuestion(
    number: 14,
    category: 'Bahasa Indonesia',
    question: 'Kata baku ...',
    options: ['resiko', 'ijin', 'aktifitas', 'risiko', 'analisa'],
    answer: 3,
    explanation: 'Bentuk bakunya risiko.',
  ),
  TniQuestion(
    number: 15,
    category: 'Bahasa Indonesia',
    question: 'Gagasan utama terdapat pada ...',
    options: [
      'kalimat penjelas',
      'kalimat tanya',
      'kalimat utama',
      'kalimat seru',
      'kata terakhir',
    ],
    answer: 2,
    explanation: 'Dinyatakan pada kalimat utama.',
  ),
  TniQuestion(
    number: 16,
    category: 'Bahasa Indonesia',
    question: 'Ringan tangan membantu berarti ...',
    options: [
      'suka memukul',
      'tidak kuat',
      'suka menolong',
      'mudah menyerah',
      'bekerja lambat',
    ],
    answer: 2,
    explanation: 'Berarti suka menolong.',
  ),
  TniQuestion(
    number: 17,
    category: 'Bahasa Indonesia',
    question: 'Penulisan kata depan benar ...',
    options: ['dirumah', 'di meja', 'dipantai', 'disamping', 'di kantor-kan'],
    answer: 1,
    explanation: 'Di tempat ditulis terpisah.',
  ),
  TniQuestion(
    number: 18,
    category: 'Bahasa Indonesia',
    question: 'Nasionalisme berarti ...',
    options: [
      'cinta bangsa dan negara',
      'menolak aturan',
      'berbahasa asing',
      'berdagang',
      'hidup hemat',
    ],
    answer: 0,
    explanation: 'Cinta dan kesetiaan pada bangsa.',
  ),
  TniQuestion(
    number: 19,
    category: 'Bahasa Indonesia',
    question: 'Antonim optimistis ...',
    options: ['yakin', 'pesimistis', 'semangat', 'percaya', 'tekun'],
    answer: 1,
    explanation: 'Lawannya pesimistis.',
  ),
  TniQuestion(
    number: 20,
    category: 'Bahasa Indonesia',
    question: 'Tanda baca yang tepat untuk ajakan ...',
    options: [
      'Ayo kita berlatih!',
      'Ayo, kita berlatih.',
      'Ayo kita berlatih?',
      'Ayo kita, berlatih.',
      'Ayo kita berlatih,',
    ],
    answer: 0,
    explanation: 'Kalimat seruan diakhiri tanda seru.',
  ),
  TniQuestion(
    number: 21,
    category: 'Bahasa Inggris',
    question: 'Correct sentence.',
    options: [
      'He go to school.',
      'He goes to school.',
      'He going school.',
      'He gone school.',
      'He go school.',
    ],
    answer: 1,
    explanation: 'He memakai goes dalam simple present.',
  ),
  TniQuestion(
    number: 22,
    category: 'Bahasa Inggris',
    question: 'Synonym of brave ...',
    options: ['afraid', 'weak', 'courageous', 'lazy', 'careless'],
    answer: 2,
    explanation: 'Brave means courageous.',
  ),
  TniQuestion(
    number: 23,
    category: 'Bahasa Inggris',
    question: 'Opposite of ancient ...',
    options: ['old', 'modern', 'historic', 'former', 'traditional'],
    answer: 1,
    explanation: 'Ancient berarti kuno.',
  ),
  TniQuestion(
    number: 24,
    category: 'Bahasa Inggris',
    question: 'They are studying now. Tense ...',
    options: [
      'simple past',
      'simple present',
      'present continuous',
      'present perfect',
      'future',
    ],
    answer: 2,
    explanation: 'Are + studying adalah present continuous.',
  ),
  TniQuestion(
    number: 25,
    category: 'Bahasa Inggris',
    question: 'The soldiers ... disciplined.',
    options: ['is', 'am', 'are', 'be', 'was'],
    answer: 2,
    explanation: 'Soldiers jamak, memakai are.',
  ),
  TniQuestion(
    number: 26,
    category: 'Bahasa Inggris',
    question: 'Maintain means ...',
    options: ['destroy', 'preserve', 'forget', 'move', 'reduce'],
    answer: 1,
    explanation: 'Maintain berarti preserve.',
  ),
  TniQuestion(
    number: 27,
    category: 'Bahasa Inggris',
    question: 'Passive: The commander leads the team.',
    options: [
      'The team is led by the commander.',
      'The team leads the commander.',
      'The team was lead.',
      'The commander is led the team.',
      'The team leading.',
    ],
    answer: 0,
    explanation: 'Passive present: is + led.',
  ),
  TniQuestion(
    number: 28,
    category: 'Bahasa Inggris',
    question: 'Although expresses ...',
    options: ['cause', 'contrast', 'time', 'purpose', 'result'],
    answer: 1,
    explanation: 'Although menunjukkan pertentangan.',
  ),
  TniQuestion(
    number: 29,
    category: 'Bahasa Inggris',
    question: 'Plural of criterion ...',
    options: [
      'criterions',
      'criterias',
      'criterion',
      'criteria',
      'criteriones',
    ],
    answer: 3,
    explanation: 'Jamak criterion adalah criteria.',
  ),
  TniQuestion(
    number: 30,
    category: 'Bahasa Inggris',
    question: 'If I ... time, I will train.',
    options: ['have', 'had', 'has', 'having', 'am'],
    answer: 0,
    explanation: 'First conditional: if + simple present.',
  ),
  TniQuestion(
    number: 31,
    category: 'IPA',
    question: 'Organ pemompa darah ...',
    options: ['paru-paru', 'ginjal', 'jantung', 'hati', 'lambung'],
    answer: 2,
    explanation: 'Jantung memompa darah.',
  ),
  TniQuestion(
    number: 32,
    category: 'IPA',
    question: 'Satuan SI gaya ...',
    options: ['joule', 'watt', 'pascal', 'newton', 'volt'],
    answer: 3,
    explanation: 'Satuan gaya adalah newton.',
  ),
  TniQuestion(
    number: 33,
    category: 'IPA',
    question: 'Tumbuhan membuat makanan dengan cahaya ...',
    options: [
      'respirasi',
      'fotosintesis',
      'ekskresi',
      'evaporasi',
      'fermentasi',
    ],
    answer: 1,
    explanation: 'Prosesnya fotosintesis.',
  ),
  TniQuestion(
    number: 34,
    category: 'IPA',
    question: 'Planet Merah ...',
    options: ['Venus', 'Mars', 'Jupiter', 'Saturnus', 'Merkurius'],
    answer: 1,
    explanation: 'Mars tampak merah.',
  ),
  TniQuestion(
    number: 35,
    category: 'IPA',
    question: 'Cair menjadi gas ...',
    options: ['membeku', 'mencair', 'mengembun', 'menyublim', 'menguap'],
    answer: 4,
    explanation: 'Disebut menguap.',
  ),
  TniQuestion(
    number: 36,
    category: 'IPA',
    question: 'Massa 5 kg, percepatan 2 m/s2. Gaya ...',
    options: ['2 N', '5 N', '7 N', '10 N', '25 N'],
    answer: 3,
    explanation: 'F=m.a=10 N.',
  ),
  TniQuestion(
    number: 37,
    category: 'IPA',
    question: 'Pusat pengatur aktivitas sel ...',
    options: ['membran', 'sitoplasma', 'inti sel', 'dinding sel', 'vakuola'],
    answer: 2,
    explanation: 'Inti sel mengatur aktivitas.',
  ),
  TniQuestion(
    number: 38,
    category: 'IPA',
    question: 'Bunyi tidak merambat melalui ...',
    options: ['udara', 'air', 'besi', 'ruang hampa', 'kayu'],
    answer: 3,
    explanation: 'Bunyi memerlukan medium.',
  ),
  TniQuestion(
    number: 39,
    category: 'IPA',
    question: 'Lapisan atmosfer tempat cuaca ...',
    options: ['troposfer', 'stratosfer', 'mesosfer', 'termosfer', 'eksosfer'],
    answer: 0,
    explanation: 'Cuaca terjadi terutama di troposfer.',
  ),
  TniQuestion(
    number: 40,
    category: 'IPA',
    question: 'Gas untuk bernapas ...',
    options: ['nitrogen', 'oksigen', 'karbon dioksida', 'hidrogen', 'helium'],
    answer: 1,
    explanation: 'Manusia membutuhkan oksigen.',
  ),
  TniQuestion(
    number: 41,
    category: 'Wawasan Kebangsaan dan Logika',
    question: 'Dasar negara Indonesia ...',
    options: [
      'UUD 1945',
      'Pancasila',
      'Bhinneka Tunggal Ika',
      'Proklamasi',
      'Garuda',
    ],
    answer: 1,
    explanation: 'Pancasila adalah dasar negara.',
  ),
  TniQuestion(
    number: 42,
    category: 'Wawasan Kebangsaan dan Logika',
    question: 'Bhinneka Tunggal Ika berarti ...',
    options: [
      'Bersatu kita teguh',
      'Berbeda-beda tetapi tetap satu',
      'Merdeka atau mati',
      'Satu bangsa satu bahasa',
      'Gotong royong',
    ],
    answer: 1,
    explanation: 'Berbeda tetapi tetap satu.',
  ),
  TniQuestion(
    number: 43,
    category: 'Wawasan Kebangsaan dan Logika',
    question: 'UUD 1945 berfungsi sebagai ...',
    options: [
      'hukum dasar negara',
      'lambang negara',
      'lagu kebangsaan',
      'semboyan',
      'ideologi',
    ],
    answer: 0,
    explanation: 'UUD 1945 adalah hukum dasar tertulis.',
  ),
  TniQuestion(
    number: 44,
    category: 'Wawasan Kebangsaan dan Logika',
    question: 'Lagu kebangsaan Indonesia ...',
    options: [
      'Bagimu Negeri',
      'Indonesia Raya',
      'Garuda Pancasila',
      'Tanah Airku',
      'Hari Merdeka',
    ],
    answer: 1,
    explanation: 'Indonesia Raya.',
  ),
  TniQuestion(
    number: 45,
    category: 'Wawasan Kebangsaan dan Logika',
    question: 'Proklamasi dibacakan pada ...',
    options: [
      '10 November 1945',
      '17 Agustus 1945',
      '20 Mei 1908',
      '28 Oktober 1928',
      '1 Juni 1945',
    ],
    answer: 1,
    explanation: 'Tanggal proklamasi adalah 17 Agustus 1945.',
  ),
  TniQuestion(
    number: 46,
    category: 'Wawasan Kebangsaan dan Logika',
    question: 'Lembaga utama pertahanan negara ...',
    options: ['Polri', 'TNI', 'DPR', 'BPK', 'KPU'],
    answer: 1,
    explanation: 'TNI bertugas di bidang pertahanan.',
  ),
  TniQuestion(
    number: 47,
    category: 'Wawasan Kebangsaan dan Logika',
    question: 'Sikap sesuai persatuan ...',
    options: [
      'memaksakan budaya',
      'menghormati perbedaan',
      'menghindari kelompok lain',
      'mementingkan diri',
      'menolak musyawarah',
    ],
    answer: 1,
    explanation: 'Menghormati perbedaan memperkuat persatuan.',
  ),
  TniQuestion(
    number: 48,
    category: 'Wawasan Kebangsaan dan Logika',
    question: 'Barisan 2,6,12,20,30,...',
    options: ['36', '40', '42', '44', '48'],
    answer: 2,
    explanation: 'Selisih 4,6,8,10,12; hasil 42.',
  ),
  TniQuestion(
    number: 49,
    category: 'Wawasan Kebangsaan dan Logika',
    question: 'Semua taruna disiplin. Andi taruna. Kesimpulan ...',
    options: [
      'mungkin disiplin',
      'wajib disiplin',
      'bukan taruna',
      'semua disiplin taruna',
      'tidak perlu disiplin',
    ],
    answer: 1,
    explanation: 'Kesimpulan langsung dari premis.',
  ),
  TniQuestion(
    number: 50,
    category: 'Wawasan Kebangsaan dan Logika',
    question: 'Buku:membaca = makanan: ...',
    options: ['memasak', 'membeli', 'makan', 'menjual', 'menyimpan'],
    answer: 2,
    explanation: 'Buku dibaca; makanan dimakan.',
  ),
];

const tniTryoutSource = 'TB XI';
