/// Bank soal Try Out Akademik dan Siber Akademi TNI dari TB XI.
class TniAcademicQuestion {
  final int number;
  final String category;
  final String question;
  final List<String> options;
  final int answer;
  final String explanation;

  const TniAcademicQuestion({
    required this.number,
    required this.category,
    required this.question,
    required this.options,
    required this.answer,
    required this.explanation,
  });
}

const tniAcademicQuestions = <TniAcademicQuestion>[
  TniAcademicQuestion(
    number: 1,
    category: 'Matematika',
    question: 'Jika 4x - 6 = 22, nilai x ...',
    options: ['4', '6', '7', '8', '9'],
    answer: 2,
    explanation: '4x=28, jadi x=7.',
  ),
  TniAcademicQuestion(
    number: 2,
    category: 'Matematika',
    question: '25% dari 240 adalah ...',
    options: ['40', '50', '60', '70', '80'],
    answer: 2,
    explanation: '0,25x240=60.',
  ),
  TniAcademicQuestion(
    number: 3,
    category: 'Matematika',
    question: 'Barisan 3, 7, 11, 15, ... suku berikutnya ...',
    options: ['17', '18', '19', '20', '21'],
    answer: 2,
    explanation: 'Bertambah 4.',
  ),
  TniAcademicQuestion(
    number: 4,
    category: 'Matematika',
    question: 'Sebuah persegi sisi 9 cm. Kelilingnya ...',
    options: ['18 cm', '27 cm', '36 cm', '45 cm', '81 cm'],
    answer: 2,
    explanation: 'Keliling=4x9=36 cm.',
  ),
  TniAcademicQuestion(
    number: 5,
    category: 'Matematika',
    question: 'Rata-rata 70, 75, 80, dan 85 adalah ...',
    options: ['72,5', '75', '77,5', '80', '82,5'],
    answer: 2,
    explanation: 'Jumlah 310 dibagi 4=77,5.',
  ),
  TniAcademicQuestion(
    number: 6,
    category: 'Matematika',
    question: '3/5 dari 50 adalah ...',
    options: ['20', '25', '30', '35', '40'],
    answer: 2,
    explanation: '3/5x50=30.',
  ),
  TniAcademicQuestion(
    number: 7,
    category: 'Matematika',
    question: 'Jika jarak 150 km ditempuh 2,5 jam, kecepatannya ...',
    options: ['50', '60', '75', '80', '90'],
    answer: 1,
    explanation: '150/2,5=60 km/jam.',
  ),
  TniAcademicQuestion(
    number: 8,
    category: 'Matematika',
    question: 'Luas segitiga alas 12 cm dan tinggi 8 cm ...',
    options: ['24', '36', '48', '64', '96'],
    answer: 2,
    explanation: '1/2x12x8=48 cm2.',
  ),
  TniAcademicQuestion(
    number: 9,
    category: 'Bahasa Indonesia',
    question: 'Kata baku yang benar ...',
    options: ['praktek', 'apotek', 'ijin', 'nasehat', 'sekedar'],
    answer: 1,
    explanation: 'Bentuk bakunya apotek.',
  ),
  TniAcademicQuestion(
    number: 10,
    category: 'Bahasa Indonesia',
    question: 'Antonim kata objektif ...',
    options: ['netral', 'faktual', 'subjektif', 'tepat', 'terukur'],
    answer: 2,
    explanation: 'Lawan objektif adalah subjektif.',
  ),
  TniAcademicQuestion(
    number: 11,
    category: 'Bahasa Indonesia',
    question: 'Kalimat efektif ...',
    options: [
      'Ia masuk ke dalam ruangan.',
      'Ia masuk ke dalam masuk ruangan.',
      'Ia memasuki ke dalam ruangan.',
      'Ia masuk dalam ke ruangan.',
      'Ia masuk ruangan ke dalam.',
    ],
    answer: 0,
    explanation: 'Kalimat A paling efektif.',
  ),
  TniAcademicQuestion(
    number: 12,
    category: 'Bahasa Indonesia',
    question: 'Gagasan utama adalah ...',
    options: [
      'contoh tambahan',
      'inti pembahasan paragraf',
      'kata sulit',
      'judul buku',
      'kalimat penutup saja',
    ],
    answer: 1,
    explanation: 'Gagasan utama merupakan inti pembahasan.',
  ),
  TniAcademicQuestion(
    number: 13,
    category: 'Bahasa Indonesia',
    question: 'Makna ungkapan besar kepala ...',
    options: ['pintar', 'sombong', 'kuat', 'sakit', 'tinggi'],
    answer: 1,
    explanation: 'Besar kepala berarti sombong.',
  ),
  TniAcademicQuestion(
    number: 14,
    category: 'Bahasa Indonesia',
    question: 'Kata yang tepat: Peserta harus ... peraturan.',
    options: ['mentaati', 'menaati', 'mentaahkan', 'ditaati', 'ketaatan'],
    answer: 1,
    explanation: 'Bentuk baku yang benar adalah menaati.',
  ),
  TniAcademicQuestion(
    number: 15,
    category: 'Bahasa Indonesia',
    question: 'Penulisan judul yang tepat ...',
    options: [
      'Sejarah Tentara Nasional Indonesia',
      'Sejarah tentara nasional indonesia',
      'SEJARAH tentara Nasional Indonesia',
      'Sejarah Tentara nasional indonesia',
      'sejarah Tentara Nasional Indonesia',
    ],
    answer: 0,
    explanation: 'Huruf awal kata penting pada judul ditulis kapital.',
  ),
  TniAcademicQuestion(
    number: 16,
    category: 'Bahasa Indonesia',
    question: 'Kata integritas bermakna ...',
    options: [
      'kejujuran dan konsistensi moral',
      'kecepatan bekerja',
      'kekuatan fisik',
      'kepandaian bicara',
      'kekayaan',
    ],
    answer: 0,
    explanation: 'Integritas berkaitan dengan kejujuran dan konsistensi.',
  ),
  TniAcademicQuestion(
    number: 17,
    category: 'Bahasa Inggris',
    question: 'The opposite of honest is ...',
    options: ['truthful', 'sincere', 'dishonest', 'loyal', 'brave'],
    answer: 2,
    explanation: 'Honest berarti jujur; lawannya dishonest.',
  ),
  TniAcademicQuestion(
    number: 18,
    category: 'Bahasa Inggris',
    question: 'She ... English every day.',
    options: ['study', 'studies', 'studying', 'studied', 'has study'],
    answer: 1,
    explanation: 'She memakai studies dalam simple present.',
  ),
  TniAcademicQuestion(
    number: 19,
    category: 'Bahasa Inggris',
    question: 'The word reliable means ...',
    options: ['dapat dipercaya', 'berbahaya', 'lambat', 'mahal', 'rahasia'],
    answer: 0,
    explanation: 'Reliable berarti dapat dipercaya.',
  ),
  TniAcademicQuestion(
    number: 20,
    category: 'Bahasa Inggris',
    question: 'The report was written ... the officer.',
    options: ['by', 'at', 'on', 'to', 'from'],
    answer: 0,
    explanation: 'Kalimat pasif menggunakan by untuk pelaku.',
  ),
  TniAcademicQuestion(
    number: 21,
    category: 'Bahasa Inggris',
    question: 'If he studies hard, he ... pass.',
    options: ['will', 'would', 'was', 'has', 'had'],
    answer: 0,
    explanation: 'First conditional: will pass.',
  ),
  TniAcademicQuestion(
    number: 22,
    category: 'Bahasa Inggris',
    question: 'Choose the correct sentence.',
    options: [
      'They is ready.',
      'They are ready.',
      'They am ready.',
      'They be ready.',
      'They was ready.',
    ],
    answer: 1,
    explanation: 'They memakai are.',
  ),
  TniAcademicQuestion(
    number: 23,
    category: 'Bahasa Inggris',
    question: 'The synonym of duty is ...',
    options: ['responsibility', 'holiday', 'problem', 'fear', 'choice'],
    answer: 0,
    explanation: 'Duty berarti responsibility/tugas.',
  ),
  TniAcademicQuestion(
    number: 24,
    category: 'Bahasa Inggris',
    question: 'We must protect ... country.',
    options: ['our', 'we', 'us', 'ourselves', 'they'],
    answer: 0,
    explanation: 'Possessive adjective untuk we adalah our.',
  ),
  TniAcademicQuestion(
    number: 25,
    category: 'Pengetahuan Umum',
    question: 'Ibu kota Provinsi Jawa Barat adalah ...',
    options: ['Semarang', 'Bandung', 'Serang', 'Bogor', 'Cirebon'],
    answer: 1,
    explanation: 'Ibu kota Jawa Barat adalah Bandung.',
  ),
  TniAcademicQuestion(
    number: 26,
    category: 'Pengetahuan Umum',
    question: 'ASEAN didirikan untuk kerja sama negara-negara ...',
    options: ['Asia Timur', 'Asia Selatan', 'Asia Tenggara', 'Eropa', 'Afrika'],
    answer: 2,
    explanation: 'ASEAN adalah organisasi Asia Tenggara.',
  ),
  TniAcademicQuestion(
    number: 27,
    category: 'Pengetahuan Umum',
    question: 'Semboyan negara Indonesia ...',
    options: [
      'Tut Wuri Handayani',
      'Bhinneka Tunggal Ika',
      'Jalesveva Jayamahe',
      'Merdeka Belajar',
      'Ing Ngarsa',
    ],
    answer: 1,
    explanation: 'Semboyannya Bhinneka Tunggal Ika.',
  ),
  TniAcademicQuestion(
    number: 28,
    category: 'Pengetahuan Umum',
    question: 'Alat mengukur suhu ...',
    options: [
      'barometer',
      'termometer',
      'higrometer',
      'anemometer',
      'seismograf',
    ],
    answer: 1,
    explanation: 'Termometer mengukur suhu.',
  ),
  TniAcademicQuestion(
    number: 29,
    category: 'Pengetahuan Umum',
    question: 'Tanggal Sumpah Pemuda ...',
    options: [
      '20 Mei 1908',
      '17 Agustus 1945',
      '28 Oktober 1928',
      '10 November 1945',
      '1 Juni 1945',
    ],
    answer: 2,
    explanation: 'Sumpah Pemuda diperingati 28 Oktober 1928.',
  ),
  TniAcademicQuestion(
    number: 30,
    category: 'Pengetahuan Umum',
    question: 'Sumber energi terbarukan ...',
    options: ['batu bara', 'minyak bumi', 'gas alam', 'matahari', 'bensin'],
    answer: 3,
    explanation: 'Matahari merupakan energi terbarukan.',
  ),
  TniAcademicQuestion(
    number: 31,
    category: 'Siber',
    question: 'Kata sandi yang paling kuat adalah ...',
    options: [
      '12345678',
      'tanggal lahir',
      'kombinasi panjang huruf, angka, dan simbol unik',
      'nama sendiri',
      'password',
    ],
    answer: 2,
    explanation: 'Kata sandi unik dan panjang lebih sulit ditebak.',
  ),
  TniAcademicQuestion(
    number: 32,
    category: 'Siber',
    question: 'Phishing adalah ...',
    options: [
      'perbaikan komputer',
      'penipuan untuk mencuri data melalui pesan/situs palsu',
      'pencadangan data',
      'pembaruan sistem',
      'pemindaian virus resmi',
    ],
    answer: 1,
    explanation:
        'Phishing menyamar sebagai pihak tepercaya untuk mencuri informasi.',
  ),
  TniAcademicQuestion(
    number: 33,
    category: 'Siber',
    question: 'Kode OTP sebaiknya ...',
    options: [
      'dibagikan kepada teman',
      'dipasang di media sosial',
      'dirahasiakan dan hanya dimasukkan pada layanan resmi',
      'dikirim ke nomor asing',
      'ditulis di komentar',
    ],
    answer: 2,
    explanation: 'OTP adalah rahasia autentikasi.',
  ),
  TniAcademicQuestion(
    number: 34,
    category: 'Siber',
    question: 'Autentikasi dua faktor berguna untuk ...',
    options: [
      'mempercepat internet',
      'menambah lapisan keamanan saat login',
      'menghapus file',
      'mengganti perangkat keras',
      'menambah kapasitas baterai',
    ],
    answer: 1,
    explanation: '2FA menambah verifikasi selain kata sandi.',
  ),
  TniAcademicQuestion(
    number: 35,
    category: 'Siber',
    question: 'Jika menerima lampiran mencurigakan, sebaiknya ...',
    options: [
      'langsung dibuka',
      'diteruskan',
      'jangan dibuka dan verifikasi pengirim melalui kanal resmi',
      'dinonaktifkan antivirus',
      'diunggah ke publik',
    ],
    answer: 2,
    explanation: 'Lampiran dapat membawa malware.',
  ),
  TniAcademicQuestion(
    number: 36,
    category: 'Siber',
    question: 'Malware adalah ...',
    options: [
      'perangkat lunak berbahaya',
      'kabel jaringan',
      'aplikasi kamera',
      'sistem operasi resmi',
      'metode pencadangan',
    ],
    answer: 0,
    explanation: 'Malware adalah malicious software.',
  ),
  TniAcademicQuestion(
    number: 37,
    category: 'Siber',
    question: 'Pembaruan sistem penting karena ...',
    options: [
      'selalu memperlambat perangkat',
      'menutup celah keamanan dan memperbaiki kesalahan',
      'menghapus semua data',
      'mengganti identitas pengguna',
      'menonaktifkan internet',
    ],
    answer: 1,
    explanation: 'Update sering membawa perbaikan keamanan.',
  ),
  TniAcademicQuestion(
    number: 38,
    category: 'Siber',
    question: 'Cadangan data sebaiknya ...',
    options: [
      'tidak pernah dibuat',
      'dibuat berkala dan diuji pemulihannya',
      'disimpan hanya di satu perangkat tanpa pengamanan',
      'dibagikan ke publik',
      'dihapus setelah dibuat',
    ],
    answer: 1,
    explanation: 'Backup berkala perlu dapat dipulihkan.',
  ),
  TniAcademicQuestion(
    number: 39,
    category: 'Siber',
    question: 'Saat memakai Wi-Fi publik, tindakan aman ...',
    options: [
      'mengakses semua akun penting tanpa perlindungan',
      'mematikan pembaruan selamanya',
      'menghindari transaksi sensitif dan memakai koneksi tepercaya',
      'membagikan kata sandi',
      'menonaktifkan kunci layar',
    ],
    answer: 2,
    explanation: 'Wi-Fi publik berisiko disadap.',
  ),
  TniAcademicQuestion(
    number: 40,
    category: 'Siber',
    question: 'Privasi digital berarti ...',
    options: [
      'semua data harus dipublikasikan',
      'kemampuan mengendalikan dan melindungi informasi pribadi',
      'tidak memakai internet',
      'menghapus semua akun',
      'menggunakan satu sandi untuk semua',
    ],
    answer: 1,
    explanation: 'Privasi berkaitan dengan kendali atas data pribadi.',
  ),
  TniAcademicQuestion(
    number: 41,
    category: 'Siber',
    question: 'Jejak digital adalah ...',
    options: [
      'sidik jari di layar',
      'rekaman aktivitas seseorang di dunia digital',
      'virus komputer',
      'kode rahasia',
      'nomor seri perangkat',
    ],
    answer: 1,
    explanation: 'Aktivitas online dapat meninggalkan rekaman.',
  ),
  TniAcademicQuestion(
    number: 42,
    category: 'Siber',
    question: 'Social engineering memanfaatkan ...',
    options: [
      'kelemahan manusia untuk memperoleh informasi/akses',
      'kerusakan layar',
      'kecepatan prosesor',
      'kabel putus',
      'cuaca',
    ],
    answer: 0,
    explanation: 'Social engineering mengeksploitasi perilaku manusia.',
  ),
  TniAcademicQuestion(
    number: 43,
    category: 'Siber',
    question: 'Jika akun diduga diretas, langkah awal ...',
    options: [
      'mengabaikan',
      'mengganti kata sandi dari perangkat tepercaya dan mengaktifkan 2FA',
      'membagikan OTP',
      'menghapus bukti',
      'mengikuti semua pesan peretas',
    ],
    answer: 1,
    explanation: 'Amankan akun dan pulihkan melalui kanal resmi.',
  ),
  TniAcademicQuestion(
    number: 44,
    category: 'Siber',
    question: 'HTTPS pada alamat situs menunjukkan ...',
    options: [
      'jaminan situs pasti jujur',
      'koneksi terenkripsi antara browser dan situs',
      'komputer bebas virus',
      'internet gratis',
      'data pasti tidak disimpan',
    ],
    answer: 1,
    explanation:
        'HTTPS mengenkripsi koneksi, tetapi bukan jaminan situs terpercaya.',
  ),
  TniAcademicQuestion(
    number: 45,
    category: 'Siber',
    question: 'Prinsip least privilege berarti ...',
    options: [
      'semua orang mendapat akses admin',
      'akses diberikan seperlunya sesuai tugas',
      'akses dibuka tanpa batas',
      'kata sandi tidak diperlukan',
      'semua file publik',
    ],
    answer: 1,
    explanation: 'Akses minimum mengurangi dampak kesalahan/insiden.',
  ),
  TniAcademicQuestion(
    number: 46,
    category: 'Siber',
    question: 'Informasi yang paling tidak boleh diumbar ...',
    options: [
      'hobi umum',
      'OTP dan kata sandi',
      'warna favorit',
      'makanan kesukaan',
      'olahraga favorit',
    ],
    answer: 1,
    explanation: 'OTP dan kata sandi adalah kredensial rahasia.',
  ),
  TniAcademicQuestion(
    number: 47,
    category: 'Siber',
    question: 'Verifikasi informasi keamanan sebaiknya melalui ...',
    options: [
      'tautan acak',
      'sumber resmi dan kanal yang alamatnya diketik/ditandai benar',
      'pesan berantai',
      'komentar anonim',
      'akun palsu',
    ],
    answer: 1,
    explanation: 'Gunakan sumber dan kanal resmi.',
  ),
  TniAcademicQuestion(
    number: 48,
    category: 'Siber',
    question: 'Firewall secara umum berfungsi ...',
    options: [
      'menyaring lalu lintas jaringan berdasarkan aturan',
      'menambah RAM',
      'mencetak dokumen',
      'mengisi baterai',
      'menghapus keyboard',
    ],
    answer: 0,
    explanation: 'Firewall mengatur lalu lintas jaringan.',
  ),
  TniAcademicQuestion(
    number: 49,
    category: 'Siber',
    question: 'Enkripsi mengubah data menjadi ...',
    options: [
      'teks yang mudah dibaca semua orang',
      'bentuk tersandi yang memerlukan kunci untuk dibaca',
      'file yang selalu rusak',
      'gambar otomatis',
      'suara',
    ],
    answer: 1,
    explanation: 'Enkripsi melindungi kerahasiaan data.',
  ),
  TniAcademicQuestion(
    number: 50,
    category: 'Siber',
    question: 'Sikap calon prajurit terhadap data kedinasan adalah ...',
    options: [
      'membagikan demi popularitas',
      'menjaga kerahasiaan dan mengikuti aturan akses',
      'memotret semua dokumen',
      'mengunggah lokasi sensitif',
      'mengirim ke akun pribadi',
    ],
    answer: 1,
    explanation: 'Data kedinasan harus dijaga sesuai aturan dan kewenangan.',
  ),
];

const tniAcademicSource = 'TB XI';
